---
title: "Open Positions"
---

::: {.callout-tip}
## PhD Positions
* __Qualifications__: M.S. degree, mathematical ability, publication(s)
* __Subject Area__: Robotic locomotion and manipulation, machine learning, applied mathematics
* __How to apply__: Email [aykut.satici@utdallas.edu](mailto:aykut.satici@utdallas.edu), subject "PhD Applicant," attach:
  1. BS and MS transcripts
  2. Academic CV, list of publications
  3. Description of interest and match to our laboratory.
:::


::: {.callout-important}
## Hourly Lab Assistant
* __Description__: In this temporary role, we will work hard to complete the remaining tasks of one of our funded project. 
We will incorporate diffusion model as a planning tool into our controller learning framework.
* __Qualifications__: B.S. degree, strong programming skills, experience with Python and C/C++, experience with machine learning and robotics
* __Subject Area__: Robotic locomotion and manipulation, machine learning, applied mathematics
* __How to apply__: Email [aykut.satici@utdallas.edu](mailto:aykut.satici@utdallas.edu), subject "Hourly Lab Assistant Applicant," attach:
  1. BS transcript
  2. Academic CV
  3. Description of interest
:::