---
title: "About"
---

Aykut C. Satici is an Associate Professor of Systems Engineering at the 
University of Texas at Dallas.

## Contact

**Address:** UT Dallas, Systems Engineering, 800 W. Campbell Rd. Richardson, TX 75080-3021 \
**Email:** [aykut.satici@utdallas.edu](mailto:aykut.satici@utdallas.edu)

## Education

University of Texas at Dallas | Richardson, TX | 
PhD in Electrical Engineering | Aug 2010 - May 2014

University of Texas at Dallas | Richardson, TX | 
MS in Mathematical Sciences | Aug 2011 - May 2013

Sabanci University | Istanbul, Turkey | 
MS in Mechatronics Engineering | Sep 2008 - Jun 2010

Sabanci University | Istanbul, Turkey | 
BS in Mechatronics Engineering | Sep 2004 - Jun 2008


## Experience 

Associate Professor | University of Texas at Dallas | Jan 2026 - present

Associate Professor | Boise State University | Jul 2024 - Dec 2025

Assistant Professor | Boise State University | Mar 2017 - Jun 2024

Postdoctoral Researcher | Massachusetts Institute of Technology | Mar 2016 - Mar 2017

Postdoctoral Researcher | University of Naples Federico II | Mar 2015 - Feb 2016

Research Assistant | University of Texas at Dallas | Aug 2010 - May 2014

Research Assistant | Sabanci University | Sep 2008 - Jun 2010