<!DOCTYPE html>
<html lang="en"><head>
<link href="../../../images/robot-arm-favicon.png" rel="icon" type="image/png">
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <meta name="author" content="Aykut C. Satici">
  <title>Aykut C. Satici – Formulating and Solving System Architecture Optimization Problems</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/theme/quarto-0fde88a82f0356838740f155f1088782.css">
  <link rel="stylesheet" href="revealjs-styles.css">
  <link href="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Formulating and Solving System Architecture Optimization Problems – Aykut C. Satici">
<meta property="og:description" content="Aykut C. Satici, Associate Professor of Systems Engineering at UT Dallas. Robotics, nonlinear control, and machine learning.">
<meta property="og:image" content="https://Symplectomorphism.github.io/teaching/ug_courses/systems_architecture/images/robot-control-lab-social.png">
<meta property="og:site_name" content="Aykut C. Satici">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-notes="Chapter 16 follows Crawley, Cameron and Selva (2016), pages 373–416. Build on the decision representations of Chapter 14 and tradespace reasoning of Chapter 15. The focus is formulating six recurring patterns and choosing methods to explore them." class="quarto-title-block center">
  <h1 class="title">Formulating and Solving System Architecture Optimization Problems</h1>
  <p class="subtitle">Systems Architecture · Chapter 16</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Aykut C. Satici 
</div>
</div>
</div>

</section>
<section>
<section id="architecture-as-an-optimization-problem" class="title-slide slide level1 center">
<h1>16.1 Architecture as an optimization problem</h1>
<aside class="notes">
<p>Reconnect to Chapter 14’s architectural decisions and Chapter 15’s Pareto analysis. This chapter supplies a vocabulary for building the decision model and choosing a search strategy. Source: §16.1, pp.&nbsp;373–374.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="learning-objectives" class="slide level2 smaller">
<h2>Learning objectives</h2>
<ul>
<li>Formulate decisions, metrics, a value function, and constraints.</li>
<li>Recognize six recurring <strong>decision patterns</strong>.</li>
<li>Explain the tradeoffs behind common architectural styles.</li>
<li>Estimate search-space size and choose an exploration method.</li>
<li>Critique encodings, decomposition, and heuristic results.</li>
</ul>
<aside class="notes">
<ul>
<li>Ask: “Last chapter we read a tradespace. What must exist before we can generate those points?” A representation of candidates, a validity check, and an evaluation model.</li>
<li>Distinguish the architect’s judgment from a programmed decision. A solver cannot supply missing stakeholder priorities or establish whether the chosen model is appropriate.</li>
<li>This is a full chapter treatment. Suggested teaching breaks follow ASSIGNING, CONNECTING, and §16.5. The exercises can be used as pair discussions or homework.</li>
<li>The learning goal is to formulate and audit a small problem, rather than implement an industrial optimization package.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.1, pp.&nbsp;373–374.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="six-recurring-architecting-tasks" class="slide level2 smaller">
<h2>Six recurring architecting tasks</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Task</th>
<th>Decision to make</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Decompose form or function</td>
<td>Which elements belong together?</td>
</tr>
<tr class="even">
<td>Map function to form</td>
<td>Which objects perform which processes?</td>
</tr>
<tr class="odd">
<td>Specialize</td>
<td>Which solution-specific concept?</td>
</tr>
<tr class="even">
<td>Characterize</td>
<td>Which attribute values?</td>
</tr>
<tr class="odd">
<td>Connect</td>
<td>Which interfaces or operational relationships?</td>
</tr>
<tr class="even">
<td>Select goals</td>
<td>Which candidate goals define the scope?</td>
</tr>
</tbody>
</table>
<aside class="notes">
<ul>
<li>Connect to OPM: processes express function, objects express form, and their relations describe how the system works. Choosing the allocation is an architectural decision; entering the chosen allocation in an OPM model records the result.</li>
<li>Decomposition connects to Chapters 3–8 and 13; mapping to Chapters 6–8 and 12; specialization and characterization to Chapters 4, 7, 13, and 14; connectivity to Chapters 4, 5, and 7; goal selection to Chapter 11.</li>
<li>Ask for a campus robot example of each task. “Choose lithium-ion batteries” specializes form; “choose 500 Wh capacity” characterizes it.</li>
<li>There are six tasks and six patterns, but their mapping is many-to-many.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Table 16.1, p.&nbsp;374.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="formulating-the-model" class="title-slide slide level1 center">
<h1>16.2 Formulating the model</h1>
<aside class="notes">
<p>We now make explicit what was implicit in the Apollo and GNC tradespaces. Ask students to identify the input, output, and assumptions of the evaluator. Source: §16.2, pp.&nbsp;375–377.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="architectures-as-decision-vectors" class="slide level2 smaller">
<h2>Architectures as decision vectors</h2>
<p>For decision <span class="math inline">\(i\)</span>, choose one value from an allowed set <span class="math inline">\(D_i\)</span>:</p>
<p><span class="math display">\[A=(x_1,\ldots,x_n),\qquad x_i\in D_i.\]</span></p>
<p>An Apollo-style encoding includes:</p>
<p><code>[EOR, earthLaunch, LOR, moonArrival, moonDeparture, cmCrew, lmCrew, smFuel, lmFuel]</code></p>
<p>The <strong>dictionary and ordering</strong> give the vector meaning.</p>
<aside class="notes">
<ul>
<li>Read the vector as a compact architecture description, not a complete engineering specification. Units, option dictionaries, and dependencies belong in the model documentation.</li>
<li>Reuse Chapter 14’s naming: earthLaunch has alternatives orbit/direct. An illustrative valid vector is [no, orbit, yes, orbit, orbit, 3, 2, storable, storable].</li>
<li>The printed §16.2 Apollo vector starts with EOR=yes while calling itself the actual architecture. This conflicts with the LOR-only configuration used in our Chapter 14 discussion. Do not teach EOR=yes as the historical Apollo choice. The purpose here is the encoding.</li>
<li>Ask whether swapping the two crew entries preserves meaning. It does not unless the dictionary also changes.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.2, p.&nbsp;375.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-value-function" class="slide level2 smaller">
<h2>The value function</h2>
<p><span class="math display">\[A\ \xrightarrow{\quad V\quad}\ M=(M_1,\ldots,M_p)\]</span></p>
<ul>
<li><strong>Input:</strong> a candidate architecture.</li>
<li><strong>Model:</strong> physics, cost estimates, risk models, and documented judgments.</li>
<li><strong>Output:</strong> metrics that reflect stakeholder needs.</li>
</ul>
<p>Apollo: <strong>minimize launched mass</strong> and <strong>maximize mission success</strong>.</p>
<aside class="notes">
<ul>
<li>The value function is an evaluator that can return a vector. It need not be a single weighted utility score.</li>
<li>Ask what lives inside Apollo’s V: the rocket equation, mass assumptions, and the operation-level risk table. Changing an assumption can move many points in the tradespace.</li>
<li>Explain the compression twice: the architecture vector leaves out design detail, and the metric vector leaves out stakeholder detail. Each compression needs justification.</li>
<li>The arrow is the input/output abstraction of Fig. 16.1, not an OPM procedural link. Keep mathematical evaluation distinct from the system’s physical function.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.2 and Fig. 16.1, pp.&nbsp;375–376.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="multiple-objectives-and-feasibility" class="slide level2 smaller">
<h2>Multiple objectives and feasibility</h2>
<p>Let <span class="math inline">\(\mathcal F\)</span> be the architectures that satisfy all hard constraints.</p>
<p><span class="math display">\[\mathcal A^*=\{A\in\mathcal F:\nexists B\in\mathcal F\text{ with }V(B)\succ V(A)\}\]</span></p>
<p>Here <span class="math inline">\(\succ\)</span> means <strong>dominates</strong> in the stated metric directions.</p>
<ul>
<li>State the preferred direction of every metric.</li>
<li>Retain non-dominated tradeoffs.</li>
<li>Use stakeholder preferences to choose among them.</li>
</ul>
<aside class="notes">
<ul>
<li>The compact Pareto expression identifies candidates through their metric values. Equal metric vectors can correspond to several distinct architectures, all of which may deserve further comparison.</li>
<li>The book writes an argmax of a metric vector. Interpret this as multiobjective non-dominance, not as a request for one vector that independently maximizes every component. Mass is a minimization metric unless its sign is reversed.</li>
<li>Ask students why “best mass and best reliability” might describe no single architecture.</li>
<li>Dominance is conditional on this feasible set and these metrics. A non-dominated point is not a certificate of real-world desirability.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.2, p.&nbsp;375; Chapter 15 Pareto analysis.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="useful-metrics-and-traceable-judgments" class="slide level2 smaller">
<h2>Useful metrics and traceable judgments</h2>
<ul>
<li>A metric should vary across the architectures under study.</li>
<li>Prefer a small, interpretable set: the book suggests <strong>2–5</strong>, often <strong>2–3</strong>.</li>
<li>Keep essential requirements even when they do not distinguish candidates.</li>
<li>Record the rationale behind subjective scores.</li>
<li>Examine sensitivity to aggregation and weights.</li>
</ul>
<aside class="notes">
<ul>
<li>If safety is identical for all modeled hybrid-car candidates, it does not help rank them. That does not authorize dropping safety requirements or verification.</li>
<li>With many competing objectives, dominance becomes less selective. A unique best performer in one metric cannot be dominated, but tied maxima need closer inspection. The book’s statement about any maximum should be read with this qualification.</li>
<li>Scientific value and community engagement can require judgment. Subjectivity is not automatically invalid; untraceable or inconsistent judgment is the problem.</li>
<li>Appendix C discusses rule-based evaluation and explanations. Here students need to know why a score was assigned, not the implementation details of that appendix.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.2, p.&nbsp;376.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="hard-and-soft-constraints" class="slide level2 smaller">
<h2>Hard and soft constraints</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Constraint</th>
<th>Treatment</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Hard</td>
<td>Reject the architecture</td>
<td>LOR requires lunar-orbit arrival</td>
</tr>
<tr class="even">
<td>Soft</td>
<td>Retain it with a penalty</td>
<td>A desirable range target</td>
</tr>
</tbody>
</table>
<p>Illustrative penalty for shortfall below range <span class="math inline">\(r_0\)</span>:</p>
<p><span class="math display">\[C_{\mathrm{effective}}=C+\lambda\max(0,r_0-r),\qquad\lambda\geq0.\]</span></p>
<aside class="notes">
<ul>
<li>Ask students to identify the units of lambda. If C is dollars and range is kilometres, lambda is dollars per kilometre of shortfall.</li>
<li>This linear penalty is a classroom formulation, not a formula supplied by the chapter. Other penalty shapes are possible.</li>
<li>A hard constraint can express physical consistency, an inviolable requirement, or an analyst’s screening rule. The last use deserves scrutiny because it may remove useful architectures before comparison.</li>
<li>The book’s 5 km car-range threshold illustrates screening and soft penalties, not a universal market requirement. A soft penalty cannot make a physically meaningless simulation meaningful.</li>
<li>Optimization transformations such as Lagrange multipliers do not change what stakeholders actually require.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.2, p.&nbsp;377.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="combinatorial-growth-and-model-scope" class="slide level2 smaller">
<h2>Combinatorial growth and model scope</h2>
<p>For independent decision domains:</p>
<p><span class="math display">\[N_{\mathrm{raw}}=\prod_{i=1}^{n}|D_i|.\]</span></p>
<ul>
<li>Categorical choices do not supply ordinary derivatives.</li>
<li>More options improve coverage but increase computation.</li>
<li>Constraints and duplicate encodings change the effective count.</li>
<li>Difficulty depends on the evaluator and mathematical structure.</li>
</ul>
<aside class="notes">
<ul>
<li>“Independent domains” means each decision has a defined choice set, not that the decisions have independent effects on value.</li>
<li>The text describes NP-hardness as exponential time and suggests a practical limit near 15–20 decisions. Treat those as cautions about scale, not formal theorems or universal limits. NP-hardness does not prove an exponential lower bound, and many structured discrete problems are tractable.</li>
<li>Direct gradients are unavailable for unordered labels such as fuel types. Structured integer methods, relaxations, or mixed formulations may still help in suitable problems.</li>
<li>Ask which matters more: 20 binary choices with microsecond evaluation, or eight choices with a day-long simulation? Compute a time budget before deciding.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.2, p.&nbsp;376; §16.6, pp.&nbsp;408–410.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-neoss-example" class="title-slide slide level1 center">
<h1>16.3 The NEOSS example</h1>
<aside class="notes">
<p>NEOSS is the chapter’s NASA Earth Observing Satellite System architecture study. Treat it as the book’s modeling example, not a description of a current NASA program. Source: §16.3, pp.&nbsp;377–379.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="earth-observation-architectures" class="slide level2 smaller">
<h2>Earth-observation architectures</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="assets/chapter16/fig16_2_neoss.png" class="quarto-figure quarto-figure-center" alt="Envisat spacecraft above and the A-Train satellite formation below." height="460"></p>
</figure>
</div>
<div class="side-caption">
<p>Envisat and the A-Train illustrate different ways to organize Earth-observing instruments. Source: Crawley, Cameron &amp; Selva (2016), Fig. 16.2, p.&nbsp;378.</p>
</div>
<aside class="notes">
<ul>
<li>The upper image concentrates instruments on a spacecraft; the lower image shows several coordinated spacecraft. They motivate the packaging decision without establishing which is better.</li>
<li>Scientists need usable data products about land, oceans, and atmosphere, rather than simply a larger satellite count.</li>
<li>Ask: “What could be shared on one spacecraft? What could fail together?” Expected answers include power, communication, launch, schedule, and platform disturbances.</li>
<li>Original image credits in the book: ESA/EPA/Corbis for Envisat and Ed Hanka/NASA for A-Train. Historical illustrations only.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Fig. 16.2, p.&nbsp;378.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="neoss-stakeholders-and-candidate-instruments" class="slide level2 smaller">
<h2>NEOSS stakeholders and candidate instruments</h2>
<p><strong>Scientists value</strong> resolution, accuracy, coverage, and continuous records.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Candidate instruments</th>
<th>Candidate instruments</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Radar altimeter</td>
<td>GPS receiver</td>
</tr>
<tr class="even">
<td>Conical microwave radiometer</td>
<td>Infrared spectrometer</td>
</tr>
<tr class="odd">
<td>Laser altimeter / lidar</td>
<td>Millimeter-wave sounder</td>
</tr>
<tr class="even">
<td>Synthetic aperture radar</td>
<td>High-resolution optical imager</td>
</tr>
</tbody>
</table>
<p>Cost, schedule, and risk also enter the evaluation.</p>
<aside class="notes">
<ul>
<li>In OPM language, Measuring creates measurement information about an environmental property, and Processing produces a data product. Instruments are objects that enable the relevant processes.</li>
<li>A laser altimeter and a synthetic aperture radar are alternative forms for some topographic measurements, with different capabilities. Selecting both can add value or create redundant capabilities.</li>
<li>Explain spatial resolution as distinguishable ground detail and temporal resolution as how frequently useful observations arrive. Data continuity asks whether records remain comparable and uninterrupted across missions.</li>
<li>The chapter later uses six instruments and three orbit types to isolate the ASSIGNING pattern. Those are reduced examples, not a contradictory eight-instrument count.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.3, pp.&nbsp;377–379.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="neoss-decision-groups" class="slide level2 smaller">
<h2>NEOSS decision groups</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Group</th>
<th>Choices</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Instrument selection</td>
<td>Which of the eight instruments?</td>
</tr>
<tr class="even">
<td>Instrument packaging</td>
<td>Which spacecraft, orbits, and constellations?</td>
</tr>
<tr class="odd">
<td>Mission scheduling</td>
<td>Which launch order and dates?</td>
</tr>
</tbody>
</table>
<p>Initial orbital options: <strong>1–3 planes</strong>, <strong>1–4 satellites per plane</strong>, true polar / sun-synchronous / tropical, <strong>400 / 600 / 800 km</strong>.</p>
<aside class="notes">
<ul>
<li>Higher altitude generally trades coarser ground resolution for broader coverage for a given instrument geometry. This is a model relationship, not a claim that every instrument’s performance depends only on altitude.</li>
<li>Power limits and electromagnetic interference couple the instrument and platform decisions.</li>
<li>A replacement mission launched after an existing mission ends can create a data gap even if its instrument is excellent. Shared budgets also link launch dates.</li>
<li>Ask which decision group influences scientific value. All of them do, which anticipates the decomposition discussion.</li>
<li>Packaging includes the orbital design, not just fitting objects in a box.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.3, p.&nbsp;379.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="six-patterns-of-architectural-decisions" class="title-slide slide level1 center">
<h1>16.4 Six patterns of architectural decisions</h1>
<aside class="notes">
<p>A pattern describes recurring decision structure. An architectural style describes a recognizable family of solutions within that structure. Source: §16.4, pp.&nbsp;379–403.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="patterns-and-architectural-styles" class="slide level2 smaller">
<h2>Patterns and architectural styles</h2>
<ul>
<li><strong>Pattern:</strong> the structure of a recurring decision problem.</li>
<li><strong>Style:</strong> a characteristic way to organize the resulting architecture.</li>
</ul>
<p>Examples:</p>
<ul>
<li>ASSIGNING admits channelized and fully cross-strapped styles.</li>
<li>PARTITIONING admits monolithic and distributed styles.</li>
<li>CONNECTING admits bus, star, ring, mesh, and tree styles.</li>
</ul>
<aside class="notes">
<ul>
<li>The chapter traces the idea to Christopher Alexander’s building patterns and the reusable software designs popularized by the Gang of Four.</li>
<li>Alexander’s example of light from two sides of a room includes a recurring problem and ways to address it in differently sized buildings. The architectural decision patterns here chiefly organize the problem rather than prescribe one universal solution.</li>
<li>Classical optimization problems, including knapsack and traveling salesman, provide related mathematical structures.</li>
<li>Ask whether “choose a distributed architecture” specifies a decision pattern or a style. It is a style preference that still requires concrete grouping decisions.</li>
<li>Patterns are useful mental models even when no optimization program is written.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4, pp.&nbsp;379–381.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-six-patterns-at-a-glance" class="slide level2 smaller">
<h2>The six patterns at a glance</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Pattern</th>
<th>Core question</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DECISION-OPTION</td>
<td>Which one option for each decision?</td>
</tr>
<tr class="even">
<td>DOWN-SELECTING</td>
<td>Which subset of candidates?</td>
</tr>
<tr class="odd">
<td>ASSIGNING</td>
<td>Which links between two sets?</td>
</tr>
<tr class="even">
<td>PARTITIONING</td>
<td>Which non-overlapping groups?</td>
</tr>
<tr class="odd">
<td>PERMUTING</td>
<td>Which one-to-one placement or order?</td>
</tr>
<tr class="even">
<td>CONNECTING</td>
<td>Which links within a fixed node set?</td>
</tr>
</tbody>
</table>
<aside class="notes">
<ul>
<li>Use the vocabulary consistently throughout the lecture. The names identify mathematical structure, not six mutually exclusive kinds of real system.</li>
<li>Ask students to classify packing instruments into unlabeled spacecraft versus allocating instrument copies to named orbits. Those are different questions despite both sounding like “assignment.”</li>
<li>We will give each pattern a representation, a count before extra constraints, a case example, and the architectural tradeoffs it exposes.</li>
<li>Keep the distinction between an encoding and a physical system visible: a binary 1 can mean selecting an instrument, installing a copy, or connecting a cable depending on the model.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Table 16.2, p.&nbsp;381.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="decision-option-one-choice-per-decision" class="slide level2 smaller">
<h2>DECISION-OPTION: one choice per decision</h2>
<p><span class="math display">\[A=(x_1,\ldots,x_n),\quad x_i\in O_i,\qquad N=\prod_i m_i.\]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Decision</th>
<th>Option 1</th>
<th>Option 2</th>
<th>Option 3</th>
<th>Option 4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1.1</td>
<td>1.2</td>
<td>1.3</td>
<td></td>
</tr>
<tr class="even">
<td>2</td>
<td>2.1</td>
<td>2.2</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>3</td>
<td>3.1</td>
<td>3.2</td>
<td>3.3</td>
<td>3.4</td>
</tr>
</tbody>
</table>
<p>Three decisions give <span class="math inline">\(3\times2\times4=24\)</span> raw architectures.</p>
<aside class="notes">
<ul>
<li>This editable morphological matrix reproduces the structure of Table 16.3. An architecture selects one entry in each row.</li>
<li>Ask students to decode [2,1,3]. It chooses options 1.2, 2.1, and 3.3.</li>
<li>Each decision has its own domain. A memory capacity is not automatically an option for processor type.</li>
<li>Continuous attributes require a finite set or a stated discretization if this pattern is used literally. The book’s spring rates of 400, 500, and 600 lb/in illustrate such a choice.</li>
<li>Sequence and compatibility are not implicit. Add constraints when needed.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4, pp.&nbsp;381–384; Table 16.3.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="two-decision-option-architectures" class="slide level2 smaller">
<h2>Two DECISION-OPTION architectures</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="assets/chapter16/fig16_3_decision_option.png" class="quarto-figure quarto-figure-center" alt="Two selections among three decisions with respectively three, two, and four options." height="440"></p>
</figure>
</div>
<div class="side-caption">
<p>The same choice sets support different architecture vectors. Source: Crawley, Cameron &amp; Selva (2016), Fig. 16.3, p.&nbsp;382.</p>
</div>
<aside class="notes">
<ul>
<li>Trace one selected option for each decision in each half of the diagram. These are generic decision graphs, not a system-behavior notation.</li>
<li>Invite a student to move from [2,1,3] to [1,1,2]. Two entries change; the second decision remains fixed.</li>
<li>Discuss why “independent options” does not imply that their performance contributions can be added independently. The evaluator may have strong interactions.</li>
<li>A decision tree can express the same choices, but it can quickly become too large to inspect.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Fig. 16.3, p.&nbsp;382.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="autonomous-underwater-vehicle-choices" class="slide level2 smaller">
<h2>Autonomous underwater vehicle choices</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="assets/chapter16/fig16_4_auv.png" class="quarto-figure quarto-figure-center" alt="Three autonomous underwater vehicle designs with different forms." height="460"></p>
</figure>
</div>
<div class="side-caption">
<p>Bluefin 12 BOSS, Nereus, and SeaExplorer illustrate alternative AUV forms. Source: Crawley, Cameron &amp; Selva (2016), Fig. 16.4, p.&nbsp;383.</p>
</div>
<aside class="notes">
<ul>
<li>Use the images to motivate specialization before presenting the count. Shape, propulsion, power, and sensing interact with the operational concept.</li>
<li>Ask whether hovering and efficient long-distance transit necessarily favor the same configuration.</li>
<li>These are examples in the book, not a specification comparison of current products. Original credits: NOAA; AUVfest 2008/Navy/NOAA; Alseamar.</li>
<li>The next table lists the chapter’s abstract options. Do not infer that each pictured vehicle has every listed alternative.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Fig. 16.4, p.&nbsp;383.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="auv-ten-decisions-4608-combinations" class="slide level2 smaller">
<h2>AUV: ten decisions, 4,608 combinations</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Decision</th>
<th>Alternatives</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Configuration</td>
<td>Torpedo, blended wing, hybrid, rectangular</td>
</tr>
<tr class="even">
<td>Swim / hover</td>
<td>Yes or no for each</td>
</tr>
<tr class="odd">
<td>Navigation</td>
<td>Dead reckoning, acoustic positioning</td>
</tr>
<tr class="even">
<td>Propulsion</td>
<td>Propeller, Kort nozzle, passive gliding</td>
</tr>
<tr class="odd">
<td>Motor</td>
<td>Brushed, brushless</td>
</tr>
<tr class="even">
<td>Power</td>
<td>Rechargeable batteries, fuel cells, solar</td>
</tr>
<tr class="odd">
<td>Sonar / magnetometer / thermistor</td>
<td>Yes or no for each</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(4(2)(2)(2)(3)(2)(3)(2)(2)(2)=4{,}608\)</span> <strong>before constraints</strong>.</p>
<aside class="notes">
<ul>
<li>There are ten decisions, despite seven displayed rows: swim and hover are separate, as are the three sensor decisions.</li>
<li>Ask for invalid or operationally implausible combinations. Passive gliding with a motor choice may introduce irrelevant values; solar power depends on an appropriate operating concept.</li>
<li>A raw Cartesian product is a starting point. It is not a count of 4,608 feasible, distinct, useful vehicles.</li>
<li>This pattern commonly supports specialization and characterization of form and function.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4, pp.&nbsp;383–384.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="aerial-network-duplicate-encodings" class="slide level2 smaller">
<h2>Aerial network: duplicate encodings</h2>
<p>Ten candidate balloon sites. Per site:</p>
<ul>
<li>Radio: type A, type B, or <strong>no balloon</strong>.</li>
<li>Altitude: low or high.</li>
</ul>
<p>Raw encoding: <span class="math inline">\(6^{10}=60{,}466{,}176\)</span> vectors.</p>
<p>With one canonical no-balloon state:</p>
<p><span class="math display">\[5^{10}=9{,}765{,}625\ \text{distinct site-choice combinations}.\]</span></p>
<aside class="notes">
<ul>
<li>This derived count assumes at most one balloon per site and that all four radio-altitude combinations are allowed for an occupied site.</li>
<li>The book deliberately exposes the duplication: an empty site has no physical altitude. Two encoded states therefore represent one architecture choice.</li>
<li>Ask students whether eliminating duplicate encodings is the same as eliminating a bad architecture. It is not; it avoids counting the same alternative repeatedly.</li>
<li>If radio types can mix across sites, the model must address interoperability. If several balloon types can occupy a site, the ASSIGNING formulation later allows a different design space.</li>
<li>The chapter’s approximate 60 million count describes raw vectors.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4, p.&nbsp;384; canonical count derived for class.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="down-selecting-a-subset-of-candidates" class="slide level2 smaller">
<h2>DOWN-SELECTING: a subset of candidates</h2>
<p><span class="math display">\[S\subseteq U,\qquad A=(x_1,\ldots,x_m),\ x_i\in\{0,1\}.\]</span></p>
<p><span class="math display">\[N=2^m\quad\text{including the empty and full subsets}.\]</span></p>
<p>Instrument order:</p>
<p><code>[radiometer, altimeter, imager, sounder, lidar, GPS, SAR, spectrometer]</code></p>
<p><code>[1,1,0,0,0,1,0,0]</code> selects radiometer, altimeter, and GPS.</p>
<aside class="notes">
<ul>
<li>Ask what flipping a bit does physically: it adds or removes one candidate instrument. In ordinary DECISION-OPTION, a change may instead replace one incompatible option with another.</li>
<li>For eight instruments, there are 256 subsets before budget and other constraints.</li>
<li>The subset structure gives search algorithms useful information. Adding an item changes its cost and benefit and may change interactions with items already present.</li>
<li>The chapter’s second printed example has a vector with an extra entry relative to the eight-item set. Its intended imager/sounder/SAR/spectrometer subset is [0,0,1,1,0,0,1,1]. Keep the dictionary explicit.</li>
<li>Selecting goals and choosing among several allowable solution forms are common applications.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4, pp.&nbsp;384–386.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="two-selected-subsets" class="slide level2 smaller">
<h2>Two selected subsets</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="assets/chapter16/fig16_5_down_selecting.png" class="quarto-figure quarto-figure-center" alt="Two subsets of eight candidate elements shown with selected and omitted elements." height="390"></p>
</figure>
</div>
<div class="side-caption">
<p>Both architectures use the same candidate set; the selected members differ. Source: Crawley, Cameron &amp; Selva (2016), Fig. 16.5 and §16.4, pp.&nbsp;385–386.</p>
</div>
<aside class="notes">
<ul>
<li>Solid rectangles show selected elements and dashed rectangles show omitted ones. Ask students to read the corresponding binary strings.</li>
<li>A point with fewer elements can outperform a larger subset if the latter wastes resources or introduces interference.</li>
<li>In the NEOSS case, selecting radar altimetry without the complementary radiometer can reduce achievable measurement accuracy because an atmospheric correction is missing.</li>
<li>Ask what model output would reveal that loss. A count of instruments alone would not.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Fig. 16.5 and §16.4, pp.&nbsp;385–386.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="interactions-change-subset-value" class="slide level2 smaller">
<h2>Interactions change subset value</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Interaction</th>
<th>Everyday example</th>
<th>NEOSS example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Synergy</td>
<td>Toothbrush with toothpaste</td>
<td>Altimeter with radiometer</td>
</tr>
<tr class="even">
<td>Redundancy</td>
<td>Several similar toothpastes</td>
<td>Overlapping topographic measurements</td>
</tr>
<tr class="odd">
<td>Interference</td>
<td>Hot food beside a cold drink</td>
<td>Power or orbit conflicts</td>
</tr>
</tbody>
</table>
<p>A useful subset combines <strong>high synergy</strong>, <strong>low interference</strong>, and <strong>limited redundancy</strong>.</p>
<aside class="notes">
<ul>
<li>A classical 0/1 knapsack adds fixed item values subject to a resource bound. This chapter’s subsets can have context-dependent values, so simply sorting items by benefit/cost can fail.</li>
<li>Radar altimetry and microwave radiometry can work together through humidity correction. SAR and lidar can compete for resources or preferred orbital conditions. These interactions require the evaluator to know more than instrument names.</li>
<li>The book calls favorable recurring combinations schemata. We will return to the precise binary-string meaning in genetic algorithms.</li>
<li>Ask whether redundancy is always wasteful. It may instead be valuable when the metric includes fault tolerance; interpretation depends on the function and failure model.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4 and Box 16.1, pp.&nbsp;386–387.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-worked-subset-selection-problem" class="slide level2 smaller">
<h2>A worked subset-selection problem</h2>
<p><strong>Classroom data:</strong> budget <span class="math inline">\(=6\)</span> cost units.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Item</th>
<th style="text-align: right;">Cost</th>
<th style="text-align: right;">Standalone benefit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td>B</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td>C</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">8</td>
</tr>
</tbody>
</table>
<p>Selecting <strong>A and B together</strong> adds a synergy bonus of 4.</p>
<p>Which feasible subset has the highest benefit?</p>
<aside class="notes">
<ul>
<li>Give students a minute before revealing the answer. Feasible subsets are empty, A, B, C, and AB. AC, BC, and ABC exceed the budget.</li>
<li>Benefits are 0, 4, 3, 8, and 4+3+4=11 respectively. AB wins even though C has the highest standalone benefit/cost ratio.</li>
<li>Without the synergy term, C would beat AB’s benefit of 7. Thus the interaction changes the architecture recommendation.</li>
<li>Ask how to encode the evaluator: B(x)=4x_A+3x_B+8x_C+4x_Ax_B, with 3x_A+3x_B+4x_C≤6.</li>
<li>These numbers are illustrative and do not quantify actual instruments.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4 and Box 16.1, pp.&nbsp;386–387; classroom example.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="subset-selection-beyond-instruments" class="slide level2 smaller">
<h2>Subset selection beyond instruments</h2>
<ul>
<li><strong>NLP strategies:</strong> complementary methods can improve coverage while consuming development and computation resources.</li>
<li><strong>Spectral bands:</strong> additional bands can add information, duplicate a capability, or enable corrections.</li>
<li><strong>Projects and goals:</strong> a limited budget forces scope choices.</li>
</ul>
<p>The benefit of an addition depends on what is already selected.</p>
<aside class="notes">
<ul>
<li>The chapter uses IBM Watson’s combination of language-processing strategies and a hypothetical next-generation RapidEye band-selection problem. Present these as historical teaching cases, not current product specifications.</li>
<li>Deep and shallow language-processing approaches motivate complementary capabilities. For spectral bands, measurements of the same constituent motivate redundancy, while cloud or atmospheric information can enable corrections.</li>
<li>The text mentions 2.2 and 4.7 micrometre bands and a 1.6 micrometre correction example. The lesson is conditional value; detailed spectral retrieval physics would require a separate instrument model.</li>
<li>Ask students to name two course projects that share equipment. Their combined cost need not equal their separate costs.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4, p.&nbsp;386.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="assigning-links-between-two-sets" class="slide level2 smaller">
<h2>ASSIGNING: links between two sets</h2>
<p>For <span class="math inline">\(m\)</span> left elements and <span class="math inline">\(n\)</span> right elements:</p>
<p><span class="math display">\[a_{ij}=\begin{cases}1&amp;\text{left }i\text{ is assigned to right }j\\0&amp;\text{otherwise.}\end{cases}\]</span></p>
<p><span class="math display">\[A\in\{0,1\}^{m\times n},\qquad N=2^{mn}.\]</span></p>
<p>Each left element may link to <strong>none, one, or several</strong> right elements.</p>
<aside class="notes">
<ul>
<li>This is a many-to-many relation in the general pattern. Exactly-one assignment is an additional constraint, not the default.</li>
<li>Examples include workers to tasks, processes to objects, instruments to orbits, or sensors to computers. In OPM, a process-object allocation still needs a precise procedural role; a generic binary matrix does not specify whether an object enables, is consumed by, or is affected by a process.</li>
<li>The matrix has mn independent binary positions before added constraints. Six instruments and three orbits give 2^18=262,144 architectures.</li>
<li>Ask whether assigning one instrument type to two orbits means teleporting one physical unit. It generally means deploying two copies.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4, pp.&nbsp;388–390.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="neoss-instrument-to-orbit-assignment" class="slide level2 smaller">
<h2>NEOSS instrument-to-orbit assignment</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="assets/chapter16/fig16_6_assigning.png" class="quarto-figure quarto-figure-center" alt="Six instrument types with links to geostationary, sun-synchronous, and polar orbits." height="460"></p>
</figure>
</div>
<div class="side-caption">
<p>Instrument types can appear in more than one orbit, or in none. Source: Crawley, Cameron &amp; Selva (2016), Fig. 16.6, p.&nbsp;388.</p>
</div>
<aside class="notes">
<ul>
<li>Trace the sounder and radiometer to geostationary and sun-synchronous orbits, radar to sun-synchronous and polar orbits, imager to sun-synchronous orbit, and lidar to polar orbit. GPS is unused.</li>
<li>Count eight assignments in this illustration. A type appearing twice represents multiple deployed instances in this simplified model.</li>
<li>This reduced example introduces geostationary orbit and six instrument types to illustrate a pattern. It is not the same domain as the earlier eight-instrument NEOSS setup.</li>
<li>Ask which constraints would limit available power or prohibit an instrument-orbit pairing.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Fig. 16.6, p.&nbsp;388.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="assignment-constraints-change-the-count" class="slide level2 smaller">
<h2>Assignment constraints change the count</h2>
<p>For <span class="math inline">\(m\)</span> left elements and <span class="math inline">\(n\)</span> right elements:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Rule for each left element</th>
<th style="text-align: right;">Raw count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Any subset</td>
<td style="text-align: right;"><span class="math inline">\(2^{mn}\)</span></td>
</tr>
<tr class="even">
<td>At least one right element</td>
<td style="text-align: right;"><span class="math inline">\((2^n-1)^m\)</span></td>
</tr>
<tr class="odd">
<td>Exactly one right element</td>
<td style="text-align: right;"><span class="math inline">\(n^m\)</span></td>
</tr>
</tbody>
</table>
<p>For 3 sensors and 2 computers: <strong>64</strong>, <strong>27</strong>, or <strong>8</strong>.</p>
<aside class="notes">
<ul>
<li>Derive one row at a time. Two computers have four subsets: empty, first, second, both. Removing empty leaves three; requiring exactly one leaves two.</li>
<li>Raise each per-sensor count to three because the constraints in this classroom example are local to each sensor. Shared capacity limits would couple the rows and invalidate that simple product.</li>
<li>The book’s second generic example uses 3 by 5 elements, giving 2^15=32,768.</li>
<li>Ask students to explain why “exactly one computer per sensor” does not require each computer to have exactly one sensor. Many-to-one mappings remain possible.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4, pp.&nbsp;388–392; constrained counts derived for class.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="channelized-and-cross-strapped-styles" class="slide level2 smaller">
<h2>Channelized and cross-strapped styles</h2>
<div class="columns">
<div class="column" style="width:48%;">
<p><strong>Channelized</strong></p>
<p><img data-src="assets/chapter16/fig16_8_channelized.png" alt="Three independent one-to-one channels." height="340"></p>
</div><div class="column" style="width:48%;">
<p><strong>Fully cross-strapped</strong></p>
<p><img data-src="assets/chapter16/fig16_9_cross_strapped.png" alt="All three left elements connected to all three right elements." height="340"></p>
</div></div>
<div class="side-caption">
<p>Source: Figs. 16.8–16.9, p.&nbsp;391. Partial connections give intermediate architectures.</p>
</div>
<aside class="notes">
<ul>
<li>The figures show three isolated channels versus nine cross-connections. The ideal isolated-chain illustration is stronger than merely saying each left node has one right node: sharing a right node could still couple the chains.</li>
<li>Reconnect to Chapter 15’s GNC architecture study. Sensor-to-computer and computer-to-actuator links are separate assignment layers.</li>
<li>The book uses Saturn V’s functional decomposition and X-38’s independent buses as channelized examples, and Total Football and Space Shuttle avionics as examples of more coupled mappings or connectivity.</li>
<li>Suh’s functional-independence principle motivates decoupling. Shared form can nevertheless reduce parts, mass, volume, and cost.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4, pp.&nbsp;390–392; Figs. 16.8–16.9.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="connectivity-cost-and-failures" class="slide level2 smaller">
<h2>Connectivity, cost, and failures</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Channelized tendencies</th>
<th>Cross-strapped tendencies</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fewer interfaces and lower connection cost</td>
<td>More interfaces and greater complexity</td>
</tr>
<tr class="even">
<td>Fewer alternative paths</td>
<td>More potential redundancy and throughput</td>
</tr>
<tr class="odd">
<td>Greater isolation between chains</td>
<td>More opportunities for failure propagation</td>
</tr>
</tbody>
</table>
<p>The choice depends on <strong>connection cost</strong>, <strong>value of reliability</strong>, and the <strong>failure model</strong>.</p>
<aside class="notes">
<ul>
<li>Avoid turning these tendencies into guarantees. A fully cross-strapped system is more reliable only under an appropriate model of component, interface, and dependent failures.</li>
<li>The book’s common-cause discussion includes one failed sensor damaging connected computers. Distinguish this propagated failure from a shared external cause such as loss of common power; both undermine an independent-failure calculation.</li>
<li>Ask which style would be attractive if cables are nearly massless but can transmit damaging faults. The answer may differ from the independent-failure result.</li>
<li>An extra nine of reliability costs something. The stakeholder’s cost-reliability preferences and credible failure dependencies help determine whether that cost is worthwhile.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Box 16.2, p.&nbsp;392.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="partitioning-exhaustive-disjoint-groups" class="slide level2 smaller">
<h2>PARTITIONING: exhaustive, disjoint groups</h2>
<p>Partition <span class="math inline">\(U\)</span> into nonempty groups <span class="math inline">\(S_1,\ldots,S_k\)</span>:</p>
<p><span class="math display">\[\bigcup_{i=1}^{k}S_i=U,\qquad S_i\cap S_j=\varnothing\quad(i\ne j).\]</span></p>
<ul>
<li>Every element belongs to <strong>exactly one</strong> group.</li>
<li>The number of groups can vary from 1 to <span class="math inline">\(|U|\)</span>.</li>
<li>Group labels do not define different architectures.</li>
</ul>
<p>Example: <code>{{radar, radiometer}, {imager, sounder, GPS}, {lidar}}</code>.</p>
<aside class="notes">
<ul>
<li>Pairwise disjointness is essential. The book prints an empty intersection over all groups, which is too weak: three groups can have no common element while still overlapping pairwise.</li>
<li>Give the counterexample {a,b}, {b,c}, {a,c}. Their total intersection is empty, but each element appears twice. It is not a valid partition.</li>
<li>Unlabeled bins distinguish a partition from assignment to named spacecraft or orbits. Relabeling satellite 1 as satellite 2 changes no grouping by itself.</li>
<li>Partitioning does not decide precise facility positions or orbital parameters; those require further decisions.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4, p.&nbsp;393.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="two-instrument-packaging-architectures" class="slide level2 smaller">
<h2>Two instrument-packaging architectures</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="assets/chapter16/fig16_10_partitioning.png" class="quarto-figure quarto-figure-center" alt="Six instruments partitioned into three groups on the left and four on the right." height="400"></p>
</figure>
</div>
<div class="side-caption">
<p>Every instrument appears exactly once; the groups change. Source: Crawley, Cameron &amp; Selva (2016), Fig. 16.10, p.&nbsp;393.</p>
</div>
<aside class="notes">
<ul>
<li>Ask students to list the groups on each side. Left: lidar alone; radar with radiometer; imager with sounder and GPS. Right: lidar alone; radar alone; imager with sounder; radiometer with GPS.</li>
<li>Count instruments rather than labels to verify completeness. Ask what decision would permit leaving one out: a separate DOWN-SELECTING decision.</li>
<li>Explain that the partition determines what shares a platform. A platform design step must subsequently check mass, power, interfaces, and orbit compatibility.</li>
<li>Grouping radar and radiometer can support measurement synergy, but only if their operating conditions actually permit coordinated observations.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Fig. 16.10, p.&nbsp;393.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="encoding-and-counting-partitions" class="slide level2 smaller">
<h2>Encoding and counting partitions</h2>
<p>For ordered elements <span class="math inline">\([a,b,c,d]\)</span>:</p>
<p><code>[1,1,2,3]</code> represents <code>{{a,b},{c},{d}}</code>.</p>
<p><code>[7,7,2,9]</code> represents the <strong>same partition</strong>.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Elements <span class="math inline">\(m\)</span></th>
<th style="text-align: right;">Partitions <span class="math inline">\(B_m\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>3</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td>5</td>
<td style="text-align: right;">52</td>
</tr>
<tr class="odd">
<td>8</td>
<td style="text-align: right;">4,140</td>
</tr>
<tr class="even">
<td>10</td>
<td style="text-align: right;">115,975</td>
</tr>
</tbody>
</table>
<aside class="notes">
<ul>
<li>Canonical labels assigned in order of first appearance eliminate this representation redundancy. Starting from [7,7,2,9], rename the first encountered group 1, the next 2, and the next 3.</li>
<li>Bell numbers count all partitions. Stirling numbers of the second kind S(m,k) count partitions into exactly k nonempty groups; B_m is their sum.</li>
<li>Ask students to enumerate the five partitions of {a,b,c}: all together, all separate, and each of the three possible pairs plus a singleton.</li>
<li>Fig. 16.11 illustrates two eight-element partitions. Its B_8 count is captured in this editable table.</li>
<li>Do not use m^m as the number of distinct unlabeled partitions.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4, pp.&nbsp;394–395; reference [19], pp.&nbsp;417–418.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="partitioning-in-other-systems" class="slide level2 smaller">
<h2>Partitioning in other systems</h2>
<ul>
<li><strong>Oil reservoirs:</strong> group reservoirs served by a common facility.</li>
<li><strong>Service engineers:</strong> group engineers supported by a common supply manager.</li>
<li><strong>Function decomposition:</strong> group lower-level processes into larger functions.</li>
</ul>
<p>The partition decides <strong>which elements share a group</strong>. Further models determine location, capacity, and feasibility.</p>
<aside class="notes">
<ul>
<li>The book’s three-reservoir example has five partitions. Ask students whether grouping A and B locates their common facility on a map. It does not.</li>
<li>The service network example has 3,000 engineers, each assigned to one manager. Capacity and geography can make many mathematical partitions impractical.</li>
<li>Mapping function to form and decomposition are the most direct architecting tasks for this pattern.</li>
<li>In OPM, a grouping choice can inform decomposition or the allocation of processes to objects. Preserve the distinction between a structural grouping and a claim about what each process actually does.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4, pp.&nbsp;394–395.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="monolithic-and-distributed-architectures" class="slide level2 smaller">
<h2>Monolithic and distributed architectures</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Monolithic</th>
<th>Fully distributed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One large group</td>
<td>One group per element</td>
</tr>
<tr class="even">
<td>Shares common infrastructure</td>
<td>Replicates common infrastructure</td>
</tr>
<tr class="odd">
<td>Can capture close-coupled synergies</td>
<td>Can isolate interference and failures</td>
</tr>
<tr class="even">
<td>Integration links development schedules</td>
<td>Smaller units can evolve separately</td>
</tr>
<tr class="odd">
<td>Shared resources may become bottlenecks</td>
<td>Coordination can add cost and complexity</td>
</tr>
</tbody>
</table>
<aside class="notes">
<ul>
<li>These styles are the two ends of a partitioning tradespace. Intermediate groupings can preserve valuable synergies while separating incompatible elements.</li>
<li>Cost depends on both replicated common functionality and the cost of interference. A shared solar array saves duplication but can create a power bottleneck and a common vulnerability.</li>
<li>Distributed systems are not automatically redundant. If each unique instrument flies once, losing one still loses its measurement, even if the other instruments survive.</li>
<li>Ask students whether faster replacement of a smaller satellite improves evolvability even when the initial hardware costs more.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Box 16.3, pp.&nbsp;395–396.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-drives-the-grouping-decision" class="slide level2 smaller">
<h2>What drives the grouping decision?</h2>
<ul>
<li>Strength of synergies and interferences.</li>
<li>Physical proximity needed for those interactions.</li>
<li>Cost of replicated power, communication, structure, and support.</li>
<li>Resource competition and failure concentration.</li>
<li>Development time, expense profile, and opportunities to upgrade.</li>
</ul>
<aside class="notes">
<ul>
<li>DOWN-SELECTING asks whether both instruments are present. PARTITIONING asks whether their placement allows the interaction to occur.</li>
<li>Radar-altimeter and radiometer measurements must be sufficiently coordinated and registered to realize their synergy. Merely flying somewhere in the same program is insufficient.</li>
<li>In the book’s Envisat discussion, shared infrastructure and common observations come with power competition, launch risk, and dependence on the least ready instrument. Metop illustrates vibration interference from a scanning instrument to a sensitive sounder.</li>
<li>The chapter reports Envisat at roughly eight tonnes, ten instruments, over two billion euros, and over ten years of development. Use these as historical case details, not current cost estimates. Its specific SAR duty-cycle claim should not be generalized to all radar modes.</li>
<li>Ask which grouping remains attractive if the maturity of one instrument slips by three years.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4 and Box 16.3, pp.&nbsp;395–397.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="permuting-exclusive-positions" class="slide level2 smaller">
<h2>PERMUTING: exclusive positions</h2>
<p>Match <span class="math inline">\(m\)</span> elements to <span class="math inline">\(m\)</span> positions, one element per position.</p>
<p><span class="math display">\[N=m!\]</span></p>
<p>For the order <strong>2, 4, 1, 3</strong>:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Representation</th>
<th>Vector</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Element occupying each successive position</td>
<td><code>[2,4,1,3]</code></td>
</tr>
<tr class="even">
<td>Position assigned to each successive element</td>
<td><code>[3,1,4,2]</code></td>
</tr>
</tbody>
</table>
<p>The two vectors are inverse descriptions of the same arrangement.</p>
<aside class="notes">
<ul>
<li>Use explicit semantics instead of relying on potentially confusing labels such as “element-based.” In the second row, element 1 goes to position 3, element 2 to position 1, element 3 to position 4, and element 4 to position 2.</li>
<li>Ask students to reconstruct the first vector from the second. This is a useful check against encoding mistakes.</li>
<li>Positions can be launch slots, locations on a board, or other exclusive options. The pattern does not require a temporal interpretation.</li>
<li>A permutation is a bijection: each element and each position appears exactly once.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4, pp.&nbsp;397–398.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="two-permutations-of-five-elements" class="slide level2 smaller">
<h2>Two permutations of five elements</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="assets/chapter16/fig16_12_permuting.png" class="quarto-figure quarto-figure-center" alt="Two one-to-one mappings of five elements to five positions." height="440"></p>
</figure>
</div>
<div class="side-caption">
<p>Five elements have 5! = 120 possible arrangements. Source: Crawley, Cameron &amp; Selva (2016), Fig. 16.12 and §16.4, pp.&nbsp;397–398.</p>
</div>
<aside class="notes">
<ul>
<li>Trace all five links and verify that no position has two occupants. A generic binary matrix without row and column constraints would admit many invalid configurations.</li>
<li>Ask why a vector with repeated entries, such as [1,1,3,4,5], cannot represent this permutation.</li>
<li>The count for 15 elements is 15!=1,307,674,368,000, already over a trillion. This motivates selective search.</li>
<li>Factorial growth eventually exceeds any fixed-base exponential c^m. The exact practical limit still depends on evaluation cost and exploitable structure.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Fig. 16.12 and §16.4, pp.&nbsp;397–398.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="order-layout-and-operations" class="slide level2 smaller">
<h2>Order, layout, and operations</h2>
<ul>
<li><strong>NEOSS:</strong> launch order affects data continuity and budgets.</li>
<li><strong>Circuit layout:</strong> placement changes total interconnection length.</li>
<li><strong>Vehicle operations:</strong> task order changes travel and resource use.</li>
<li><strong>Exploration portfolios:</strong> destination sequence changes capability development.</li>
</ul>
<p>An order alone may still need dates, durations, or geometry.</p>
<aside class="notes">
<ul>
<li>The book connects circuit placement to the importance of total wire length and uses NASA’s historical Flexible Path discussion as a portfolio-sequencing example.</li>
<li>Treat those as illustrations of decision structure, not claims about current chip specifications or current NASA plans.</li>
<li>Ask whether “A then B” gives a launch date. It does not. Development durations, launch availability, annual budgets, and precedence constraints can still determine feasibility.</li>
<li>Operations belong in architectural reasoning early because the concept of operations generates goals and metrics.</li>
<li>Position exclusivity also supports layouts with no natural first-to-last ordering.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4, pp.&nbsp;398–399.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="front-loaded-and-incremental-deployment" class="slide level2 smaller">
<h2>Front-loaded and incremental deployment</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Front-loaded high-value deployment</th>
<th>Incremental deployment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Prioritizes the most valuable systems</td>
<td>Delivers some value sooner</td>
</tr>
<tr class="even">
<td>May require a long wait for first value</td>
<td>Builds capability progressively</td>
</tr>
<tr class="odd">
<td>Can avoid duplicated interim capability</td>
<td>May incur interim or replacement costs</td>
</tr>
<tr class="even">
<td>Greater exposure to program cancellation</td>
<td>More opportunities to learn and adapt</td>
</tr>
</tbody>
</table>
<aside class="notes">
<ul>
<li>The book calls the first style “greedy deployment,” assuming high-value elements are costly and slow to develop. Distinguish this architectural style from a generic greedy optimization algorithm.</li>
<li>Ask which strategy stakeholders can sustain through years of spending without operational benefit.</li>
<li>Incremental delivery can reduce programmatic risk and improve flexibility, but it can also require redundant or temporary capability.</li>
<li>The table gives tendencies under the chapter’s assumptions. If a high-value element is also quick and inexpensive, the apparent conflict may disappear.</li>
<li>A useful evaluation considers value delivery over time, not only the final system’s performance.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Box 16.4, p.&nbsp;399.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="connecting-a-graph-on-a-fixed-node-set" class="slide level2 smaller">
<h2>CONNECTING: a graph on a fixed node set</h2>
<p><span class="math display">\[G=(U,E),\qquad a_{ij}=1\ \text{when edge }i\to j\text{ exists}.\]</span></p>
<ul>
<li>One set of nodes, with decisions about connections.</li>
<li>The adjacency matrix is square.</li>
<li>An undirected graph has <span class="math inline">\(a_{ij}=a_{ji}\)</span>.</li>
<li>Self-connections require an explicit modeling choice.</li>
</ul>
<p>Nodes can represent systems, objects, processes, or facilities.</p>
<aside class="notes">
<ul>
<li>The book’s formal paragraph uses “vertices” for connections. Use the standard distinction: vertices or nodes are elements, and edges are connections.</li>
<li>Clarify whether an edge means a physical cable, a possible flow, or a logical dependency. Binary adjacency alone does not encode capacity, delay, or flow magnitude.</li>
<li>Examples include a power grid and a water network with fixed production/treatment locations. Choosing those locations would add further architectural decisions.</li>
<li>ASSIGNING has two distinct node sets and only links across the sets. CONNECTING starts with a single fixed set and permits whatever pairs the domain allows.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4, pp.&nbsp;399–401.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="connectivity-and-adjacency-matrices" class="slide level2 smaller">
<h2>Connectivity and adjacency matrices</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="assets/chapter16/fig16_13_connecting.png" class="quarto-figure quarto-figure-center" alt="Two undirected six-node networks with corresponding symmetric adjacency matrices." height="440"></p>
</figure>
</div>
<div class="side-caption">
<p>The matrices encode which pairs share a connection. Source: Crawley, Cameron &amp; Selva (2016), Fig. 16.13, p.&nbsp;400.</p>
</div>
<aside class="notes">
<ul>
<li>Ask students to find node 3’s neighbors in the left graph: nodes 1, 2, 4, and 5. The corresponding row has four ones.</li>
<li>Check symmetry and the zero diagonal. Each undirected edge occupies two matrix entries but is only one binary decision.</li>
<li>Both graphs have six fixed nodes; they differ in edges. These are general mathematical network representations, not system-behavior diagrams.</li>
<li>The count 32,768 is 2^15 for six labeled nodes, no self-loops, and at most one edge per pair.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Fig. 16.13, p.&nbsp;400.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="four-connectivity-counts" class="slide level2 smaller">
<h2>Four connectivity counts</h2>
<p>For <span class="math inline">\(m\)</span> labeled nodes and binary connections:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Self-connections</th>
<th style="text-align: right;">Directed</th>
<th style="text-align: right;">Undirected</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Allowed</td>
<td style="text-align: right;"><span class="math inline">\(2^{m^2}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(2^{m(m+1)/2}\)</span></td>
</tr>
<tr class="even">
<td>Prohibited</td>
<td style="text-align: right;"><span class="math inline">\(2^{m(m-1)}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(2^{m(m-1)/2}\)</span></td>
</tr>
</tbody>
</table>
<p>For 3 nodes without self-connections:</p>
<p><strong>64 directed graphs</strong>, <strong>8 undirected graphs</strong>.</p>
<aside class="notes">
<ul>
<li>Derive the exponents as the number of independent yes/no choices. Directed edges use ordered pairs; undirected edges use unordered pairs.</li>
<li>For undirected graphs with loops, count m(m−1)/2 ordinary edges plus m loops, giving m(m+1)/2.</li>
<li>These formulas allow the empty graph and disconnected graphs. A connected-network requirement reduces the count and needs another constraint.</li>
<li>Parallel links, weighted edges, identical unlabeled nodes, and multiple edge types would need a different counting argument.</li>
<li>Ask why squaring the node count is wrong for an undirected loop-free network.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Table 16.4, p.&nbsp;400.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="bus-and-star-topologies" class="slide level2 smaller">
<h2>Bus and star topologies</h2>
<div class="columns">
<div class="column" style="width:48%;">
<p><img data-src="assets/chapter16/fig16_14_bus.png" alt="Six elements sharing a common bus interface." height="350"></p>
</div><div class="column" style="width:48%;">
<p><img data-src="assets/chapter16/fig16_14_star.png" alt="A star network with element 4 as its hub." height="350"></p>
</div></div>
<p>A bus is a <strong>shared interface</strong>. A star has a <strong>central node</strong>.</p>
<div class="side-caption">
<p>Source: Crawley, Cameron &amp; Selva (2016), Fig. 16.14 and Box 16.5, pp.&nbsp;402–403.</p>
</div>
<aside class="notes">
<ul>
<li>Ask students to trace a message from element 1 to element 6. Which resource does every such transfer depend on?</li>
<li>In the star, element 4 is a node that can perform processing or act as a source or sink. The bus is a shared interface rather than an additional node in this illustration.</li>
<li>Ask how increasing traffic affects the shared resource. Both styles can encounter bottlenecks, but the flow-control mechanism matters.</li>
<li>These generic graphs depict network topology, not procedural relationships in an OPM model. An architecture model should still state the kind of flow and the roles of its objects and processes.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Fig. 16.14 and Box 16.5, pp.&nbsp;402–403.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ring-mesh-and-tree-topologies" class="slide level2 smaller">
<h2>Ring, mesh, and tree topologies</h2>
<div class="columns">
<div class="column" style="width:32%;">
<p><img data-src="assets/chapter16/fig16_14_ring.png" alt="Six elements connected in a closed ring." height="300"></p>
</div><div class="column" style="width:32%;">
<p><img data-src="assets/chapter16/fig16_14_mesh.png" alt="Six elements with multiple mesh connections." height="300"></p>
</div><div class="column" style="width:32%;">
<p><img data-src="assets/chapter16/fig16_14_tree.png" alt="A tree with a branching hierarchy." height="300"></p>
</div></div>
<p>Where are the <strong>alternative routes</strong>, <strong>bottlenecks</strong>, and <strong>failure dependencies</strong>?</p>
<div class="side-caption">
<p>Source: Crawley, Cameron &amp; Selva (2016), Fig. 16.14 and Box 16.5, pp.&nbsp;402–403.</p>
</div>
<aside class="notes">
<ul>
<li>Trace the closed circuit in the ring, alternative paths in the mesh, and branches in the tree. A mesh need not be a complete graph.</li>
<li>Ask students to remove one edge mentally and assess which flows remain possible. Avoid equating graph connectivity with the behavior of a particular forwarding protocol.</li>
<li>The commodity may be data, vehicles, power, water, gas, or food. Reliability, latency, throughput, and scalability depend on both topology and the flow and failure models.</li>
<li>Hybrid architectures combine styles across regions or levels. The following tables summarize the tradeoffs rather than declaring a universal winner.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Fig. 16.14 and Box 16.5, pp.&nbsp;401–403.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="bus-star-and-ring-tradeoffs" class="slide level2 smaller">
<h2>Bus, star, and ring tradeoffs</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Style</th>
<th>Potential advantage</th>
<th>Principal concern</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bus</td>
<td>Low interface cost, easy attachment</td>
<td>Shared bus failure or congestion</td>
</tr>
<tr class="even">
<td>Star</td>
<td>Simple hub coordination</td>
<td>Hub bottleneck and failure</td>
</tr>
<tr class="odd">
<td>Ring</td>
<td>Predictable access in suitable protocols</td>
<td>Dependence on the intact forwarding path</td>
</tr>
</tbody>
</table>
<p>A <strong>bus</strong> is a shared interface. A <strong>hub</strong> is a node that can process or relay flow.</p>
<aside class="notes">
<ul>
<li>The chapter cites launch-vehicle avionics for a bus, airline hub-and-spoke systems for a star, and token-ring networking for a ring. Present these as examples from the text rather than current universal practice.</li>
<li>Qualify the book’s statement that every ring node is a single point of failure. That applies to an unprotected forwarding ring; bypass, dual rings, routing, and protection alter failure behavior. An undirected cycle with one removed node can remain connected as a path.</li>
<li>Likewise, scalability is not unlimited when every flow shares one resource.</li>
<li>Ask whether adding a faster hub changes topology. It changes capability and cost while preserving the star’s structure.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Box 16.5, p.&nbsp;403.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="mesh-tree-and-hybrid-tradeoffs" class="slide level2 smaller">
<h2>Mesh, tree, and hybrid tradeoffs</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Style</th>
<th>Potential advantage</th>
<th>Principal concern</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mesh</td>
<td>Alternative routes, distributed cooperation</td>
<td>More links and routing complexity</td>
</tr>
<tr class="even">
<td>Tree</td>
<td>Clear hierarchy, maintainable expansion</td>
<td>Failure can disconnect descendants</td>
</tr>
<tr class="odd">
<td>Hybrid</td>
<td>Different structures for different needs</td>
<td>More interface and coordination choices</td>
</tr>
</tbody>
</table>
<p>Performance depends on <strong>where flow originates</strong>, <strong>where it goes</strong>, and <strong>how much it carries</strong>.</p>
<aside class="notes">
<ul>
<li>The chapter uses rural communication networks and peer-to-peer systems for mesh structures, and apartment-building distribution networks for trees.</li>
<li>A tree is connected and acyclic. Every edge is a bridge, so losing one can separate the graph; the system-level consequence depends on the traffic and available backup paths.</li>
<li>A mesh can improve fault tolerance, but not every sparse mesh survives every failure. Make the protection target explicit.</li>
<li>Ask students to propose a hybrid campus network and identify where resilience is most valuable. The point is to justify connections through stakeholder needs rather than select a fashionable topology.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4 and Box 16.5, pp.&nbsp;401–403.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="pattern-recognition-exercise" class="slide level2 smaller">
<h2>Pattern recognition exercise</h2>
<p>Choose a natural pattern and state one necessary assumption.</p>
<ol type="1">
<li>Select experiments within a mass limit.</li>
<li>Divide experiments into spacecraft without duplication.</li>
<li>Deploy instrument copies into named orbits.</li>
<li>Choose the order of four launches.</li>
<li>Select communication links among the spacecraft.</li>
<li>Choose one propulsion type for each spacecraft.</li>
</ol>
<aside class="notes">
<ul>
<li>Expected answers: DOWN-SELECTING, PARTITIONING, ASSIGNING, PERMUTING, CONNECTING, and DECISION-OPTION.</li>
<li>Ask what changes if experiments can fly twice. Pure partitioning no longer represents the intended space without changing what the elements mean.</li>
<li>Ask what changes if a launch can carry several spacecraft. A permutation of spacecraft alone no longer describes the full packaging/scheduling problem.</li>
<li>Accept an alternative encoding if students state the constraints and explain what structure is lost or gained. Pattern recognition should not become a vocabulary guessing game.</li>
<li>This is a useful pause before the discussion of overlapping formulations.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.4, pp.&nbsp;379–403; classroom exercise.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="formulating-a-large-problem" class="title-slide slide level1 center">
<h1>16.5 Formulating a large problem</h1>
<aside class="notes">
<p>Real architecture problems combine patterns. Decomposition can make analysis manageable, but coupling can invalidate independently optimized choices. Source: §16.5, pp.&nbsp;403–408.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="architecting-tasks-and-useful-patterns" class="slide level2 smaller">
<h2>Architecting tasks and useful patterns</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Task</th>
<th>Usually useful patterns</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Decompose form / function</td>
<td>PARTITIONING</td>
</tr>
<tr class="even">
<td>Map function to form</td>
<td>ASSIGNING, PARTITIONING</td>
</tr>
<tr class="odd">
<td>Specialize form / function</td>
<td>DECISION-OPTION, DOWN-SELECTING</td>
</tr>
<tr class="even">
<td>Characterize form / function</td>
<td>DECISION-OPTION</td>
</tr>
<tr class="odd">
<td>Connect form / function</td>
<td>ASSIGNING, PERMUTING, CONNECTING</td>
</tr>
<tr class="even">
<td>Define scope / select goals</td>
<td>DOWN-SELECTING</td>
</tr>
</tbody>
</table>
<aside class="notes">
<ul>
<li>This is the full mapping of Table 16.5 in a compact editable form. “Usually” matters: it is guidance, not a rule that excludes other encodings.</li>
<li>Revisit students’ campus-robot examples from the opening table. Ask whether their assumptions point toward a particular pattern.</li>
<li>In NEOSS, assigning instruments to named orbits permits missing or repeated types, while partitioning a selected set into spacecraft permits neither. A budget or deployment rule may make one formulation more natural.</li>
<li>The pattern should match the architect’s mental model and the intended alternatives.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Table 16.5 and §16.5, p.&nbsp;404.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="overlap-generic-encodings" class="slide level2 smaller">
<h2>Overlap: generic encodings</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Pattern</th>
<th>DECISION-OPTION representation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DOWN-SELECTING</td>
<td>One binary choice per candidate</td>
</tr>
<tr class="even">
<td>ASSIGNING</td>
<td>One binary choice per left-right pair</td>
</tr>
<tr class="odd">
<td>PARTITIONING</td>
<td>List partitions, or constrain group labels</td>
</tr>
<tr class="even">
<td>PERMUTING</td>
<td>List permutations, or enforce distinct positions</td>
</tr>
<tr class="odd">
<td>CONNECTING</td>
<td>One binary choice per allowable edge</td>
</tr>
</tbody>
</table>
<p>Representability does not guarantee a convenient search space.</p>
<aside class="notes">
<ul>
<li>This slide captures the DECISION-OPTION row of Table 16.6. Listing all 52 partitions of five instruments as one decision is possible, but conceals the grouping structure.</li>
<li>The printed ASSIGNING conversion uses an ambiguous N count. The explicit count is mn binary variables for m left and n right elements.</li>
<li>A constrained label representation of partitions also needs duplicate handling because many group-label vectors encode the same partition.</li>
<li>Ask which representation makes “move one instrument to another spacecraft” easy to express. The structured grouping representation usually does.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Table 16.6 and §16.5, pp.&nbsp;405–406.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="overlap-subset-and-graph-views" class="slide level2 smaller">
<h2>Overlap: subset and graph views</h2>
<ul>
<li>ASSIGNING can be a subset choice for each left element.</li>
<li>CONNECTING can select a subset of candidate edges.</li>
<li>PARTITIONING can select candidate groups, with exact coverage constraints.</li>
<li>PERMUTING can select element-position pairs, with one per element and position.</li>
<li>A decision-option graph needs links only to that decision’s valid options.</li>
</ul>
<aside class="notes">
<ul>
<li>These are the DOWN-SELECTING row and related graph conversions in Table 16.6.</li>
<li>For partitioning as group selection, require each element to occur in exactly one selected group. Otherwise a set of selected subsets may overlap or leave gaps.</li>
<li>For a decision-option bipartite graph, require exactly one selected edge out of each decision and forbid edges to another decision’s private options.</li>
<li>Ask why treating a permutation as arbitrary edge selection creates many invalid candidates. Most edge subsets violate the one-to-one requirements.</li>
<li>General-purpose encodings often trade conceptual simplicity for extra constraints.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Table 16.6 and §16.5, pp.&nbsp;405–406.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="overlap-groups-positions-and-networks" class="slide level2 smaller">
<h2>Overlap: groups, positions, and networks</h2>
<ul>
<li>PARTITIONING: assign to <strong>indistinguishable bins</strong>, exactly once per element.</li>
<li>PERMUTING: assign to <strong>distinct positions</strong>, exactly one per position.</li>
<li>ASSIGNING: connect two distinct node sets only across the sets.</li>
<li>PERMUTING: use a perfect matching between elements and positions.</li>
<li>PARTITIONING: recover groups from graph components, often with duplicates.</li>
</ul>
<aside class="notes">
<ul>
<li>This captures the remaining direct relationships in Table 16.6. Empty abstract bins can be ignored for partitioning, but bin labels must not create spurious alternatives.</li>
<li>Many graphs have the same connected components. For three elements all in one group, a path and a triangle recover the same partition, so graph encoding is many-to-one.</li>
<li>The table also discusses theoretical conversions between partitioning and permutation problems through complexity reductions. Those concern appropriately formulated optimization/decision problems with objectives and constraints; merely enumerating a permutation is not an NP-completeness claim.</li>
<li>The practical lesson is to preserve useful structure. The chapter’s broad interchangeability claim should not be read as a promise that every conversion is simple, compact, or equally efficient.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Table 16.6 and §16.5, pp.&nbsp;405–406.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="binary-encoding-requires-enough-bits" class="slide level2 smaller">
<h2>Binary encoding requires enough bits</h2>
<p>A decision with <span class="math inline">\(m\)</span> options needs</p>
<p><span class="math display">\[b=\lceil\log_2m\rceil\]</span></p>
<p>bits in a compact binary encoding.</p>
<p>For 3 options:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Bits</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>00 / 01 / 10</td>
<td>Options A / B / C</td>
</tr>
<tr class="even">
<td>11</td>
<td>Invalid code</td>
</tr>
</tbody>
</table>
<aside class="notes">
<ul>
<li>The ceiling is necessary. The book writes log2(m), which is not an integer for most option counts.</li>
<li>Ask whether treating the two bits as unconstrained selection decisions preserves the original choice set. It introduces the invalid 11 code.</li>
<li>A one-hot alternative would use three bits with an exactly-one constraint. It is less compact but gives another useful representation.</li>
<li>Compactness alone does not determine a good encoding: mutation, crossover, feasibility checks, and neighborhood meaning also matter.</li>
<li>When m is a power of two, every compact code can represent an option; other architectural constraints may still apply.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.5, p.&nbsp;406.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="neoss-subproblems-remain-coupled" class="slide level2 smaller">
<h2>NEOSS subproblems remain coupled</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="assets/chapter16/fig16_15_decomposition.png" class="quarto-figure quarto-figure-center" alt="Instrument selection, packaging, and mission scheduling linked by packaging factors, maturity, and data continuity." height="450"></p>
</figure>
</div>
<div class="side-caption">
<p>Different patterns organize different decisions, with feedback between them. Source: Crawley, Cameron &amp; Selva (2016), Fig. 16.15 and §16.5, pp.&nbsp;407–408.</p>
</div>
<aside class="notes">
<ul>
<li>Instrument selection maps naturally to DOWN-SELECTING; packaging to PARTITIONING or ASSIGNING; scheduling to PERMUTING plus any needed date decisions.</li>
<li>Follow the feedback links: spare bus or launch capacity can favor an opportunity payload; instrument maturity affects packaging and launch order; data continuity affects both selection and scheduling.</li>
<li>The chapter argues that instrument selection often drives the largest cost and performance changes, with packaging effects at a smaller but still important scale. Treat this as a case-specific assessment.</li>
<li>Ask why the best standalone instrument set might be awkward to package.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Fig. 16.15 and §16.5, pp.&nbsp;407–408.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="decomposition-and-global-quality" class="slide level2 smaller">
<h2>Decomposition and global quality</h2>
<ul>
<li>Separate subproblems that are as loosely coupled as possible.</li>
<li>Preserve links through shared constraints and evaluation.</li>
<li>Carry multiple promising alternatives across a boundary.</li>
<li>Revisit upstream choices when downstream results expose a conflict.</li>
</ul>
<p>Combining individually optimal subproblem solutions can produce a poor overall architecture.</p>
<aside class="notes">
<ul>
<li>A data-gap requirement can constrain instrument selection so the scheduling stage has an appropriate replacement mission to launch.</li>
<li>A packaging stage might reject an otherwise attractive set because of wasted bus capacity, interference, or an immature instrument that delays all others.</li>
<li>Carrying alternatives and iterating are practical classroom extensions of the chapter’s explicit coupling constraints. They reduce premature commitment but do not prove a global optimum.</li>
<li>Ask students to identify the metric and interface data exchanged between two teams. “We will coordinate” is insufficient unless they say what information changes the decisions.</li>
<li>The goal is manageable analysis with honest limits on the result.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.5, pp.&nbsp;404, 407–408.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="solving-the-optimization-problem" class="title-slide slide level1 center">
<h1>16.6 Solving the optimization problem</h1>
<aside class="notes">
<p>Start with the simplest method that fits the computational budget. Search algorithms do not remove the need for valid encodings and credible evaluators. Source: §16.6, pp.&nbsp;408–416.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="full-factorial-enumeration" class="slide level2 smaller">
<h2>Full-factorial enumeration</h2>
<ol type="1">
<li>Generate every candidate combination.</li>
<li>Reject invalid architectures and duplicate encodings.</li>
<li>Evaluate every remaining architecture.</li>
<li>Retain metrics and explanations.</li>
<li>Apply Pareto analysis and stakeholder preferences.</li>
</ol>
<p>Enumeration gives both the frontier and the surrounding tradespace.</p>
<aside class="notes">
<ul>
<li>This builds on the chapter’s nested-loop approach and Chapter 15’s argument for retaining dominated regions to learn about structure.</li>
<li>Distinguish a raw Cartesian product from the feasible set. The book’s Fig. 16.16 shows generation but omits the constraint filter in that snippet; include it in an actual workflow.</li>
<li>Exhaustive evaluation identifies the true Pareto set for the finite model if evaluation and filtering are correct. It does not validate the physical model itself.</li>
<li>Ask what evidence is lost if the tool stores only its final best point. Clusters, sensitivities, alternative families, and explanations can disappear.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.6, pp.&nbsp;408–409; Fig. 16.16.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="enumeration-algorithm" class="slide level2 smaller">
<h2>Enumeration algorithm</h2>
<pre style="font-size: 0.75em; line-height: 1.35;">results = []
for A in CartesianProduct(option_sets):
    if not hard_constraints_hold(A):
        continue
    A = canonicalize(A)
    if already_evaluated(A):
        continue
    metrics, explanation = evaluate(A)
    results.append(A, metrics, explanation)
front = nondominated_architectures(results)
</pre>
<aside class="notes">
<ul>
<li>This pseudocode generalizes Apollo’s nine nested loops. Canonicalization and duplicate checking are explicit classroom additions motivated by the balloon and partition examples.</li>
<li>The evaluation must apply any soft-constraint penalties consistently, and the Pareto routine must know each metric’s direction.</li>
<li>Ask where a partition generator would fit. Either generate valid partitions directly or preprocess a list of partition options; naïvely looping over arbitrary labels needs constraints and duplicate handling.</li>
<li>Procedural languages specify steps. Declarative/rule-based approaches specify relationships and goals and use an inference mechanism to generate candidates; Appendix C develops that alternative.</li>
<li>Do not run a costly physical simulation on a combination already known to be invalid.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.6, pp.&nbsp;408–409; adapted from Fig. 16.16.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-computational-budget" class="slide level2 smaller">
<h2>The computational budget</h2>
<p>Approximate serial evaluation time:</p>
<p><span class="math display">\[T\approx N_{\mathrm{evaluated}}\,t_{\mathrm{eval}}.\]</span></p>
<p><strong>Classroom example:</strong> <span class="math inline">\(2^{20}=1{,}048{,}576\)</span> candidates.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Time per evaluation</th>
<th style="text-align: right;">Total serial time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1 millisecond</td>
<td style="text-align: right;">17.5 minutes</td>
</tr>
<tr class="even">
<td>1 second</td>
<td style="text-align: right;">12.1 days</td>
</tr>
<tr class="odd">
<td>1 minute</td>
<td style="text-align: right;">2.0 years</td>
</tr>
</tbody>
</table>
<p>Broader coverage competes with deeper modeling.</p>
<aside class="notes">
<ul>
<li>These estimates neglect generation, constraint checking, communication, and storage overhead. Parallelism can help, but speedup is limited by available resources and serial work.</li>
<li>Ask students to decide whether more fidelity is worthwhile before seeing the evaluation budget. A detailed model that evaluates only two arbitrary candidates may be less useful at this stage.</li>
<li>A staged approach can use a simpler model to find families and detailed models to scrutinize survivors, provided screening assumptions are checked.</li>
<li>“Small enough” depends on candidate count, evaluation time, hardware, and tolerable elapsed time, not an immutable number of decisions.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.6, p.&nbsp;408; classroom calculation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="heuristic-search-for-large-spaces" class="slide level2 smaller">
<h2>Heuristic search for large spaces</h2>
<ul>
<li>Generate promising candidates without visiting every combination.</li>
<li>Use evaluated results to guide subsequent search.</li>
<li>Seek several good architectural families.</li>
<li>Treat the returned front as an <strong>approximation</strong> unless completeness is established.</li>
</ul>
<p>Flexible heuristics suit categorical, nonlinear, and nonsmooth models.</p>
<aside class="notes">
<ul>
<li>The chapter favors metaheuristics because they require relatively little problem structure. This is a pragmatic choice, not a claim that they outperform every exact or specialized algorithm.</li>
<li>Branch-and-bound, cutting planes, network methods, and dynamic programming can be useful when their mathematical assumptions fit. Standard gradients are unsuitable for arbitrary category labels.</li>
<li>A run that stops improving may have converged locally or simply exhausted its search budget.</li>
<li>Ask students what would justify saying “globally optimal.” Exhaustive coverage, a valid optimality bound, or another mathematical certificate would be needed, not just a long run.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.6, pp.&nbsp;409–410; reference [27].</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="generator-evaluator-and-search-agent" class="slide level2 smaller">
<h2>Generator, evaluator, and search agent</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="assets/chapter16/fig16_17_search.png" class="quarto-figure quarto-figure-center" alt="Architecture generator and evaluator coordinated by a search algorithm receiving metrics and explanations." height="440"></p>
</figure>
</div>
<div class="side-caption">
<p>Search directions connect candidate generation to evaluation feedback. Source: Crawley, Cameron &amp; Selva (2016), Fig. 16.17, p.&nbsp;410.</p>
</div>
<aside class="notes">
<ul>
<li>Trace one cycle: generate an architecture, evaluate it using stakeholder requirements, then use metrics and explanations to choose another region or change.</li>
<li>With full enumeration, generation and final filtering can be separate. With heuristic search, generating candidates and selecting survivors become intertwined.</li>
<li>The evaluator’s explanation can show why a design failed or which requirement created a penalty. That information is useful to the human architect even if the search operator uses only numbers.</li>
<li>Ask which box contains stakeholder judgments and which box proposes new decision vectors.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Fig. 16.17, p.&nbsp;410.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-population-based-search-cycle" class="slide level2 smaller">
<h2>A population-based search cycle</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="assets/chapter16/fig16_18_population.png" class="quarto-figure quarto-figure-center" alt="Initial population, evaluation, termination check, selection, generation, and final preferred architectures." height="480"></p>
</figure>
</div>
<div class="side-caption">
<p>A population carries multiple alternatives through successive generations. Source: Crawley, Cameron &amp; Selva (2016), Fig. 16.18, p.&nbsp;411.</p>
</div>
<aside class="notes">
<ul>
<li>Walk through all six numbered steps. Initial generation precedes evaluation; each iteration tests termination, selects parents or survivors, and creates the next candidates.</li>
<li>Evaluation rules define performance. Selection rules decide which architectures contribute. Search rules decide how new candidates are constructed.</li>
<li>Populations are useful when the goal is several Pareto families instead of one best scalar solution.</li>
<li>The termination branch should not be interpreted as proof that the mathematical frontier was found. It may simply represent a budget limit.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Fig. 16.18, p.&nbsp;411.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="selection-diversity-and-stopping" class="slide level2 smaller">
<h2>Selection, diversity, and stopping</h2>
<ul>
<li>Preserve high-quality candidates through elitism.</li>
<li>Retain diversity across the tradeoffs and architecture families.</li>
<li>Generate new candidates through search operators.</li>
<li>Stop at a stated time, evaluation, generation, or improvement limit.</li>
<li>Compare final candidates with baselines and further analysis.</li>
</ul>
<aside class="notes">
<ul>
<li>Pareto rank is useful in multiobjective selection, but rank alone may let the population crowd into one narrow region.</li>
<li>Some dominated candidates can contribute diversity and lead to useful new combinations. Selection is not identical to immediately discarding every dominated point forever.</li>
<li>Elitism means retaining high-quality solutions across generations; selecting only current Pareto points as parents is one possible rule, not the entire definition.</li>
<li>Ask what happens if every individual becomes the same architecture. Crossover alone then offers little novelty.</li>
<li>Final preference selection remains a stakeholder decision informed by the search results.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.6, pp.&nbsp;411–412, 414–415.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="generating-feasible-initial-populations" class="slide level2 smaller">
<h2>Generating feasible initial populations</h2>
<ul>
<li>Randomly choose valid decision options or binary values.</li>
<li>Reject infeasible samples when rejection is inexpensive.</li>
<li>For tight constraints, generate feasible candidates directly.</li>
<li>Alternatively, repair an infeasible candidate.</li>
<li>Check whether sampling or repair favors particular regions.</li>
</ul>
<aside class="notes">
<ul>
<li>For an unconstrained DECISION-OPTION problem, sample one option per decision. For a subset problem, sample a binary vector.</li>
<li>Rejection sampling can become ineffective when feasible candidates occupy a tiny fraction of the raw space. Record the acceptance rate rather than assuming randomness is sufficient.</li>
<li>Repair requires a definition of a nearby feasible architecture. It can introduce systematic bias, for example always deleting the most recently added instrument.</li>
<li>Ask students how to sample a permutation directly. Shuffle the element list rather than sample positions independently and hope there are no repeats.</li>
<li>Feasible-by-construction generation still needs the additional domain constraints checked.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.6, p.&nbsp;412.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="uniform-sampling-can-miss-useful-styles" class="slide level2 smaller">
<h2>Uniform sampling can miss useful styles</h2>
<p>For 10 elements, <span class="math inline">\(B_{10}=115{,}975\)</span> partitions.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Number of groups</th>
<th style="text-align: right;">Number of partitions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td style="text-align: right;">511</td>
</tr>
<tr class="even">
<td>4</td>
<td style="text-align: right;">34,105</td>
</tr>
<tr class="odd">
<td>5</td>
<td style="text-align: right;">42,525</td>
</tr>
<tr class="even">
<td>6</td>
<td style="text-align: right;">22,827</td>
</tr>
</tbody>
</table>
<p>About <strong>85.8%</strong> have 4–6 groups. Uniform over partitions is not uniform over group counts.</p>
<aside class="notes">
<ul>
<li>The counts are Stirling numbers of the second kind. The fraction is (34,105+42,525+22,827)/115,975=0.85757.</li>
<li>The book reports 88% and more than 45,000 five-group partitions; those figures are inaccurate. Use the exact counts here.</li>
<li>If two- or three-spacecraft architectures seem promising, deliberately include them or sample the group count first and then a partition conditional on that count.</li>
<li>Explain that this intentional bias changes the sampling distribution. It can improve search coverage of a region of interest, but should not be mistaken for an unbiased statistical estimate of the entire tradespace.</li>
<li>Ask whether uniformly generating arbitrary group labels would be uniform over partitions. In general, it would not.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.6, p.&nbsp;412; counts computed from Stirling numbers.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-mixed-initial-population" class="slide level2 smaller">
<h2>A mixed initial population</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Source of candidates</th>
<th>Why include it?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Baselines and architectures of interest</td>
<td>Compare with known proposals</td>
</tr>
<tr class="even">
<td>Extreme styles</td>
<td>Test boundaries of the architecture space</td>
</tr>
<tr class="odd">
<td>Structured experimental designs</td>
<td>Cover selected combinations systematically</td>
</tr>
<tr class="even">
<td>Carefully sampled random candidates</td>
<td>Explore less anticipated regions</td>
</tr>
</tbody>
</table>
<p>Check feasibility for every source.</p>
<aside class="notes">
<ul>
<li>For PARTITIONING, include the monolithic and fully distributed extremes. For ASSIGNING, include channelized and fully cross-strapped examples where feasible.</li>
<li>A deterministic design does not automatically contain every architectural extreme. Include important extremes explicitly.</li>
<li>A Latin hypercube stratifies each sampled dimension; an orthogonal array balances combinations to a specified strength. Neither should be described as universally testing every full combination.</li>
<li>Ask why an initial population consisting only of the current baseline and small mutations might overlook an entirely different architecture family.</li>
<li>Preserve provenance so an architect can see whether an attractive result came from the baseline, a style extreme, or search.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.6, pp.&nbsp;412–413.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="an-orthogonal-array-example" class="slide level2 smaller">
<h2>An orthogonal-array example</h2>
<p>For three binary decisions, choose four of the eight vectors:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Sample</th>
<th style="text-align: right;">Decision 1</th>
<th style="text-align: right;">Decision 2</th>
<th style="text-align: right;">Decision 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>B</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td>C</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td>D</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
<p>Every <strong>pair of columns</strong> contains 00, 01, 10, and 11 exactly once.</p>
<aside class="notes">
<ul>
<li>Have students check columns 1 and 3, then columns 2 and 3. This is pairwise coverage, not all eight triples.</li>
<li>Orthogonal here refers to combinatorial balance, not zero dot products of these binary vectors.</li>
<li>The chapter also gives L_9(3^4): nine runs for four three-level decisions, compared with 3^4=81 full-factorial cases. The run count is not generally less than the number of decisions; the text’s P&lt;N statement is a typo.</li>
<li>Coverage alone does not isolate arbitrary higher-order interactions or guarantee inclusion of the best architecture.</li>
<li>Such designs can initialize a search or select tests when full-factorial testing is too expensive.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.6, p.&nbsp;413.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="exploration-and-exploitation" class="slide level2 smaller">
<h2>Exploration and exploitation</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Exploration</th>
<th>Exploitation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Discover new regions</td>
<td>Improve within a promising region</td>
</tr>
<tr class="even">
<td>Preserve diverse possibilities</td>
<td>Investigate useful local changes</td>
</tr>
<tr class="odd">
<td>Reduces premature convergence</td>
<td>Improves candidate quality</td>
</tr>
</tbody>
</table>
<p>Too little exploration can trap a search. Too little exploitation can leave promising candidates underdeveloped.</p>
<aside class="notes">
<ul>
<li>Use a landscape analogy cautiously because categorical spaces do not have a unique geometric distance. The encoding and move operator define what “nearby” means.</li>
<li>The chapter mentions genetic algorithms, particle swarm, ant colony, bees, and harmony search as families that balance these aims. It focuses on genetic operators and local search rather than surveying all algorithms.</li>
<li>Ask whether mutation always explores far away. A one-bit mutation may be quite local; an operator’s effect depends on the problem.</li>
<li>A practical search strategy may combine mechanisms instead of expecting one heuristic to serve every purpose.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.6, p.&nbsp;413.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="crossover-combines-parent-decisions" class="slide level2 smaller">
<h2>Crossover combines parent decisions</h2>
<p><strong>Classroom example:</strong> cut after the third decision.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Architecture</th>
<th>Prefix</th>
<th>Suffix</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Parent 1</td>
<td><code>1 1 0</code></td>
<td><code>0 1 0</code></td>
</tr>
<tr class="even">
<td>Parent 2</td>
<td><code>0 0 1</code></td>
<td><code>1 0 1</code></td>
</tr>
<tr class="odd">
<td>Child 1</td>
<td><code>1 1 0</code></td>
<td><code>1 0 1</code></td>
</tr>
<tr class="even">
<td>Child 2</td>
<td><code>0 0 1</code></td>
<td><code>0 1 0</code></td>
</tr>
</tbody>
</table>
<p>Single-point, multi-point, and uniform crossover exchange different portions of the encoding.</p>
<aside class="notes">
<ul>
<li>Relate this explicit binary example to the single-point exchange in Fig. 16.19. The children inherit prefixes and suffixes from different parents.</li>
<li>Ask whether two feasible parents guarantee feasible children. A shared budget or incompatible option pair can make a child invalid.</li>
<li>Single-point crossover tends to preserve contiguous fragments. The ordering of decisions therefore matters when useful interactions span particular positions.</li>
<li>In uniform crossover, choose the contributing parent at each decision position. It is decisions or genes that are exchanged within an architecture chromosome.</li>
<li>Genetic algorithms use fitness or multiobjective selection to bias which parents contribute, not knowledge that each inherited fragment must be good.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.6 and Fig. 16.19, p.&nbsp;414; classroom encoding.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="schemata-represent-architecture-families" class="slide level2 smaller">
<h2>Schemata represent architecture families</h2>
<p>A schema uses 0, 1, and <span class="math inline">\(*\)</span> (“either value”).</p>
<p><code>[1,*,*,0]</code> describes <strong>four</strong> binary architectures.</p>
<p>For a length-<span class="math inline">\(n\)</span> schema with <span class="math inline">\(k\)</span> fixed positions:</p>
<p><span class="math display">\[\text{number of matching architectures}=2^{n-k}.\]</span></p>
<p>One complete binary architecture matches <span class="math inline">\(2^n\)</span> schemata.</p>
<aside class="notes">
<ul>
<li>List [1,0,0,0], [1,0,1,0], [1,1,0,0], and [1,1,1,0]. Two free bits give four instances.</li>
<li>To see the second count, choose independently whether each position in a complete architecture remains fixed or becomes a wildcard.</li>
<li>In the book, a schema with instrument 2 present and instrument 5 absent identifies a family whose value can be estimated by average fitness over matching candidates.</li>
<li>A promising schema has above-average fitness in the comparison population. That estimate depends on sampling and the other decisions, so it is not a context-free guarantee.</li>
<li>Selection can amplify useful schemata, while crossover preserves some and disrupts others. This explains a mechanism, not a proof of global convergence.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.6, pp.&nbsp;414–415.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="mutation-and-valid-neighborhoods" class="slide level2 smaller">
<h2>Mutation and valid neighborhoods</h2>
<ul>
<li>Mutation makes a small random change.</li>
<li>Local search examines neighboring architectures for improvement.</li>
<li>A subset neighbor may flip one inclusion bit.</li>
<li>A permutation neighbor may swap two positions.</li>
<li>A partition neighbor may move one element between groups.</li>
</ul>
<p>Operators should respect the encoding’s meaning and constraints.</p>
<aside class="notes">
<ul>
<li>The chapter presents mutation as a way to reduce trapping in a suboptimal region. The pattern-specific moves here are classroom examples of implementing that principle.</li>
<li>Naïve single-point crossover on [1,2,3,4] and [3,4,1,2] at the midpoint produces [1,2,1,2], which is not a permutation. Use a permutation-preserving operator or a justified repair.</li>
<li>Moving an element out of a singleton partition removes the now-empty group. Canonicalize labels afterward.</li>
<li>Local search can become stuck if reaching a better architecture requires temporarily accepting a worse one.</li>
<li>Ask which operation changes system scope versus only rearranging an existing scope.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.6, pp.&nbsp;413–415; pattern-aware classroom examples.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="additional-heuristics-and-expert-knowledge" class="slide level2 smaller">
<h2>Additional heuristics and expert knowledge</h2>
<ul>
<li><strong>Tabu-style memory:</strong> discourage cycling through recently visited moves or configurations.</li>
<li><strong>Domain knowledge:</strong> try combinations known to have useful interactions.</li>
<li><strong>NEOSS example:</strong> colocate altimeter and radiometer when the mission permits their synergy.</li>
<li>Retain exploration beyond the expert’s favored region.</li>
</ul>
<aside class="notes">
<ul>
<li>The chapter simplifies Tabu Search to a list of bad schemata. Teach the broader memory idea carefully: tabu status is a temporary search restriction, not a statement that a design is physically infeasible or permanently bad.</li>
<li>A domain rule can help discover useful packaging far faster than blind random changes, but it must respect orbit, resource, maturity, and data-continuity constraints.</li>
<li>Ask what happens if expert knowledge is outdated or omits a new technology. An overly rigid rule can exclude the best family.</li>
<li>Keep hard constraints separate from heuristic preferences. A useful tendency should not silently become an absolute prohibition.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.6, p.&nbsp;415; reference [34].</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-portfolio-of-search-heuristics" class="slide level2 smaller">
<h2>A portfolio of search heuristics</h2>
<ul>
<li>Combine general and domain-specific operators.</li>
<li>Measure which operators produce useful candidates.</li>
<li>Allocate more effort to effective operators.</li>
<li>Preserve enough exploration to detect changing opportunities.</li>
<li>Account for evaluation cost as well as improvement.</li>
</ul>
<aside class="notes">
<ul>
<li>The chapter warns about dilution: adding weak heuristics can reduce the impact of good ones if effort is divided indiscriminately.</li>
<li>Hyperheuristics adapt the choice of heuristics. Machine-learning approaches can support this extra layer, but are beyond the chapter’s introductory treatment.</li>
<li>Ask what “effective” means in a multiobjective search. Possibilities include new non-dominated candidates, better coverage, or improved quality per evaluation; one scalar score may hide tradeoffs.</li>
<li>An operator that succeeds early may become less useful later. Monitoring should not assume performance is fixed.</li>
<li>More algorithmic complexity should earn its place through evidence on the problem at hand.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.6, pp.&nbsp;415–416.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="choosing-and-reporting-a-search-strategy" class="slide level2 smaller">
<h2>Choosing and reporting a search strategy</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Situation</th>
<th>Reasonable starting point</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Small feasible space</td>
<td>Full enumeration</td>
</tr>
<tr class="even">
<td>Strong exploitable mathematical structure</td>
<td>A suitable specialized method</td>
</tr>
<tr class="odd">
<td>Large, irregular architecture model</td>
<td>Population-based heuristic search</td>
</tr>
</tbody>
</table>
<p>Report the model, constraints, evaluation budget, baselines, and the limits of the resulting frontier.</p>
<aside class="notes">
<ul>
<li>Ask students to separate model uncertainty from incomplete search. Repeating a search can reveal variability in found candidates, but cannot correct a biased cost model.</li>
<li>Compare small versions against exhaustive enumeration when practical, and compare full runs with known baselines and style extremes.</li>
<li>Treat reproducible random seeds, repeated runs, and sensitivity to assumptions as practical evaluation habits. They are useful checks, not certificates of optimality.</li>
<li>The chapter’s message is to use enumeration when feasible and flexible heuristics when needed, while retaining architecture judgment throughout.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.6 and §16.7, pp.&nbsp;408–416; classroom synthesis.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="synthesis-and-application" class="title-slide slide level1 center">
<h1>16.7 Synthesis and application</h1>
<aside class="notes">
<p>Return to the full architecture task: a faithful representation, credible evaluation, manageable search, and reasoned interpretation. Source: §16.7, p.&nbsp;416.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-compact-neoss-formulation-exercise" class="slide level2 smaller">
<h2>A compact NEOSS formulation exercise</h2>
<p>For a simplified program:</p>
<ul>
<li>Choose among four instruments.</li>
<li>Partition selected instruments into spacecraft.</li>
<li>Assign each spacecraft one of three allowed orbit options.</li>
<li>Order the spacecraft launches.</li>
</ul>
<p>Define <strong>two metrics</strong>, <strong>two hard constraints</strong>, and <strong>one coupling</strong> that a staged solution must retain.</p>
<aside class="notes">
<ul>
<li>Give pairs five minutes. Expected patterns: DOWN-SELECTING, PARTITIONING, DECISION-OPTION for each spacecraft’s orbit, and PERMUTING for launch order.</li>
<li>Possible metrics: scientific requirement satisfaction and lifecycle cost. Possible constraints: spacecraft power capacity and an instrument-orbit incompatibility. A continuity requirement can couple instrument selection with launch timing.</li>
<li>The orbit step here requires exactly one named orbit option per spacecraft, so its simple decision-option encoding is intentional. A more general multiple-copy orbit allocation would use ASSIGNING.</li>
<li>Ask students whether launch order alone verifies a no-gap condition. Actual dates or a model that derives dates are needed.</li>
<li>Do not reward a long list of variables unless each has a dictionary, interpretation, and role in evaluation.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §§16.2–16.6, pp.&nbsp;375–416; classroom exercise.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="counting-the-compact-neoss-space" class="slide level2 smaller">
<h2>Counting the compact NEOSS space</h2>
<p><strong>Classroom assumptions:</strong> no duplicated instruments, no extra constraints.</p>
<p>For a selected set of size <span class="math inline">\(s\)</span>, partition it into <span class="math inline">\(k\)</span> spacecraft, choose one of 3 orbits for each, and order the launches:</p>
<p><span class="math display">\[N=\sum_{s=1}^{4}\binom{4}{s}\sum_{k=1}^{s}S(s,k)\,3^k\,k!=4{,}059.\]</span></p>
<p>The empty program adds <strong>one</strong> more architecture if it is allowed.</p>
<aside class="notes">
<ul>
<li>Break the product into choices: choose the subset, choose an unlabeled partition, assign an orbit to each resulting instrument group, and permute those groups into launch order.</li>
<li>Contributions by selected-set size are 12, 126, 876, and 3,045, totaling 4,059. For one selected instrument there are four choices times three orbits.</li>
<li>Each group is identifiable by its instrument membership, so assigning orbit options and launch positions does not reintroduce arbitrary bin-label duplicates.</li>
<li>This count does not represent the full NEOSS program in the book. It omits dates, constellation details, copies, and constraints by construction.</li>
<li>Use as an optional challenge. The learning goal is a correct factorization, not memorizing Stirling numbers.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §§16.4–16.6; derived classroom example.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="chapter-16-takeaways" class="slide level2 smaller">
<h2>Chapter 16 takeaways</h2>
<ul>
<li>A decision model links architecture choices to stakeholder metrics.</li>
<li>Six patterns expose useful structure and architectural styles.</li>
<li>Encodings must preserve meaning, feasibility, and distinct alternatives.</li>
<li>Decomposition requires explicit attention to coupling.</li>
<li>Enumeration gives complete model coverage when affordable.</li>
<li>Heuristics provide useful candidates with limits that must remain visible.</li>
</ul>
<aside class="notes">
<ul>
<li>Reconnect the final three chapters: Chapter 14 represents and evaluates decisions; Chapter 15 reasons about the tradespace; Chapter 16 formulates recurring structures and searches them.</li>
<li>Ask students which step requires the most human judgment. There is no single correct stage: scope, metrics, assumptions, constraints, decomposition, and interpretation all do.</li>
<li>Optimization supports architecture rather than replacing stakeholder analysis, concept generation, or detailed engineering.</li>
<li>Invite a student to explain one pattern using an example outside aerospace to test transfer of understanding.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.7, p.&nbsp;416.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="exit-ticket" class="slide level2 smaller">
<h2>Exit ticket</h2>
<ol type="1">
<li>Why is assigning to named orbits different from partitioning into spacecraft?</li>
<li>Why can two encodings represent the same architecture?</li>
<li>When can a locally attractive subsystem harm the full system?</li>
<li>What does a heuristic Pareto front establish, and what does it leave uncertain?</li>
</ol>
<aside class="notes">
<ul>
<li>Expected answer 1: general assignment permits omissions and multiple copies and uses named destinations; partitioning is exhaustive, disjoint grouping into unlabeled subsets.</li>
<li>Expected answer 2: irrelevant values at an empty balloon site, or different labels for identical partition groups, do not change the physical architecture.</li>
<li>Expected answer 3: shared resources, incompatible packaging, delayed maturity, or data-continuity gaps can offset local value.</li>
<li>Expected answer 4: the returned candidates are non-dominated among those found under the stated model; unvisited candidates may dominate them, and the model itself may be inaccurate.</li>
<li>Use the answers to identify whether students need another exercise in representation, coupling, or search interpretation.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), §16.7, p.&nbsp;416; classroom assessment.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="reading-and-further-study" class="slide level2 smaller">
<h2>Reading and further study</h2>
<p><strong>Crawley, Cameron &amp; Selva, <em>System Architecture</em> (2016)</strong></p>
<ul>
<li>Chapter 16, §§16.1–16.7, pp.&nbsp;<strong>373–416</strong>.</li>
<li>Chapter references, pp.&nbsp;<strong>416–419</strong>.</li>
<li>Appendix C: rule-based representation, generation, and evaluation.</li>
<li>Appendix D: related computational methods and classical problems.</li>
</ul>
<p>Revisit Chapters 14–15 for the Apollo, GNC, and Pareto examples.</p>
<aside class="notes">
<ul>
<li>The lecture follows the supplied edition. All reproduced source figures carry their figure and page references; numerical classroom examples are labeled as such.</li>
<li>Further-reading routes within the chapter include Alexander and software design patterns, Suh’s functional independence, Bell and Stirling numbers, Holland’s genetic algorithms, and multiobjective methods such as NSGA-II.</li>
<li>Students do not need to read every research citation before using the six patterns. Assign the chapter and choose a targeted reference for deeper work.</li>
<li>Suggested follow-up: formulate a small architecture problem, enumerate it, then compare a limited heuristic search with the exact finite-model frontier.</li>
</ul>
<p><strong>Source:</strong> Crawley, Cameron &amp; Selva (2016), Chapter 16 and references, pp.&nbsp;373–419.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="../../../images/monogram_solid-blk.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="../../../teaching/ug_courses/systems_architecture/index.html">← Course Home</a> · Systems Architecture · Chapter 16</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/Symplectomorphism\.github\.io\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>