---
title: "Polygon diagonals"
description: "How many of them are there?"
author: "Aykut C. Satici"
date: "2026-04-01"
categories: [geometry]
layout: article
crossref:
  exr-title: "Problem"
  exr-prefix: "Problem"
  prp-title: "Answer"
---



::: {#exr-polygon-diagonals}
## Polygon diagonals
Suppose the function $f: \mathbb{N} \to \mathbb{N}$ denotes the number of 
distinct diagonals that can be drawn in a regular $n$-gon. For example, 
$$
f(3) = 0, \quad f(4) = 2, \quad f(5) = 5.
$$
Determine the value of $f(9) - f(7)$.
:::

::: {#prp-polygon-diagonals}
Order the vertices in a counterclockwise manner and take the vertex $v_1$ of an
$n$-gon. A diagonal from this vertex connects $v_1$ to some other vertex $v_j$
such that $j \neq 1, 2, n$. Hence, there are only $m = n-3$ diagonals emanating
from the first vertex.  Similarly, from the second vertex $v_2$, one can draw
diagonals to all other vertices except $v_1, v_2, v_3$. 

However, once we reach $v_3$, the diagonal connecting $v_3$ to $v_1$ has already
been counted as a diagonal emanating from $v_1$ so in addition to not being able 
to draw diagonals to $v_2, v_3$, and $v_4$, we also cannot draw a diagonal to $v_1$.
This pattern continues for all subsequent vertices; that is, for $v_4$, we cannot 
draw diagonals to not three, not four, but $5$ vertices. 

In other words, after two vertices have been selected, we can draw diagonals to 
only $m-1, m-2, \ldots, 1$ vertices until we exhaust all the vertices. 

Hence, the total number of diagonals for an $n$-gon is given by
$$ 
f(n) = 2(n-3) + \frac{(n-3-1)(n-3)}{2} = \frac{1}{2}n(n-3).
$$

Therefore, we have 
$f(9) - f(7) = \frac{1}{2}(9)(6) - \frac{1}{2}(7)(4) = 27 -14 = \boxed{13}$.

:::

{{< include _back.qmd >}}