<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aykut C. Satici">

<title>Where Does the Torque Gain Converge? – Aykut C. Satici</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/robot-arm-favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-09b469177ad55450d94bd915a4dae986.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
window.MathJax = {
  loader: {
    load: ['[tex]/boldsymbol', '[tex]/mathtools']
  },
  tex: {
    packages: {'[+]': ['boldsymbol', 'mathtools']}
  }
};
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="../../assets/mathjax/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
<link rel="stylesheet" href="../research.css">
<meta property="og:title" content="Where Does the Torque Gain Converge? – Aykut C. Satici">
<meta property="og:description" content="Aykut C. Satici, Associate Professor of Systems Engineering at UT Dallas. Robotics, nonlinear control, and machine learning.">
<meta property="og:image" content="https://Symplectomorphism.github.io/research/wind-esc/assets/q1-anomaly.svg">
<meta property="og:site_name" content="Aykut C. Satici">
<meta property="og:image:alt" content="Left, converged torque gain against design for six LES conditions, every bar negative, from half a percent to eight percent low. Right, converged tip-speed ratio for the same six, every point above the design value of 7.5, reaching 7.85.">
</head>

<body class="nav-sidebar nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Aykut C. Satici</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../research/index.html"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../publications.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../teaching/index.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../people/index.html"> 
<span class="menu-text">People</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../news/index.html"> 
<span class="menu-text">News</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../positions/index.html"> 
<span class="menu-text">Opportunities</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-miscellaneous" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Miscellaneous</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-miscellaneous">    
        <li>
    <a class="dropdown-item" href="../../fun/index.html">
 <span class="dropdown-text">Fun</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../chiasson/index.html">
 <span class="dropdown-text">John Chiasson</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    <div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="q1-estimand.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></div>
<!-- main -->
<main class="content" id="quarto-document-content">
<div style="visibility: hidden; position: absolute; top: 0; left: 0; width: 0; height: 0; overflow: hidden;">
$$
% Define your custom commands here
\newcommand{\bmat}[1]{\begin{bmatrix}#1\end{bmatrix}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\P}{\mathbb{P}}
\newcommand{\S}{\mathbb{S}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\S}{\mathbb{S}}
\newcommand{\norm}[2]{\|{#1}\|_{{}_{#2}}}
\newcommand{\pd}[2]{\frac{\partial #1}{\partial #2}}
\newcommand{\pdd}[2]{\frac{\partial^2 #1}{\partial #2^2}}
\newcommand{\vectornorm}[1]{\left|\left|#1\right|\right|}
\newcommand{\abs}[1]{\left|{#1}\right|}
\newcommand{\mbf}[1]{\mathbf{#1}}
\newcommand{\mc}[1]{\mathcal{#1}}
\newcommand{\bm}[1]{\boldsymbol{#1}}
\newcommand{\nicefrac}[2]{{}^{#1}\!/_{\!#2}}
\newcommand{\argmin}{\operatorname*{arg\,min}}
\newcommand{\argmax}{\operatorname*{arg\,max}}
\newcommand{\dd}{\operatorname{d}\!}
$$
</div>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Where Does the Torque Gain Converge?</h1>
<p class="subtitle lead">Every published run lands a few percent below the design value, and the two obvious explanations do not account for it</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Aykut C. Satici </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Robot Control Lab · Systems Engineering · UT Dallas
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<section id="what-is-actually-being-adapted" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="what-is-actually-being-adapted">What is actually being adapted</h2>
<p>The controller has <strong>one knob</strong>: the torque gain <span class="math inline">\(k\)</span> in <span class="math inline">\(\tau_g = k\Omega^2\)</span>. Everything else follows from it. Setting <span class="math inline">\(\dot\Omega = 0\)</span> gave</p>
<p><span class="math display">\[\frac{C_P(\lambda)}{\lambda^3} = \frac{2k}{\rho\pi R^5}\]</span></p>
<p>so choosing <span class="math inline">\(k\)</span> chooses the tip-speed ratio <span class="math inline">\(\lambda_{\text{eq}}(k)\)</span> the rotor settles at. Extremum seeking estimates <span class="math inline">\(\partial \ln P/\partial k\)</span> and integrates until that estimate is zero.</p>
<div class="claim">
<p>So the quantity that <strong>converges</strong> is <span class="math inline">\(k\)</span>. The tip-speed ratio is not adjusted, estimated, or held. It is what you read off afterward, through the monotone map <span class="math inline">\(k \mapsto \lambda_{\text{eq}}\)</span>.</p>
</div>
<div class="notes">
<p>Worth being firm about this, because CLR19 reports lambda-bar and it is easy to read that as the thing being controlled. It is not. Lambda is a state. The algorithm never forms it, because forming it would need the wind speed, which is the whole reason extremum seeking is being used.</p>
</div>
</section>
<section id="what-it-is-scored-against" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="what-it-is-scored-against">What it is scored against</h2>
<p>The reference value comes from the design power-coefficient curve:</p>
<p><span class="math display">\[k_{\text{opt}} = \tfrac12\rho\pi R^5\,\frac{C_P^{\max}}{\lambda_\star^3}
\;=\; 2.2, \qquad\text{from}\quad C_P^{\max} = 0.49,\ \ \lambda_\star = 7.5\]</span></p>
<div class="cols2">
<div class="card">
<p><span class="cardh">Where that curve comes from</span></p>
<p><strong>Blade-element momentum</strong>: chop each blade into spanwise strips, look up the lift and drag of the airfoil at each strip’s angle of attack, and integrate. That gives <span class="math inline">\(C_P(\lambda,\beta)\)</span> for the NREL 5 MW reference rotor.</p>
</div>
<div class="card">
<p><span class="cardh">What that makes it</span></p>
<p>A prediction from blade geometry and airfoil tables, in steady uniform flow. Not a measurement of the rotor in the simulation.</p>
</div>
</div>
<div class="warn">
<p>So <span class="math inline">\(k_{\text{opt}} = 2.2\)</span> inherits whatever that curve gets wrong. If its peak sits at the wrong <span class="math inline">\(\lambda\)</span>, the reference is wrong and every convergence claim is scored against the wrong number.</p>
</div>
</section>
<section id="the-anomaly" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="the-anomaly">The anomaly</h2>
<p><img src="assets/q1-anomaly.svg" class="img-fluid" alt="Left, converged torque gain against design for six LES conditions, every bar negative, from half a percent to eight percent low. Right, converged tip-speed ratio for the same six, every point above the design value of 7.5, reaching 7.85."></p>
<div class="warn">
<p>Every converged torque gain in the large-eddy simulations of <a href="#references">[CLR19]</a> sits <strong>below</strong> the design value, and every tip-speed ratio sits <strong>above</strong> it. Two algorithms, three wind speeds, two inflow conditions, and the sign never changes.</p>
</div>
<div class="notes">
<p>This is not a criticism of CLR19. The offsets are small enough to read as agreement, and nothing in it depends on them. They become interesting only once you want to resolve 0.2 in lambda.</p>
<p>Six runs, two independent algorithms, sign never flips. That is bias, not scatter.</p>
</div>
</section>
<section id="why-the-wind-does-not-cancel" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="why-the-wind-does-not-cancel">Why the wind does not cancel</h2>
<p>One dither period produces one number, a correlation:</p>
<p><span class="math display">\[\hat g \;=\; \frac{1}{aT}\int_0^T \ln P(t)\,g(t)\,dt,
\qquad
\ln P = \underbrace{\ln(\tfrac12\rho A)}_{\text{constant}}
+ \underbrace{3\ln V(t)}_{\text{the wind}}
+ \underbrace{\ln C_P(\lambda)}_{\text{the turbine}}\]</span></p>
<div class="cols2">
<div class="card">
<p><span class="cardh">the constant does cancel</span></p>
<p><span class="math inline">\(\int_0^T g\,dt = 0\)</span> by symmetry, so a constant contributes exactly nothing.</p>
</div>
<div class="card">
<p><span class="cardh">the wind does not</span></p>
<p><span class="math inline">\(3\ln V(t)\)</span> is not a constant. What survives is <span class="math inline">\(\tfrac{3}{aT}\int_0^T \ln V\,g\;dt\)</span>, which is zero <strong>in expectation</strong> and nonzero in <strong>any one window</strong>.</p>
</div>
</div>
<div class="claim">
<p>Flip a fair coin ten times: heads minus tails has expectation zero, and you still get <span class="math inline">\(+2\)</span> or <span class="math inline">\(-4\)</span>. Over 150 s the turbulence leans one way or the other against the square wave by chance. The wind does not <strong>bias</strong> the gradient. It adds <strong>scatter</strong>.</p>
</div>
</section>
<section id="and-the-scatter-is-large" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="and-the-scatter-is-large">And the scatter is large</h2>
<p><img src="assets/channels.svg" class="fig-wide img-fluid" alt="Time series over ten minutes. The wind contribution to log power swings with standard deviation 0.30 nepers; the turbine's response to the probe is a small clean sinusoid of amplitude 0.02."></p>
<div class="warn">
<p>In the raw record the irrelevant term is about <strong>fifteen times</strong> the signal: <span class="math inline">\(3\ln V\)</span> has <span class="math inline">\(\sigma \approx 3\,\mathrm{TI} = 0.30\)</span> nepers, against a probe response near <span class="math inline">\(0.02\)</span>.</p>
</div>
<div class="notes">
<p>Correlating against the dither over a window of length T shrinks that by roughly the square root of the correlation time over T, giving</p>
<p>sigma of g-hat, about 3 times TI times root tau-c over T, divided by a.</p>
<p>It falls as one over root T, which is exactly the averaging Rotea says is unavoidable, and as one over the dither amplitude. Neither ever drives it to zero.</p>
</div>
</section>
<section id="so-which-k-should-it-find" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="so-which-k-should-it-find">So which <span class="math inline">\(k\)</span> should it find?</h2>
<div class="cols3">
<div class="card">
<p><span class="cardh">(a) the design <span class="math inline">\(k\)</span></span></p>
<p><span class="math inline">\(k_{\text{opt}} = 2.2\)</span>, the gain that peaks the blade-element curve in steady uniform flow. What every paper scores against.</p>
</div>
<div class="card">
<p><span class="cardh">(b) the turbulent <span class="math inline">\(k\)</span></span></p>
<p>The gain maximizing <span class="math inline">\(\mathbb{E}[\ln P]\)</span> under the inflow the machine actually sees. Differs from (a) by a Jensen gap plus rotor lag.</p>
</div>
<div class="card">
<p><span class="cardh">(c) the algorithm’s fixed point</span></p>
<p>The gain where the <em>gradient estimate</em> vanishes, which adds whatever bias the demodulator carries.</p>
</div>
</div>
<div class="claim">
<p>Three different numbers. The runs all land near <span class="math inline">\(2.03\)</span>. Asking “how accurate is the estimator” is premature until we say which of these it was supposed to hit.</p>
</div>
<div class="notes">
<p>And note the reporting convention. The papers quote lambda-bar rather than k-bar, because lambda is the interpretable coordinate. But the two are the same fact: a torque gain 7.7 percent below design puts the rotor at a tip-speed ratio about 0.19 above design, and that is most of the 0.35 offset in the figures.</p>
</div>
</section>
<section id="candidate-one-estimator-bias" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="candidate-one-estimator-bias">Candidate one: estimator bias</h2>
<p><a href="#references">[CLR19]</a> dithers with a square wave, so the correlation is a two-point central difference. The slides that follow derive <span class="math inline">\(\hat g = J' + \tfrac{a^2}{6}J''' + O(a^4)\)</span> and the displacement <span class="math inline">\(\Delta u = -\tfrac{a^2}{6}\,J'''/J''\)</span> it leaves; the numbers are below.</p>
<p>Every term is computable: invert <span class="math inline">\(\varphi(\lambda) = C_P(\lambda)/\lambda^3 = c\,u\)</span> for <span class="math inline">\(\lambda_{\text{eq}}(u)\)</span>, with <span class="math inline">\(c\)</span> pinned by <span class="math inline">\(\varphi(\lambda_\star) = c\,u_{\text{opt}}\)</span>; form <span class="math inline">\(J(u) = \ln C_P(\lambda_{\text{eq}}(u))\)</span> and differentiate at the peak. Units below are Ciri et al.’s, <span class="math inline">\(u_{\text{opt}} = 2.2\)</span> N<span class="math inline">\(\cdot\)</span>m<span class="math inline">\(\cdot\)</span>rpm<span class="math inline">\(^{-2}\)</span>.</p>
<div class="cols2">
<div class="card">
<p><span class="cardh">read off the curve</span></p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td><span class="math inline">\(J''\)</span></td>
<td><span class="math inline">\(-0.145\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(J'''\)</span></td>
<td><span class="math inline">\(0.108\)</span></td>
</tr>
<tr class="odd">
<td>ratio</td>
<td><span class="math inline">\(-0.748\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(d\lambda/du\)</span></td>
<td><span class="math inline">\(-1.13\)</span> <span class="math inline">\(\;(=-\lambda_\star/3u_{\text{opt}})\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(a\)</span> (Ciri 2019)</td>
<td><span class="math inline">\(13.6\%\)</span> of <span class="math inline">\(k_{\text{opt}}\)</span></td>
</tr>
</tbody>
</table>
</div>
<div class="card">
<p><span class="cardh">the result</span></p>
<p><span class="math display">\[\Delta u = +0.0112\]</span></p>
<p><span class="math display">\[\Delta\lambda = \Delta u\cdot\frac{d\lambda}{du} = -0.013\]</span></p>
<p>Against an observed <span class="math inline">\(+0.35\)</span>, and with the wrong sign.</p>
</div>
</div>
</section>
<section id="candidate-two-the-peak-moved" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="candidate-two-the-peak-moved">Candidate two: the peak moved</h2>
<p>Rotor inertia is <span class="math inline">\(3.5\times10^7\)</span> kg m², so <span class="math inline">\(\lambda\)</span> swings rather than sits. Expanding <span class="math inline">\(\mathbb{E}[C_P(\bar\lambda+\delta)] \approx C_P + \tfrac12\sigma_\lambda^2 C_P''\)</span> and maximizing over <span class="math inline">\(\bar\lambda\)</span>,</p>
<p><span class="math display">\[\Delta\lambda \;=\; -\frac{\sigma_\lambda^2}{2}\,\frac{C_P'''}{C_P''},
\qquad C_P'' = -0.0551,\quad C_P''' = 0.0065\]</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(\sigma_\lambda\)</span></th>
<th><span class="math inline">\(0.3\)</span></th>
<th><span class="math inline">\(0.5\)</span></th>
<th><span class="math inline">\(0.8\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\Delta\lambda\)</span></td>
<td><span class="math inline">\(+0.005\)</span></td>
<td><span class="math inline">\(+0.015\)</span></td>
<td><span class="math inline">\(+0.037\)</span></td>
</tr>
</tbody>
</table>
<div class="claim">
<p>Same shape as candidate one, a third derivative over a second scaled by a variance, but opposite in meaning: one says the algorithm misses a fixed target, the other says the target moved. Note <span class="math inline">\(\sigma_\lambda\)</span> is <strong>estimated</strong>, from the share of turbulence energy above the rotor’s own pole, not measured.</p>
</div>
</section>
<section id="the-arithmetic" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="the-arithmetic">The arithmetic</h2>
<p><img src="assets/q1-budget.svg" class="fig-wide img-fluid" alt="Horizontal bars: finite-difference bias 0.012, turbulent optimum 0.015, averaging artifact 0.015, the three together 0.042, against an observed gap of 0.350."></p>
<div class="warn">
<p>Both fail, by more than an order of magnitude. Adding a third effect, that the reported <span class="math inline">\(\bar\lambda\)</span> is a time average and <span class="math inline">\(\lambda(u)\)</span> is curved, brings the total to <span class="math inline">\(0.042\)</span> against an observed <span class="math inline">\(0.350\)</span>.</p>
</div>
<div class="notes">
<p>Computed on the map from normalized torque gain to settled tip-speed ratio, using the dither amplitude <a href="#references">[CLR19]</a> actually used (Appendix A2, <span class="math inline">\(a = 0.3\)</span>).</p>
<p>The honest caveat, and it should be said out loud: the third derivative comes from an analytic surface fitted through the peak, not from the NREL tables. So quote the sensitivity rather than the number. To explain the whole gap by finite-difference bias you would need that third derivative about 28 times larger. A fitted surface can be wrong by a factor of two or three. Not by 28.</p>
</div>
</section>
<section id="costing-it-out" class="level1 divider">
<h1 class="divider">Costing it out</h1>
<p>Where the <span class="math inline">\(a^2/6\)</span>, the <span class="math inline">\(-1/3\)</span> and the amplitude trade actually come from.</p>
<section id="splitting-the-objective" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="splitting-the-objective">Splitting the objective</h2>
<p><span class="math inline">\(C_P\)</span> is naturally a function of <span class="math inline">\(\lambda\)</span>, but <span class="math inline">\(\lambda\)</span> is not settable. You turn the gain <span class="math inline">\(u\)</span>, and <span class="math inline">\(\lambda\)</span> follows through <span class="math inline">\(\lambda_{\text{eq}}(u)\)</span>. So split <span class="math inline">\(\ln P\)</span> into the part that moves with <span class="math inline">\(u\)</span> and the part that does not:</p>
<p><span class="math display">\[\ln P(t) \;=\; \underbrace{\ln(\tfrac12\rho A) + 3\ln V(t)}_{C(t),\ \text{no } u \text{ in it}}
\;+\; \underbrace{\ln C_P\big(\lambda_{\text{eq}}(u)\big)}_{J(u)}\]</span></p>
<p>A term with no <span class="math inline">\(u\)</span> in it has zero derivative in <span class="math inline">\(u\)</span>, so</p>
<p><span class="math display">\[\frac{\partial^n(\ln P)}{\partial u^n} = \frac{\partial^n J}{\partial u^n}
\qquad\text{for every } n\ge 1\]</span></p>
<div class="claim">
<p><span class="math inline">\(\ln P\)</span> needs the wind and cannot be evaluated; <span class="math inline">\(J\)</span> needs only the <span class="math inline">\(C_P\)</span> curve. They have identical derivatives, so <strong>derivatives</strong> may be taken on <span class="math inline">\(J\)</span> alone. That is not the same as saying <span class="math inline">\(C\)</span> disappears from the estimator.</p>
</div>
</section>
<section id="what-the-estimator-actually-returns" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="what-the-estimator-actually-returns">What the estimator actually returns</h2>
<p>The 2019 dither is a <strong>square wave</strong>: the knob sits at <span class="math inline">\(u+a\)</span> for the first half-period, <span class="math inline">\(u-a\)</span> for the second. The correlation is a difference of two half-period means, <span class="math inline">\(\hat g = \big[\bar y(u{+}a) - \bar y(u{-}a)\big]/2a\)</span>. Substituting the split:</p>
<p><span class="math display">\[\hat g \;=\;
\underbrace{\frac{J(u{+}a) - J(u{-}a)}{2a}}_{\text{the turbine}}
\;+\;
\underbrace{\frac{\bar C^{+} - \bar C^{-}}{2a}}_{\text{the wind}}\]</span></p>
<div class="warn">
<p><span class="math inline">\(\bar C^{\pm}\)</span> are means of the <strong>same</strong> <span class="math inline">\(C(t)\)</span> over <strong>different</strong> windows, so they do not cancel. This is the coin-flip term: zero mean, nonzero variance. It is where all the scatter comes from, and it is not part of any Taylor series.</p>
</div>
<div class="claim">
<p>Bias from the first term, scatter from the second. The next slides take them in turn.</p>
</div>
</section>
<section id="why-the-bias-is-a26" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="why-the-bias-is-a26">Why the bias is <span class="math inline">\(a^2/6\)</span></h2>
<p>Taylor-expand the turbine term about <span class="math inline">\(u\)</span>:</p>
<p><span class="math display">\[J(u+a) = J + aJ' + \tfrac{a^2}{2}J'' + \tfrac{a^3}{6}J''' + \tfrac{a^4}{24}J'''' + \cdots\]</span> <span class="math display">\[J(u-a) = J - aJ' + \tfrac{a^2}{2}J'' - \tfrac{a^3}{6}J''' + \tfrac{a^4}{24}J'''' - \cdots\]</span></p>
<p>Subtracting, <strong>every even power cancels</strong>, which is what “central” difference means. Then divide by <span class="math inline">\(2a\)</span>: every term drops one order, <span class="math inline">\(O(a^5)\)</span> included.</p>
<p><span class="math display">\[J(u{+}a) - J(u{-}a) = 2aJ' + \tfrac{a^3}{3}J''' + O(a^5)
\;\;\Longrightarrow\;\;
\frac{J(u{+}a) - J(u{-}a)}{2a} = J' + \frac{a^2}{6}J''' + O(a^4)\]</span></p>
<p>That is the turbine term alone. Adding back the wind term from the previous slide gives the whole estimator:</p>
<p><span class="math display">\[\hat g \;=\; J' + \frac{a^2}{6}J''' + O(a^4)
\;+\; \underbrace{\frac{\bar C^{+} - \bar C^{-}}{2a}}_{\text{the wind}}\]</span></p>
<div class="claim">
<p>The algorithm stops where <span class="math inline">\(\hat g = 0\)</span>, not where <span class="math inline">\(J' = 0\)</span>. Linearizing <span class="math inline">\(J' \approx J''\Delta u\)</span> gives <span class="math inline">\(\Delta u = -\tfrac{a^2}{6}\,J'''/J''\)</span>.</p>
</div>
<div class="notes">
<p>The leading error is a-squared rather than a because the even terms cancel. A one-sided difference would be order a and far worse.</p>
<p>And the bias is not an artifact of the square wave. Sinusoidal dithering, as in Kumar and Rotea 2022, expands J of u plus a sine and demodulates against a sine, picking up the fourth moment of a sine, three eighths, and gives a-squared over eight instead of over six. Same order, different constant.</p>
</div>
</section>
<section id="from-a-gain-error-to-a-tip-speed-ratio" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="from-a-gain-error-to-a-tip-speed-ratio">From a gain error to a tip-speed ratio</h2>
<p>The bias lives in <span class="math inline">\(u\)</span>, the torque gain the algorithm turns; Ciri et al.&nbsp;report <span class="math inline">\(\lambda\)</span>. The equilibrium relation converts between them. With <span class="math inline">\(\varphi(\lambda) := C_P(\lambda)/\lambda^3\)</span> it reads <span class="math inline">\(\varphi(\lambda_{\text{eq}}) = c\,u\)</span>, where <span class="math inline">\(c\)</span> is a rotor constant that also carries whatever units <span class="math inline">\(u\)</span> is quoted in. Differentiate implicitly:</p>
<p><span class="math display">\[\varphi'(\lambda)\,\frac{d\lambda}{du} = c
\qquad\Longrightarrow\qquad
\frac{d\lambda}{du} = \frac{c}{\varphi'(\lambda)}\]</span></p>
<p>You never have to evaluate <span class="math inline">\(c\)</span>: the optimum pins it, <span class="math inline">\(c = \varphi(\lambda_\star)/u_{\text{opt}}\)</span>. And at the peak <span class="math inline">\(C_P' = 0\)</span>, so <span class="math inline">\(\varphi'(\lambda_\star) = -3C_P^{\max}/\lambda_\star^4\)</span>. Everything cancels:</p>
<p><span class="math display">\[\frac{d\lambda}{du}\bigg|_\star
= \frac{C_P^{\max}\big/(\lambda_\star^3\,u_{\text{opt}})}{-3C_P^{\max}\big/\lambda_\star^4}
= -\frac{\lambda_\star}{3\,u_{\text{opt}}}
\qquad\Longleftrightarrow\qquad
\frac{d\ln\lambda}{d\ln u}\bigg|_\star = -\frac13\]</span></p>
<div class="claim">
<p>Negative: more braking torque, slower rotor, lower <span class="math inline">\(\lambda\)</span>. And the leverage is <strong>exactly</strong> <span class="math inline">\(-1/3\)</span> in elastic terms, free of <span class="math inline">\(c\)</span>, <span class="math inline">\(\rho\)</span>, <span class="math inline">\(R\)</span>, the gearbox and the choice of units. With Ciri et al.’s <span class="math inline">\(u_{\text{opt}} = 2.2\)</span> N<span class="math inline">\(\cdot\)</span>m<span class="math inline">\(\cdot\)</span>rpm<span class="math inline">\(^{-2}\)</span> that is <span class="math inline">\(d\lambda/du = -1.14\)</span>.</p>
</div>
<div class="notes">
<p>Where the one third comes from: at the peak C_P is flat, so near it phi is essentially C_P-max over lambda cubed. The equilibrium then says u goes like lambda to the minus three, and inverting a cube root is where the third comes from. Nothing about the blades enters.</p>
<p>This is also why quoting a slope in absolute units is a trap. Minus 1.14 per newton-meter-per-rpm-squared sounds small and minus 39.8 would sound large, but they are the same physical statement in two unit systems. The elasticity is the number that means something.</p>
<p>Linearizing is safe here. At the predicted bias, half a percent in u, linear and exact agree to three decimals at minus 0.012. At the observed anomaly, 7.7 per cent, linear gives 0.191 and exact 0.196.</p>
<p>And the sign is the point. The anomaly has the gain landing low, so lambda high. The bias predicts delta-u positive, gain high, lambda low. Opposite sign. That conclusion survives any error in the magnitude.</p>
</div>
</section>
<section id="sizing-the-scatter" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="sizing-the-scatter">Sizing the scatter</h2>
<p>The wind term is <span class="math inline">\((\bar C^{+} - \bar C^{-})/2a\)</span>. Let <span class="math inline">\(\sigma_y\)</span> be the standard deviation of the fluctuating part of <span class="math inline">\(y = \ln P\)</span>, and let <span class="math inline">\(\tau_c\)</span> be its <strong>correlation time</strong>: the lag beyond which the signal has forgotten itself, so a window of length <span class="math inline">\(T_w\)</span> carries about <span class="math inline">\(T_w/\tau_c\)</span> independent samples rather than <span class="math inline">\(T_w/\Delta t\)</span>. Each half-period average has <span class="math inline">\(T_w = T/2\)</span>:</p>
<p><span class="math display">\[\operatorname{Var}(\bar C^{\pm})
= \frac{\sigma_y^2}{\underbrace{(T/2)/\tau_c}_{\text{independent samples}}}
= \frac{2\sigma_y^2\tau_c}{T}\]</span></p>
<p>The two windows are disjoint, so treat them as independent and add variances. Then divide by <span class="math inline">\(2a\)</span>:</p>
<p><span class="math display">\[\operatorname{Var}(\hat g_{\text{noise}}) = \frac{1}{4a^2}\cdot\frac{4\sigma_y^2\tau_c}{T}
\;\;\Longrightarrow\;\;
\boxed{\;\sigma_{\hat g} = \frac{\sigma_y}{a}\sqrt{\frac{\tau_c}{T}}\;}\]</span></p>
<div class="claim">
<p>The <span class="math inline">\(1/a\)</span> is the whole difficulty: the wind does not care how hard you dither, so shrinking the probe to kill bias amplifies the noise one for one. The <span class="math inline">\(\sqrt{\tau_c/T}\)</span> is weaker than it looks, and <strong>only holds for <span class="math inline">\(\tau_c \ll T/2\)</span></strong>, which this turbine does not satisfy.</p>
</div>
<div class="notes">
<p>Sigma-y: log-power is a constant plus three log V plus J, so its fluctuation is three times delta-V over V, three times the turbulence intensity. At ten per cent that is 0.30 nepers. It is an upper bound, because the rotor averages over the whole disk and its own inertia filters, so rotor-effective wind is smoother than a point measurement. Tau-c gets its own slide next.</p>
</div>
</section>
<section id="choosing-tau_c" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="choosing-tau_c">Choosing <span class="math inline">\(\tau_c\)</span></h2>
<p>Taylor’s frozen-turbulence picture: eddies of size <span class="math inline">\(L\)</span> sweep past at <span class="math inline">\(U\)</span>, so the signal decorrelates in <span class="math inline">\(\tau_{\text{int}} = L/U\)</span>. IEC 61400-1 fixes <span class="math inline">\(L\)</span> from hub height <a href="#references">[IEC]</a>: <span class="math inline">\(\Lambda_1 = 0.7\min(z,60)\)</span> m, <span class="math inline">\(L = 8.1\Lambda_1\)</span>. At <span class="math inline">\(h = 90\)</span> m <span class="math inline">\(\ge 60\)</span> m the scale parameter is <span class="math inline">\(\Lambda_1 = 42\)</span> m and the longitudinal integral length is <span class="math inline">\(L = 8.1\Lambda_1\)</span>:</p>
<p><span class="math display">\[L = 8.1(42) = 340\ \text{m}
\;\;\Longrightarrow\;\;
\tau_{\text{int}} = \frac{340}{8} = 42.5\ \text{s}
\;\;\Longrightarrow\;\;
\tau_c = 2\tau_{\text{int}} = 85\ \text{s}\]</span></p>
<p>The factor of two is the convention: independent samples sit <span class="math inline">\(2\tau_{\text{int}}\)</span> apart, not <span class="math inline">\(\tau_{\text{int}}\)</span>.</p>
<div class="warn">
<p><span class="math inline">\(\tau_c = 85\)</span> s exceeds the half-period <span class="math inline">\(T/2 = 75\)</span> s, so <span class="math inline">\(\sigma_{\hat g}\)</span> is outside the regime it was derived in. Wind slower than <span class="math inline">\(T\)</span> is <strong>common to both half-windows and cancels in their difference</strong>, so the formula over-states the scatter: exactly, by <span class="math inline">\(1.5\times\)</span> at <span class="math inline">\(\tau_{\text{int}} = 42.5\)</span> s and <span class="math inline">\(2.4\times\)</span> at <span class="math inline">\(85\)</span> s.</p>
</div>
<div class="claim">
<p><span class="math inline">\(L\)</span> is a design standard, not a measurement of this inflow, so <span class="math inline">\(\tau_c\)</span> is good to a factor of two. That costs <span class="math inline">\(12\%\)</span> in the answer, since <span class="math inline">\(a_\star \propto \tau_c^{1/6}\)</span>.</p>
</div>
<div class="notes">
<p>Sanity check against the simulation domain of Ciri, Leonardi and Rotea. Their Appendix A1 of <a href="#references">[CLR19]</a> gives a precursor box of 9.6 rotor diameters streamwise, 1210 meters, which caps the largest eddy it can hold; at eight meters per second that is a 151-second flow-through. So 340 meters is comfortably inside what the box can represent, and the IEC number is not contradicted by the simulation setup.</p>
<p>The exponents are what make this reportable. Tau-c enters the scatter as a square root and the optimal amplitude as a sixth root, so a scale estimate is enough where a measurement would be needed if it entered linearly.</p>
</div>
</section>
<section id="how-big-should-the-dither-be" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="how-big-should-the-dither-be">How big should the dither be?</h2>
<p><strong>Bias</strong>, from the previous slides, converted to <span class="math inline">\(\lambda\)</span>:</p>
<p><span class="math display">\[|\Delta\lambda| = \underbrace{\tfrac16\left|\tfrac{J'''}{J''}\right|\left|\tfrac{d\lambda}{du}\right|}_{K_b}\,a^2
= \tfrac16(0.748)(1.13)\,a^2 = 0.141\,a^2
\;\;\longrightarrow\;\; 0.68\,\alpha^2\]</span></p>
<p><strong>Scatter.</strong> One period gives gradient noise <span class="math inline">\(\sigma_y\sqrt{\tau_c/T}/a\)</span>; a gradient error displaces the settled gain by <span class="math inline">\(\delta g/|J''|\)</span>; <span class="math inline">\(N\)</span> periods average it down:</p>
<p><span class="math display">\[\sigma_\lambda = \underbrace{\frac{\sigma_y\sqrt{\tau_c/T}}{|J''|}\left|\tfrac{d\lambda}{du}\right|}_{K_v}\,\frac{1}{a\sqrt N}
\;\;\longrightarrow\;\; \frac{K_v/u_{\text{opt}}}{\alpha\sqrt N}\]</span></p>
<p>Writing <span class="math inline">\(a = \alpha\,u_{\text{opt}}\)</span> puts both in the units the figure plots: <span class="math inline">\(\alpha\)</span> is the dither as a fraction of the optimal gain. <span class="math inline">\(K_b\)</span> follows from the <span class="math inline">\(C_P\)</span> curve alone. <span class="math inline">\(K_v\)</span> does not, and the next slide is why.</p>
<div class="claim">
<p><span class="math inline">\(K_b\)</span> carries no <span class="math inline">\(N\)</span>; <span class="math inline">\(K_v\)</span> does. <strong>Bias survives averaging, scatter does not.</strong></p>
</div>
<div class="notes">
<p>Inputs, all in the units of Ciri et al.&nbsp;2019 where u-opt is 2.2: J-triple-prime over J-double-prime is minus 0.748 and d-lambda-d-u is minus 1.13, both from the fitted surface. Sigma-y is three times turbulence intensity, 0.30 nepers. Tau-c 85 seconds from the previous slide, T the 150-second period, J-double-prime 0.145.</p>
<p>The alpha forms are the ones to trust. Rescaling u multiplies K-b and K-v by compensating powers, so the alpha-form coefficients are the same whatever units anyone quotes the gain in. K-b over u-opt squared is 0.68 from the curve; K-v over u-opt is at most 0.033 from the data.</p>
</div>
</section>
<section id="k_v-has-to-be-calibrated-not-predicted" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="k_v-has-to-be-calibrated-not-predicted"><span class="math inline">\(K_v\)</span> has to be calibrated, not predicted</h2>
<p>Feeding <span class="math inline">\(\sigma_y = 3\,\text{TI} = 0.30\)</span> and <span class="math inline">\(\tau_c = 85\)</span> s into <span class="math inline">\(\sigma_{\hat g}\)</span> gives <span class="math inline">\(K_v/u_{\text{opt}} = 0.80\)</span>, hence <span class="math inline">\(\sigma_\lambda = 3.4\)</span> at their dither. The rotor would wander the whole curve. The converged tip-speed ratios reported in <a href="#references">[CLR19]</a> say otherwise:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>converged <span class="math inline">\(\bar\lambda\)</span></th>
<th><span class="math inline">\(U=4\)</span></th>
<th><span class="math inline">\(U=8\)</span></th>
<th><span class="math inline">\(U=12\)</span></th>
<th>spread</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong><a href="#references">[CLR19]</a> Table 4</strong>, shear <span class="math inline">\(+\)</span> <span class="math inline">\(10\%\)</span> TI</td>
<td>7.72, 7.75</td>
<td>7.85, 7.85</td>
<td>7.85</td>
<td><span class="math inline">\(0.13\)</span></td>
</tr>
<tr class="even">
<td><strong><a href="#references">[CLR19]</a> Table 3</strong>, uniform inflow</td>
<td>7.60, 7.60</td>
<td>7.75, 7.73</td>
<td>7.70</td>
<td><span class="math inline">\(0.15\)</span></td>
</tr>
</tbody>
</table>
<p>Each cell is ESC then LP-ESC; at <span class="math inline">\(U=12\)</span> only LP-ESC is listed, because plain ESC did not converge there.</p>
<div class="warn">
<p>Turbulence adds <strong>nothing</strong> to the spread of the converged means. The 40-minute mean covers <span class="math inline">\(\approx 2\)</span> independent realizations, so <span class="math inline">\(\sigma_\lambda \lesssim 0.14\)</span> and <span class="math inline">\(K_v/u_{\text{opt}} \lesssim 0.033\)</span>: the prediction is too big by <span class="math inline">\(\mathbf{24}\)</span> to <span class="math inline">\(\mathbf{40\times}\)</span>.</p>
</div>
<div class="claim">
<p>The demodulator rejects far more of the wind than <span class="math inline">\(\sigma_y\sqrt{\tau_c/T}\)</span> allows for, because that form counts the whole spectrum while the correlation sees a narrow band at <span class="math inline">\(1/T\)</span>, sited in a spectral valley on purpose. <strong>Quantifying that rejection is the open problem</strong>, and until it is done <span class="math inline">\(K_v\)</span> is an upper bound read off the data.</p>
</div>
<div class="notes">
<p>Both rows are <a href="#references">[CLR19]</a>: Table 3 is the uniform-inflow campaign, Table 4 the shear-plus-turbulence one, same three wind speeds and same two algorithms.</p>
<p>Two things not to overstate. The spread across runs is a bound, not a measurement: the three wind speeds genuinely converge to different lambda, so some of the 0.13 is physics rather than noise, which only makes the bound tighter. And no standard deviations are published, which is the whole reason a bound is the best available.</p>
<p>Redoing the demodulator against a Kaimal spectrum instead of a single correlation time brings sigma-g-hat from 0.75 to 0.43. That is the right method and it closes only a factor of 1.7 of the 24. The rest is in sigma-y.</p>
</div>
</section>
<section id="trading-bias-against-scatter" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="trading-bias-against-scatter">Trading bias against scatter</h2>
<p>Bias and scatter are now both errors in <span class="math inline">\(\lambda\)</span>, so they are comparable. What a run actually delivers is the <strong>mean-squared error</strong>, bias squared plus variance:</p>
<p><span class="math display">\[M(a) = \underbrace{\big(K_b a^2\big)^2}_{\text{bias}^2}
+ \underbrace{\left(\frac{K_v}{a\sqrt N}\right)^2}_{\text{variance}}
= K_b^2 a^4 + \frac{K_v^2}{a^2 N}\]</span></p>
<p>One term climbs with <span class="math inline">\(a\)</span> and the other falls, so the minimum is interior. Set the derivative to zero:</p>
<p><span class="math display">\[\frac{dM}{da} = 4K_b^2a^3 - \frac{2K_v^2}{a^3N} = 0
\;\;\Longrightarrow\;\;
a_\star^6 = \frac{K_v^2}{2K_b^2N}
\;\;\Longrightarrow\;\;
a_\star \propto N^{-1/6}\]</span></p>
<p>Substituting <span class="math inline">\(a_\star\)</span> back gives what that amplitude actually achieves:</p>
<p><span class="math display">\[M(a_\star) = \left(2^{-2/3} + 2^{1/3}\right)K_b^{2/3}K_v^{4/3}N^{-2/3}
\;\;\Longrightarrow\;\;
\sqrt{M(a_\star)} \propto N^{-1/3}\]</span></p>
<div class="claim">
<p>Both limits are bad: <span class="math inline">\(a\to0\)</span> kills the bias but sends the scatter to infinity, <span class="math inline">\(a\to\infty\)</span> does the reverse. Two different exponents fall out and they are easy to confuse: the <strong>amplitude</strong> goes as <span class="math inline">\(N^{-1/6}\)</span>, the <strong>error it buys</strong> goes as <span class="math inline">\(N^{-1/3}\)</span>.</p>
</div>
<div class="notes">
<p>The sixth root is the part with teeth. It says you cannot buy your way out of a badly chosen dither by running longer: thirty times the run length moves the optimum by less than a factor of two. Amplitude is a design choice that has to be made correctly up front.</p>
</div>
</section>
<section id="the-loop-is-a-constant-gain-recursion" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="the-loop-is-a-constant-gain-recursion">The loop is a constant-gain recursion</h2>
<p>Equations 11 and 12 of Ciri, Leonardi &amp; Rotea <a href="#references">[CLR19]</a> take one step per dither period:</p>
<p><span class="math display">\[u_{n+1} = u_n + \kappa\int_0^{T} y(t)\,g_c(t)\,dt\]</span></p>
<p>The demodulator <span class="math inline">\(g_c\)</span> is <span class="math inline">\(+1\)</span> on the first half-period and <span class="math inline">\(-1\)</span> on the second, blanked for <span class="math inline">\(T_r\)</span> after each step. So the integral is exactly the half-window difference from before, <span class="math inline">\((\tfrac T2 - T_r)(\bar y^{+} - \bar y^{-})\)</span>, and since <span class="math inline">\(\hat g = (\bar y^{+}-\bar y^{-})/2a\)</span>:</p>
<p><span class="math display">\[u_{n+1} = u_n + \kappa_{\text{eff}}\,\hat g_n,
\qquad \kappa_{\text{eff}} := 2a\kappa\left(\tfrac T2 - T_r\right)\]</span></p>
<div class="claim">
<p>The correlate-and-step loop <strong>is</strong> a gradient ascent whose step size is <span class="math inline">\(\kappa_{\text{eff}}\)</span>. There is no <span class="math inline">\(1/n\)</span> anywhere, so the step never decays.</p>
</div>
<div class="notes">
<p>The units do not quite close in Table 2 of <a href="#references">[CLR19]</a>. The LP-ESC integrand is log-power, which is dimensionless, so its kappa should be gain per second. The table lists watts per rpm squared for both rows, which is what the plain-ESC row needs. That is why the value of kappa-eff below is pinned from the reported settling time rather than read off the table.</p>
</div>
</section>
<section id="linearizing-about-the-peak" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="linearizing-about-the-peak">Linearizing about the peak</h2>
<p><span class="math inline">\(\hat g_n\)</span> is an estimate of <span class="math inline">\(J'(u_n)\)</span>, and two facts turn the update into a linear recursion. First, at the peak <span class="math inline">\(J'(u^\star)=0\)</span>, so for <span class="math inline">\(\tilde u_n := u_n - u^\star\)</span> small,</p>
<p><span class="math display">\[J'(u_n) = J'(u^\star) + J''\tilde u_n + O(\tilde u_n^2) \approx J''\,\tilde u_n\]</span></p>
<p>Second, the estimator does not return <span class="math inline">\(J'\)</span> cleanly. It returns it plus the wind term derived earlier, which is what <span class="math inline">\(w_n\)</span> is:</p>
<p><span class="math display">\[\hat g_n = J''\tilde u_n + \underbrace{w_n}_{(\bar C^{+}-\bar C^{-})/2a},
\qquad \mathbb{E}[w_n]=0,
\qquad \operatorname{Var}(w_n) = \sigma_{\hat g}^2 = \frac{\sigma_y^2\tau_c}{a^2T}\]</span></p>
<p>Substitute into the update and subtract <span class="math inline">\(u^\star\)</span> from both sides:</p>
<p><span class="math display">\[\tilde u_{n+1} = \big(1 + \kappa_{\text{eff}}J''\big)\tilde u_n + \kappa_{\text{eff}}w_n
= \rho\,\tilde u_n + \kappa_{\text{eff}}w_n,
\qquad \rho := 1 - g,\;\; g := \kappa_{\text{eff}}|J''|\]</span></p>
<div class="claim">
<p><span class="math inline">\(J''&lt;0\)</span> at a maximum, which is why <span class="math inline">\(1+\kappa_{\text{eff}}J''\)</span> is <span class="math inline">\(1-g\)</span>. The loop is a scalar AR(1) driven by gradient-estimate noise.</p>
</div>
</section>
<section id="what-n-is-and-what-it-is-not" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="what-n-is-and-what-it-is-not">What <span class="math inline">\(N\)</span> is, and what it is not</h2>
<p>An AR(1) has a stationary variance. Take variances of both sides, use independence of <span class="math inline">\(w_n\)</span> from <span class="math inline">\(\tilde u_n\)</span>, and set <span class="math inline">\(V_{n+1}=V_n=V\)</span>:</p>
<p><span class="math display">\[V = \rho^2 V + \kappa_{\text{eff}}^2\sigma_{\hat g}^2
\;\;\Longrightarrow\;\;
V = \frac{\kappa_{\text{eff}}^2\sigma_{\hat g}^2}{1-\rho^2}
= \frac{g}{2-g}\cdot\frac{\sigma_{\hat g}^2}{J''^2}\]</span></p>
<p>using <span class="math inline">\(\kappa_{\text{eff}} = g/|J''|\)</span> and <span class="math inline">\(1-\rho^2 = g(2-g)\)</span>. Averaging <span class="math inline">\(N\)</span> periods instead would give <span class="math inline">\(\sigma_{\hat g}^2/(N J''^2)\)</span>. Equating the two:</p>
<p><span class="math display">\[\boxed{\;N_{\text{eff}} = \frac{2}{g} - 1\;}\]</span></p>
<div class="claim">
<p><span class="math inline">\(N\)</span> is a <strong>tuning</strong>, not a run length. Table 2 of <a href="#references">[CLR19]</a>, with <span class="math inline">\(k\)</span> going <span class="math inline">\(4.5 \to 2.2\)</span> and <span class="math inline">\(99\%\)</span> of steady power in 10 min <span class="math inline">\(=\)</span> 4 periods, gives <span class="math inline">\(g \approx 0.49\)</span>, so <span class="math inline">\(N_{\text{eff}} \approx 3\)</span>. An hour instead of ten minutes changes nothing.</p>
</div>
<div class="notes">
<p>This is the part that is easy to get wrong and worth saying out loud on Friday. A constant-gain stochastic approximation does not converge to a point. It converges to a stationary distribution whose spread is set by the gain alone. Halving the gain halves the variance and doubles the settling time, which is the trade the tuning actually makes.</p>
<p>Only a decaying gain, or Polyak-Ruppert averaging of the iterates on top of a constant gain, turns run length into accuracy. Neither is in this algorithm, which is one of the concrete things to propose.</p>
</div>
</section>
<section id="and-the-answer" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="and-the-answer">And the answer</h2>
<p><img src="assets/biasvar.svg" class="fig-band img-fluid" alt="Log-log plot of error in lambda against dither amplitude as a fraction of the optimal torque gain. Bias rises as the square of amplitude, scatter falls as one over amplitude, and the total has a minimum near 27 percent. The published value of 13.6 percent is marked to the left of it."></p>
<div class="claim">
<p>With <span class="math inline">\(K_v\)</span> bounded from Table 4 of <a href="#references">[CLR19]</a> and <span class="math inline">\(N_{\text{eff}} = 3\)</span>: <span class="math inline">\(a_\star \lesssim 27\%\)</span> of <span class="math inline">\(k_{\text{opt}}\)</span>, against the published <span class="math inline">\(13.6\%\)</span>. <strong>Within a factor of two</strong>, and scatter still beats bias by <span class="math inline">\(11\times\)</span> there, so the loop is variance-limited but not wildly mistuned.</p>
</div>
<div class="warn">
<p><span class="math inline">\(a_\star\)</span> is an upper bound, because <span class="math inline">\(K_v\)</span> is. The honest statement is that the published amplitude is on the small side of optimal and that nobody, here included, can yet compute <span class="math inline">\(K_v\)</span> from the turbulence.</p>
</div>
<div class="notes">
<p>The sixth root is what makes this survivable. K-v is known only as an upper bound, and a-star goes as K-v to the one third, so even an order of magnitude of slack in K-v is about a factor of two in the amplitude. That is why a bound is still worth quoting.</p>
<p>A separate point about the reported numbers, worth raising on Friday. In that same paper the steady-state statistics are averaged from twenty to sixty minutes, forty minutes, over a precursor that repeats every twenty. So every quoted mean, including the converged lambda-bar of 7.85 that Q1 is about, rests on two independent wind realizations. That is not a criticism of the simulations, it is the reason the published numbers carry no error bars and the concrete argument for rerunning with non-repeating seeds.</p>
<p>Three soft spots. K-b inherits the fitted C-P surface through a third derivative, which is what a fit reproduces worst, and that one cuts both ways. The root-N averaging assumes independent periods, but the period is 150 seconds against a correlation time of 85, a ratio of 1.8, so consecutive periods are correlated and the effective N is below 3, which pushes a-star up further. And the step from gradient scatter to gain scatter is a linearization in the curvature.</p>
<p>The obvious defense of a small dither is loads. Nobody states that trade either.</p>
</div>
</section>
<section id="how-wrong-would-the-curve-have-to-be" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="how-wrong-would-the-curve-have-to-be">How wrong would the curve have to be?</h2>
<p>Both estimates hinge on a third derivative, and third derivatives are what a fitted surface reproduces worst.</p>
<div class="warn">
<p>To explain the whole <span class="math inline">\(0.35\)</span> by estimator bias you would need the ratio <span class="math inline">\(J'''/J''\)</span> to be <span class="math inline">\(-20.8\)</span>, against the fitted <span class="math inline">\(-0.748\)</span>. <strong>A factor of 28.</strong></p>
</div>
<div class="cols2">
<div class="card">
<p><span class="cardh">What is solid</span></p>
<p>The formulas, the inversion of the equilibrium relation, and the dither amplitude, read straight out of <a href="#references">[CLR19]</a>.</p>
</div>
<div class="card">
<p><span class="cardh">What is not</span></p>
<p>The <span class="math inline">\(C_P\)</span> surface. These figures use Heier’s analytic curve remapped onto <span class="math inline">\((7.5,\,0.49)\)</span>, not the NREL table, and both third derivatives inherit that.</p>
</div>
</div>
<div class="claim">
<p>An order-of-magnitude argument, good to a factor of a few, not verified against the real rotor. Enough to motivate the test, which settles the question without needing either curve.</p>
</div>
<div class="notes">
<p>What would firm this up is recomputing the two derivatives from the actual NREL 5 MW power-coefficient table rather than an analytic fit. Those tables are in the reference-turbine reports, which our own scoping note already lists under missing and wanted. Worth chasing for this alone.</p>
<p>A fit that matches the peak’s location and curvature being wrong by a factor of 28 in the third derivative is implausible. But implausible is not verified, and it should be said that way rather than glossed.</p>
</div>
</section>
<section id="what-survives" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="what-survives">What survives</h2>
<div class="cols2">
<div class="card">
<p><span class="cardh">The decisive split</span></p>
<p><a href="#references">[CLR19]</a> Table 3 runs the same machine in <strong>uniform</strong> inflow: no turbulence, no peak shift, negligible scatter. The offset is still <span class="math inline">\(+0.10\)</span> to <span class="math inline">\(+0.25\)</span>.</p>
</div>
<div class="card">
<p><span class="cardh">What that leaves</span></p>
<p>Turbulence can account for at most the difference between the two campaigns, about <span class="math inline">\(0.1\)</span>. The rest is present when nothing stochastic is happening at all.</p>
</div>
</div>
<div class="claim">
<p>Neither candidate can act in uniform inflow, yet most of the gap is already there. The design curve is <strong>already known to be wrong about the level</strong>, <span class="math inline">\(0.44\)</span> realized against <span class="math inline">\(0.49\)</span>. Nobody has checked whether it is also wrong about the <strong>location</strong>, and that is the one explanation the arithmetic cannot touch.</p>
</div>
<div class="notes">
<p>This inverts what I would have proposed a week ago. The obvious experiment was to vary the dither amplitude and look for an a-squared scaling in the offset. I now expect that experiment to return nothing, because the predicted effect is 0.012 and seed-to-seed scatter will be larger.</p>
</div>
</section>
<section id="the-test" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="the-test">The test</h2>
<div class="openq">
<p>Stop closing the loop. Hold the torque gain at a series of fixed values, run each long enough to average out the turbulence, and <strong>measure the simulator’s own <span class="math inline">\(C_P(\lambda)\)</span> curve.</strong> Then ask where its peak is.</p>
</div>
<div class="cols2">
<div class="card">
<p><span class="cardh">If the peak is at 7.5</span></p>
<p>The gap is real and none of the three candidates explain it. That is a more interesting outcome than confirming one of them.</p>
</div>
<div class="card">
<p><span class="cardh">If the peak is near 7.85</span></p>
<p>There is no estimator bias. The algorithms were right, the reference was wrong, and every convergence claim in the line needs restating against the new number.</p>
</div>
</div>
<div class="small">
<p>A few days of compute, no new code, and it is the same measurement the simulator-fidelity question needs anyway.</p>
</div>
</section>
<section id="why-this-one-comes-first" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="why-this-one-comes-first">Why this one comes first</h2>
<div class="cols3">
<div class="card">
<p><span class="cardh">It gates the bound</span></p>
<p>You cannot write a performance bound for the estimation of a quantity that has not been defined.</p>
</div>
<div class="card">
<p><span class="cardh">It gates stability</span></p>
<p>Calling a run unstable presumes you know what it failed to converge to.</p>
</div>
<div class="card">
<p><span class="cardh">It gates the application</span></p>
<p>Detecting a <span class="math inline">\(0.2\)</span> shift from erosion is hopeless if the reference carries an unexplained <span class="math inline">\(0.35\)</span>.</p>
</div>
</div>
<div class="claim">
<p>Cheapest of the open questions, and the one the others rest on. <strong>Worked through, it closes</strong>: most of the offset survives in uniform inflow where no estimator effect can act, so the residual is in the reference, not the algorithm. What it leaves behind is a measurement, not a research program.</p>
</div>
</section>
<section id="where-does-the-torque-gain-converge" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="where-does-the-torque-gain-converge">Where does the torque gain converge?</h2>
<div class="closing">
<div class="lead">
<p>Two explanations, costed out, both dead by an order of magnitude, and most of the offset survives in inflow where neither can act.</p>
</div>
<div class="cols2">
<div class="card">
<p><span class="cardh">The claim</span></p>
<p>The offset is not estimator bias, not a Jensen shift, and not scatter: the scatter is bounded at <span class="math inline">\(\sigma_\lambda \lesssim 0.14\)</span> by the run-to-run spread. What remains is that the simulated rotor’s peak is not at <span class="math inline">\(7.5\)</span>.</p>
</div>
<div class="card">
<p><span class="cardh">The caveat</span></p>
<p>The third derivative behind that arithmetic comes from a fitted surface. The sensitivity is stated on the arithmetic slide: it would have to be wrong by <span class="math inline">\(28\times\)</span>.</p>
</div>
</div>
<div class="small">
<p>Sources: <a href="#references">[CLR19]</a> Tables 2–4 and Appendices A1–A2; <a href="#references">[IEC]</a> for the turbulence length scale. Full list on the next slide.</p>
</div>
</div>
</section>
<section id="references" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="references">References</h2>
<div class="refs">
<p><strong>[R17]</strong>&nbsp; M. A. Rotea, <em>Logarithmic power feedback for extremum seeking control of wind turbines</em>, IFAC-PapersOnLine <strong>50</strong>(1) (2017) 4504–4509. <a href="https://doi.org/10.1016/j.ifacol.2017.08.381">doi:10.1016/j.ifacol.2017.08.381</a></p>
<p><strong>[CLR19]</strong>&nbsp; U. Ciri, S. Leonardi &amp; M. A. Rotea, <em>Evaluation of log-of-power extremum seeking control for wind turbines using large eddy simulations</em>, Wind Energy <strong>22</strong> (2019) 992–1002. <a href="https://doi.org/10.1002/we.2336">doi:10.1002/we.2336</a></p>
<p><strong>[KR22]</strong>&nbsp; D. Kumar &amp; M. A. Rotea, <em>Wind turbine power maximization using log-power proportional-integral extremum seeking</em>, Energies <strong>15</strong> (2022) 1004. <a href="https://doi.org/10.3390/en15031004">doi:10.3390/en15031004</a></p>
<p><strong>[KR24]</strong>&nbsp; D. Kumar &amp; M. A. Rotea, <em>Optimal tip-speed ratio for degraded blades</em>, Wind Energy Science <strong>9</strong> (2024) 2133–2146. <a href="https://doi.org/10.5194/wes-9-2133-2024">doi:10.5194/wes-9-2133-2024</a></p>
<p><strong>[RKAJ24]</strong>&nbsp; M. A. Rotea, D. Kumar, E. J. Aju &amp; Y. Jin, <em>Multi-row extremum seeking for wind farm power maximization</em>, J. Phys. Conf. Ser. <strong>2767</strong> (2024) 032043. <a href="https://doi.org/10.1088/1742-6596/2767/3/032043">doi:10.1088/1742-6596/2767/3/032043</a></p>
<p><strong>[MGR24]</strong>&nbsp; S. P. Mulders, N. Gallo &amp; M. A. Rotea, <em>Analysis of extremum seeking control for wind turbine torque controller optimization by aerodynamic and generator power objectives</em>, ACC (2024). <a href="https://arxiv.org/abs/2407.08059">arXiv:2407.08059</a></p>
<p><strong>[GKN12]</strong>&nbsp; A. Ghaffari, M. Krstić &amp; D. Nešić, <em>Multivariable Newton-based extremum seeking</em>, Automatica <strong>48</strong> (2012) 1759–1767. <a href="https://doi.org/10.1016/j.automatica.2012.05.059">doi:10.1016/j.automatica.2012.05.059</a></p>
<p><strong>[S00]</strong>&nbsp; J. C. Spall, <em>Adaptive stochastic approximation by the simultaneous perturbation method</em>, IEEE Trans. Automat. Contr. <strong>45</strong> (2000) 1839–1853. <a href="https://www.jhuapl.edu/spsa/PDF-SPSA/Spall_TAC00.pdf">PDF</a></p>
<p><strong>[LM23]</strong>&nbsp; C. Lauand &amp; S. Meyn, <em>Quasi-stochastic approximation: design principles with applications to extremum seeking control</em>, IEEE Control Systems Magazine <strong>43</strong> (2023). <a href="https://doi.org/10.1109/MCS.2023.3291884">doi:10.1109/MCS.2023.3291884</a></p>
<p><strong>[A22]</strong>&nbsp; N. J. Abbas et al., <em>A reference open-source controller for fixed and floating offshore wind turbines</em>, Wind Energy Science <strong>7</strong> (2022) 53–73. <a href="https://doi.org/10.5194/wes-7-53-2022">doi:10.5194/wes-7-53-2022</a></p>
<p><strong>[J09]</strong>&nbsp; J. Jonkman, S. Butterfield, W. Musial &amp; G. Scott, <em>Definition of a 5-MW reference wind turbine</em>, NREL/TP-500-38060 (2009). <a href="https://www.nrel.gov/docs/fy09osti/38060.pdf">PDF</a> &nbsp;·&nbsp; <strong>[IEC]</strong>&nbsp; IEC 61400-1 ed.&nbsp;3, normal turbulence model.</p>
</div>
<div class="footnote">
<p>See also <a href="q4-matrix-gain.html">the matrix gain</a>.</p>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/Symplectomorphism\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Aykut C. Satici · Robot Control Lab · UT Dallas</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="mailto:aykut.satici@utdallas.edu">
<p>Email</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://github.com/symplectomorphism">
<p>GitHub</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../../positions/index.html">
<p>Opportunities</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>