<!DOCTYPE html>
<html lang="en"><head>
<link href="../../images/robot-arm-favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Aykut C. Satici">
  <title>Aykut C. Satici – Wind as a Stochastic Process</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-76a25e025fc5d71580f7ded5a7feac72.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Wind as a Stochastic Process – Aykut C. Satici">
<meta property="og:description" content="Aykut C. Satici, Associate Professor of Systems Engineering at UT Dallas. Robotics, nonlinear control, and machine learning.">
<meta property="og:image" content="https://Symplectomorphism.github.io/research/wind-esc/images/robot-control-lab-social.png">
<meta property="og:site_name" content="Aykut C. Satici">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Wind as a Stochastic Process</h1>
  <p class="subtitle">Where the gradient-estimate noise comes from, derived from the inflow spectrum rather than measured</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Aykut C. Satici
</div>
        <p class="quarto-title-affiliation">
            Robot Control Lab · Systems Engineering · UT Dallas
          </p>
    </div>
</div>

</section>
<section id="the-number-we-are-trying-to-compute" class="slide level2 smaller">
<h2>The number we are trying to compute</h2>
<p>Extremum seeking perturbs the torque gain and correlates the measured power against the perturbation. One period of that correlation returns one number, <span class="math inline">\(\hat g\)</span>, an estimate of the slope of the objective. <strong>Because the wind is random, <span class="math inline">\(\hat g\)</span> is random.</strong></p>
<p><span class="math display">\[\sigma(\hat g) := \text{standard deviation of one period's gradient estimate}\]</span></p>
<div class="claim">
<p><span class="math inline">\(\sigma(\hat g)\)</span> is the quantity this deck computes. Three design choices turn on it: the probe amplitude, how long to average, and how widely the gain scatters about its optimum once the adaptation has settled. Each of those dependences is <strong>derived</strong> in the closing section, once the machinery to do so exists.</p>
</div>
<div class="warn">
<p>Every value quoted for <span class="math inline">\(\sigma(\hat g)\)</span> so far has been <strong>measured</strong>: read off a simulation, or bounded from a published table. None was predicted from the turbulence.</p>
</div>
</section>
<section id="why-it-is-not-a-one-line-calculation" class="slide level2 smaller">
<h2>Why it is not a one-line calculation</h2>
<p><span class="math display">\[\hat g = \frac{1}{T}\int_0^T \ln P(t)\,\frac{2}{a}\sin\omega t\;dt\]</span></p>
<p><span class="math inline">\(P\)</span> depends on the wind, which is a <strong>random process</strong>, not a random number. So <span class="math inline">\(\hat g\)</span> is an integral of a random process against a deterministic weight, and its variance depends on how the wind’s randomness is distributed <strong>in time</strong>. A gust lasting an hour and a gust lasting a second contribute quite differently to the same integral.</p>
<div class="claim">
<p>Three things are therefore needed, and none of them is optional:</p>
<ol type="1">
<li>a way to describe <em>how a random process distributes its variance over timescales</em>: the spectral density;</li>
<li>a <em>model</em> of which spectrum turbulence actually has: Kaimal;</li>
<li>a rule for <em>pushing a process through a linear integral</em>: Wiener-Khinchin together with Fubini.</li>
</ol>
</div>
</section>
<section id="the-route" class="slide level2 smaller">
<h2>The route</h2>

<img data-src="assets/wind-roadmap.svg" class="fig-hero r-stretch" alt="Four boxes left to right with arrows between them. A: reduce the randomness, y minus its mean equals three epsilon, needs P, C_P and lambda. B: make it a linear functional, g-hat noise equals six over aT times Z, needs the estimator. C: variance of a linear functional, sigma squared Z from S and w-hat, needs Wiener-Khinchin. D: put in the measured frequency content of turbulence, a number. Below, a banner giving the goal."><div class="claim">
<p>Four links. <strong>A</strong> shows that although log-power depends on the wind three separate ways, at the optimum only one survives. <strong>B</strong> uses that to write the estimator’s noise as a single integral of one random process. <strong>C</strong> is the general rule for the variance of such an integral. <strong>D</strong> puts in the measured frequency content of atmospheric turbulence and produces a number. Each is stated, then checked against simulation at the end.</p>
</div>
</section>
<section>
<section id="link-a-reduce-the-randomness" class="title-slide slide level1 divider center">
<h1>Link A: reduce the randomness</h1>
<p>Log-power depends on the wind three separate ways. At the optimum only one of them survives, and that is what makes the rest tractable.</p>
</section>
<section id="what-we-need-from-the-turbine" class="slide level2 smaller">
<h2>What we need from the turbine</h2>
<p>A wind turbine below rated wind speed. Write <span class="math inline">\(\bar V\)</span> for the mean wind speed, <span class="math inline">\(R\)</span> for the rotor radius, <span class="math inline">\(\Omega\)</span> for the rotor angular speed, <span class="math inline">\(\rho\)</span> for air density and <span class="math inline">\(A = \pi R^2\)</span> for the swept area. Define the <strong>tip-speed ratio</strong> and the <strong>power coefficient</strong>:</p>
<p><span class="math display">\[\lambda := \frac{R\Omega}{V},
\qquad
P = \tfrac12\rho A V^3\,C_P(\lambda)\]</span></p>
<p><span class="math inline">\(C_P\)</span> is a property of the blades. For the rotor studied here it has a single maximum <span class="math inline">\(C_P^{\max}\)</span> at <span class="math inline">\(\lambda = \lambda^\star\)</span>; where that curve comes from, and what is physics versus measurement in it, is Appendix A.0b. The controller’s only actuator is the <strong>torque gain</strong> <span class="math inline">\(u\)</span> in the generator-torque law <span class="math inline">\(\tau_g = u\Omega^2\)</span>; setting <span class="math inline">\(\dot\Omega = 0\)</span> makes the rotor rest where <span class="math inline">\(C_P(\lambda)/\lambda^3 = c\,u\)</span> for a rotor constant <span class="math inline">\(c\)</span> (derived in Appendix A.0), so <span class="math inline">\(u\)</span> selects an equilibrium <span class="math inline">\(\lambda_{\text{eq}}(u)\)</span>.</p>
<div class="claim">
<p>Define the <strong>objective</strong> <span class="math inline">\(J(u) := \ln C_P\big(\lambda_{\text{eq}}(u)\big)\)</span>, and write <span class="math inline">\(J'\)</span>, <span class="math inline">\(J''\)</span> for its first two derivatives in <span class="math inline">\(u\)</span>. The optimum <span class="math inline">\(u^\star\)</span> is where <span class="math inline">\(J'(u^\star) = 0\)</span>, equivalently <span class="math inline">\(\lambda_{\text{eq}}(u^\star) =
\lambda^\star\)</span>. Numerically, for the NREL 5 MW rotor at <span class="math inline">\(\bar V = 8\)</span> m/s, <span class="math inline">\(J'' = -1.41\times10^{-13}\)</span> in SI units.</p>
</div>
</section>
<section id="the-decomposition" class="slide level2 smaller">
<h2>The decomposition</h2>
<p>Split the wind into a mean and a fluctuation about it:</p>
<p><span class="math display">\[V(t) = \bar V\big(1 + \varepsilon(t)\big),
\qquad
\varepsilon(t) := \frac{\tilde v(t)}{\bar V},
\qquad
\mathrm{TI} := \frac{\sigma_{\tilde v}}{\bar V} = \sigma_\varepsilon\]</span></p>
<p><span class="math inline">\(\tilde v\)</span> is the fluctuating part in m/s, <span class="math inline">\(\varepsilon\)</span> its dimensionless counterpart, and <span class="math inline">\(\mathrm{TI}\)</span> the <strong>turbulence intensity</strong>, <span class="math inline">\(0.10\)</span> in the case studied here. For a random variable <span class="math inline">\(x\)</span>, <span class="math inline">\(\sigma_x :=
\sqrt{\mathbb{E}[x^2] - (\mathbb{E}[x])^2}\)</span> is its <strong>standard deviation</strong>. For a process <span class="math inline">\(x(t)\)</span> it is evaluated at a fixed <span class="math inline">\(t\)</span>; the assumption that makes it independent of <span class="math inline">\(t\)</span> is stated on <em>Link A, executed</em>. Since <span class="math inline">\(\bar V :=
\mathbb{E}[V]\)</span>, both <span class="math inline">\(\tilde v\)</span> and <span class="math inline">\(\varepsilon\)</span> have mean zero, so <span class="math inline">\(\sigma_{\tilde v}^2 = \mathbb{E}[\tilde v^2]\)</span> and <span class="math inline">\(\sigma_\varepsilon^2 =
\mathbb{E}[\varepsilon^2]\)</span>.</p>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span>The standard form is additive, <span class="math inline">\(V = \bar V + \tilde v\)</span>, with the statistics written for <span class="math inline">\(\tilde v\)</span> <a href="#/references">[IEC]</a>. Dividing by the constant <span class="math inline">\(\bar V\)</span> gives the form above: <span class="math inline">\(\varepsilon = \tilde v/\bar V\)</span> and <span class="math inline">\(\sigma_\varepsilon = \sigma_{\tilde v}/\bar V = \mathrm{TI}\)</span>.</p>
</div>
<div class="cols2">
<div class="card">
<p><span class="cardh"><span class="math inline">\(\varepsilon\)</span> is small</span></p>
<p><span class="math inline">\(\sigma_\varepsilon = 0.10\)</span>, so a series in <span class="math inline">\(\varepsilon\)</span> converges quickly and second-order terms contribute about <span class="math inline">\(1\%\)</span>.</p>
</div>
<div class="card">
<p><span class="cardh"><span class="math inline">\(\varepsilon\)</span> is dimensionless</span></p>
<p>Every statistic of <span class="math inline">\(\varepsilon\)</span> is a pure number, <span class="math inline">\(\mathrm{TI}\)</span> among them. From here on the wind enters only through <span class="math inline">\(\varepsilon\)</span>, and <span class="math inline">\(\bar V\)</span> appears explicitly wherever it does.</p>
</div>
</div>
</section>
<section id="link-a-executed" class="slide level2 smaller">
<h2>Link A, executed</h2>
<p>From the definitions, <span class="math inline">\(y = \ln P = \ln(\tfrac12\rho A) + 3\ln V + \ln C_P(\lambda)\)</span>. Substituting <span class="math inline">\(V = \bar V(1+\varepsilon)\)</span> into the middle term, the logarithm of the product splits, and <span class="math inline">\(\ln(1+\varepsilon) = \varepsilon - \tfrac12\varepsilon^2 +
O(\varepsilon^3)\)</span> for <span class="math inline">\(|\varepsilon| &lt; 1\)</span>:</p>
<p><span class="math display">\[3\ln V = 3\ln\bar V + 3\ln(1+\varepsilon)
= \underbrace{3\ln\bar V}_{\text{constant}} + 3\varepsilon
\;\underbrace{-\;\tfrac32\varepsilon^2 + O(\varepsilon^3)}_{\text{second order}}\]</span></p>
<p>The second-order part has typical size <span class="math inline">\(\tfrac32\sigma_\varepsilon^2 = 0.015\)</span>, against <span class="math inline">\(3\sigma_\varepsilon = 0.30\)</span> for the linear term <span class="math inline">\(3\varepsilon\)</span>.</p>
<p>The third term, <span class="math inline">\(\ln C_P(\lambda)\)</span>, also depends on the wind, through <span class="math inline">\(\lambda = R\Omega/V\)</span>. Both wind-dependent terms are expanded under four standing assumptions, stated on the next slide; the third term is then handled on the slide after.</p>
</section>
<section id="link-a-standing-assumptions" class="slide level2 smaller">
<h2>Link A, standing assumptions</h2>
<p>In force through Links A and B.</p>
<ol type="1">
<li><strong>The gain is held fixed</strong>: <span class="math inline">\(u(t) = u\)</span> on the whole interval considered. The dither the estimator adds is treated on <em>Link A under the dither</em>.</li>
<li><strong><span class="math inline">\(\varepsilon\)</span> is strictly stationary</strong>: for every <span class="math inline">\(k\)</span>, every <span class="math inline">\(s_1,\dots,s_k\)</span> and every shift <span class="math inline">\(\tau\)</span>, the vector <span class="math inline">\((\varepsilon(s_1+\tau),\dots,\varepsilon(s_k+\tau))\)</span> has the same joint distribution as <span class="math inline">\((\varepsilon(s_1),\dots,\varepsilon(s_k))\)</span>.</li>
<li><strong><span class="math inline">\(\mathbb{E}[\cdot]\)</span> is the expectation with respect to that law.</strong> For fixed <span class="math inline">\(t\)</span>, <span class="math inline">\(\mathbb{E}[\lambda(t)]\)</span> averages the random variable <span class="math inline">\(\lambda(t)\)</span> over the distribution of the wind. It is a number.</li>
<li><strong>The rotor has forgotten its initial condition.</strong> Linearized about its equilibrium (A.0c), the rotor equation reads <span class="math inline">\(\dot{\delta\Omega} +
\delta\Omega/\tau_{\text{rotor}} = b\,\varepsilon(t)\)</span>, with <span class="math inline">\(\delta\Omega :=
\Omega - \Omega_{\text{eq}}\)</span>, <span class="math inline">\(\tau_{\text{rotor}} = 6.4\)</span> s at <span class="math inline">\(8\)</span> m/s, and <span class="math inline">\(b\)</span> a constant (both in A.0c). Its solution from <span class="math inline">\(t = 0\)</span> is <span class="math display">\[\delta\Omega(t) = e^{-t/\tau_{\text{rotor}}}\,\delta\Omega(0)
+ b\int_0^t e^{-(t-s)/\tau_{\text{rotor}}}\,\varepsilon(s)\,ds\]</span> The first term is deterministic and falls below <span class="math inline">\(1\%\)</span> of <span class="math inline">\(\delta\Omega(0)\)</span> after <span class="math inline">\(5\tau_{\text{rotor}} = 32\)</span> s. Assumption 4 is that this has happened, so <span class="math inline">\(\Omega(t)\)</span> is the second term alone: a causal, time-invariant functional of the wind path <span class="math inline">\(\{\varepsilon(s): s\le t\}\)</span>. The rotor still lags the wind; the lag is the exponential weight itself.</li>
</ol>
<div class="claim">
<p>Under 1 to 4, <span class="math inline">\(V(t) = \bar V(1+\varepsilon(t))\)</span>, <span class="math inline">\(\Omega(t)\)</span>, hence <span class="math inline">\(\lambda(t) = R\Omega(t)/V(t)\)</span> and <span class="math inline">\(y(t)\)</span>, are obtained from the wind path up to <span class="math inline">\(t\)</span> by rules that do not change with <span class="math inline">\(t\)</span>. Assumption 2 then gives each of them the same law at every <span class="math inline">\(t\)</span>, so <span class="math inline">\(\mathbb{E}[\lambda(t)]\)</span> and <span class="math inline">\(\mathbb{E}[y(t)]\)</span> are constants.</p>
</div>
</section>
<section id="link-a-executed-continued" class="slide level2 smaller">
<h2>Link A, executed, continued</h2>
<p>With <span class="math inline">\(u\)</span> fixed, <span class="math inline">\(\lambda(t)\)</span> fluctuates only because the wind does. Write <span class="math inline">\(\bar\lambda := \mathbb{E}[\lambda(t)]\)</span>, a constant by the previous slide, and <span class="math inline">\(\delta\lambda := \lambda - \bar\lambda\)</span>. Two limits of the rotor’s response bracket <span class="math inline">\(\delta\lambda\)</span>:</p>
<ul>
<li><strong>Frozen <span class="math inline">\(\Omega\)</span>.</strong> With <span class="math inline">\(\lambda_0 := R\Omega/\bar V\)</span> and <span class="math inline">\(1/(1+\varepsilon) = 1 - \varepsilon + O(\varepsilon^2)\)</span>, <span class="math display">\[\lambda = \frac{R\Omega}{\bar V(1+\varepsilon)} = \lambda_0\big(1 - \varepsilon + O(\varepsilon^2)\big),
\qquad \bar\lambda = \lambda_0\big(1 + O(\sigma_\varepsilon^2)\big),
\qquad \delta\lambda = -\bar\lambda\,\varepsilon + O(\varepsilon^2)\]</span></li>
<li><strong><span class="math inline">\(\Omega\)</span> tracking the equilibrium.</strong> <span class="math inline">\(\delta\lambda = 0\)</span>, since <span class="math inline">\(\lambda_{\text{eq}}(u)\)</span> depends on <span class="math inline">\(u\)</span> alone (A.0).</li>
</ul>
<p>In both, and in between, <span class="math inline">\(\delta\lambda = O(\varepsilon)\)</span>. Expanding about <span class="math inline">\(\bar\lambda\)</span>:</p>
<p><span class="math display">\[\ln C_P(\bar\lambda + \delta\lambda)
= \ln C_P(\bar\lambda)
+ \frac{C_P'(\bar\lambda)}{C_P(\bar\lambda)}\,\delta\lambda
+ O(\delta\lambda^2)\]</span></p>
<div class="claim">
<p>The next slide evaluates the two terms of this expansion at the optimum. Away from it, <span class="math inline">\(C_P'(\bar\lambda)\)</span> is a fixed nonzero number, <span class="math inline">\(\delta\lambda = O(\varepsilon)\)</span>, and their product, the linear term, is <span class="math inline">\(O(\varepsilon)\)</span>: a fluctuation of the same order as <span class="math inline">\(3\varepsilon\)</span>, with a coefficient set by how far off the gain sits.</p>
</div>
</section>
<section id="link-a-executed-concluded" class="slide level2 smaller">
<h2>Link A, executed, concluded</h2>
<p><strong>At the optimum</strong>, <span class="math inline">\(u = u^\star\)</span> (<em>What we need from the turbine</em>), so <span class="math inline">\(\lambda_{\text{eq}}(u) = \lambda^\star\)</span>, and <span class="math inline">\(d := \bar\lambda - \lambda^\star\)</span> is a number with <span class="math inline">\(d = O(\sigma_\varepsilon^2)\)</span> (A.0d). Three steps.</p>
<ol type="1">
<li><strong>The coefficient of the linear term.</strong> Taylor-expand <span class="math inline">\(C_P'\)</span> about <span class="math inline">\(\lambda^\star\)</span>, where <span class="math inline">\(C_P'(\lambda^\star) = 0\)</span> and <span class="math inline">\(C_P''(\lambda^\star) = -0.055\)</span> is a fixed number (A.0b curve): <span class="math display">\[C_P'(\bar\lambda) = C_P'(\lambda^\star) + C_P''(\lambda^\star)\,d + O(d^2)
= C_P''(\lambda^\star)\,d + O(\sigma_\varepsilon^4) = O(\sigma_\varepsilon^2)\]</span></li>
<li><strong>The linear term.</strong> <span class="math inline">\(\dfrac{C_P'(\bar\lambda)}{C_P(\bar\lambda)}\,\delta\lambda
= O(\sigma_\varepsilon^2)\cdot O(\varepsilon) = O(\sigma_\varepsilon^2\,\varepsilon)\)</span>.</li>
<li><strong>The Taylor remainder.</strong> <span class="math inline">\(O(\delta\lambda^2) = O(\varepsilon^2)\)</span>, because <span class="math inline">\(\delta\lambda = O(\varepsilon)\)</span> (previous slide).</li>
</ol>
<p>Collecting the three terms of <span class="math inline">\(y\)</span> from <em>Link A, executed</em>:</p>
<p><span class="math display">\[y = \underbrace{\ln(\tfrac12\rho A) + 3\ln\bar V + \ln C_P(\bar\lambda)}_{\text{constant}}
\;+\; 3\varepsilon(t) \;+\; r(t),
\qquad
r := -\tfrac32\varepsilon^2 + O(\varepsilon^3) + O(\sigma_\varepsilon^2\,\varepsilon) + O(\delta\lambda^2)\]</span></p>
<div class="claim">
<p><span class="math inline">\(\mathbb{E}[3\varepsilon] = 0\)</span>, so <span class="math inline">\(\mathbb{E}[y]\)</span> is the constant plus <span class="math inline">\(\mathbb{E}[r]\)</span>, and <span class="math display">\[y(t) - \mathbb{E}[y] = 3\varepsilon(t) + \big(r(t) - \mathbb{E}[r]\big)\]</span> Every piece of <span class="math inline">\(r\)</span> is a product of at least two factors of size <span class="math inline">\(\sigma_\varepsilon\)</span>, so <span class="math inline">\(\operatorname{sd}(r - \mathbb{E}r) = O(\sigma_\varepsilon^2)
\approx 0.01\)</span> against <span class="math inline">\(\operatorname{sd}(3\varepsilon) = 3\sigma_\varepsilon = 0.30\)</span>. This is what <span class="math inline">\(y - \mathbb{E}[y] = 3\varepsilon + O(\varepsilon^2)\)</span> means wherever it is quoted below: <strong>one term, one random process.</strong></p>
</div>
</section></section>
<section>
<section id="link-b-make-it-a-linear-functional" class="title-slide slide level1 divider center">
<h1>Link B: make it a linear functional</h1>
<p>Link A leaves a single random process. This writes the estimator’s noise as one integral of it.</p>
</section>
<section id="what-we-need-from-the-estimator" class="slide level2 smaller">
<h2>What we need from the estimator</h2>
<p>Extremum seeking perturbs the gain with a sinusoid of <strong>amplitude</strong> <span class="math inline">\(a\)</span> and <strong>period</strong> <span class="math inline">\(T\)</span>. Time is cut into dither periods <span class="math inline">\([nT,(n+1)T)\)</span>, <span class="math inline">\(n = 0,1,2,\dots\)</span>; <span class="math inline">\(u_n\)</span> is the gain about which the <span class="math inline">\(n\)</span>-th period dithers, and the measured log-power is correlated against the sinusoid over exactly that period (written below with the period’s own clock, <span class="math inline">\(t \in [0,T]\)</span>):</p>
<p><span class="math display">\[u(t) = u_n + a\sin\omega t,
\qquad
\omega := \frac{2\pi}{T},
\qquad
f_1 := \frac{1}{T} = \frac{\omega}{2\pi}\]</span></p>
<p><span class="math display">\[y(t) := \ln P(t),
\qquad
\hat g_n := \frac{1}{T}\int_0^T y(t)\,\frac{2}{a}\sin\omega t\;dt\]</span></p>
<p>Why that integral is a gradient estimate, and why the factor is <span class="math inline">\(2/a\)</span>, is Appendix A.1.</p>
<div class="claim">
<p><span class="math inline">\(\hat g_n\)</span> is an estimate of <span class="math inline">\(J'(u_n)\)</span>. Its <strong>mean</strong> error is the finite-amplitude bias <span class="math inline">\(\tfrac{a^2}{8}J'''\)</span>, derived on <em>The bias grows as <span class="math inline">\(a^2\)</span></em>; its <strong>scatter</strong>, which is what this deck computes, comes entirely from the wind. Published values for the NREL 5 MW case <a href="#/references">[CLR19]</a>: <span class="math inline">\(T = 150\)</span> s and <span class="math inline">\(a = 13.6\%\)</span> of <span class="math inline">\(u^\star\)</span>.</p>
</div>
<aside class="notes">
<p>Two conventions fixed here and used throughout. The correlation window is exactly one dither period, which matters in step three because it fixes the shape of the frequency window. And the demodulating signal is in phase with the dither, which is what makes the estimator pick out the first harmonic.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="link-b-executed" class="slide level2 smaller">
<h2>Link B, executed</h2>
<p>Write the log-power over one period as three parts. <span class="math inline">\(y_0(t)\)</span> is its value with <span class="math inline">\(\varepsilon \equiv 0\)</span>, a deterministic <span class="math inline">\(T\)</span>-periodic function of the dither; the wind adds <span class="math inline">\(3\varepsilon(t)\)</span> and the remainder <span class="math inline">\(r(t)\)</span> of <em>Link A, executed, concluded</em>:</p>
<p><span class="math display">\[y(t) = y_0(t) + 3\varepsilon(t) + r(t)\]</span></p>
<p>The estimator is linear in <span class="math inline">\(y\)</span>, so it splits the same way:</p>
<p><span class="math display">\[\hat g = \underbrace{\frac{2}{aT}\int_0^T y_0\sin\omega t\,dt}_{\hat g_{\text{det}}}
+ \underbrace{\frac{6}{aT}\int_0^T \varepsilon(t)\sin\omega t\,dt}_{\hat g_{\text{noise}}}
+ \underbrace{\frac{2}{aT}\int_0^T r\sin\omega t\,dt}_{\hat g_r}\]</span></p>
<p><span class="math inline">\(\hat g_{\text{det}}\)</span> is a number (its value is Appendix A.1). <span class="math inline">\(\hat g_r\)</span> is smaller than <span class="math inline">\(\hat g_{\text{noise}}\)</span> by the factor <span class="math inline">\(\operatorname{sd}(r)/\operatorname{sd}(3\varepsilon) = O(\sigma_\varepsilon)\)</span>; it is carried by the validation, which measures the total. This deck computes the scatter of the middle term:</p>
<p><span class="math display">\[\hat g_{\text{noise}} = \frac{6}{aT}\,Z,
\qquad
Z := \int_0^T \varepsilon(t)\,w(t)\,dt,
\qquad
w(t) := \begin{cases}\sin\omega t, &amp; 0\le t\le T\\ 0,&amp;\text{otherwise}\end{cases}\]</span></p>
</section>
<section id="link-b-executed-continued" class="slide level2 smaller">
<h2>Link B, executed, continued</h2>
<p><span class="math inline">\(Z\)</span> is a scalar random variable: the wind fluctuation over one period, weighted by the dither and integrated. Its mean is zero, because <span class="math inline">\(w\)</span> is deterministic and <span class="math inline">\(\mathbb{E}[\varepsilon(t)] = 0\)</span> at every <span class="math inline">\(t\)</span>:</p>
<p><span class="math display">\[\mathbb{E}[Z] = \int_0^T \mathbb{E}[\varepsilon(t)]\,w(t)\,dt = 0,
\qquad\text{so}\qquad
\operatorname{Var}(Z) = \mathbb{E}[Z^2]\]</span></p>
<p>Write <span class="math inline">\(Z^2\)</span> as a double integral and take the expectation inside:</p>
<p><span class="math display">\[\operatorname{Var}(Z)
= \mathbb{E}\!\left[\iint_{[0,T]^2}\! w(t)w(s)\,\varepsilon(t)\varepsilon(s)\,dt\,ds\right]
= \iint_{[0,T]^2}\! w(t)\,w(s)\,\underbrace{\mathbb{E}[\varepsilon(t)\varepsilon(s)]}_{=\;\Gamma(t-s)}\,dt\,ds\]</span></p>
<div class="claim">
<p>Exchanging <span class="math inline">\(\mathbb{E}\)</span> with the integral is <strong>Fubini’s theorem</strong>, and its condition holds: <span class="math inline">\(|\Gamma(\tau)| \le \Gamma(0) = \sigma_\varepsilon^2\)</span> (Cauchy-Schwarz, <span class="math inline">\(|\mathbb{E}[XY]| \le \sqrt{\mathbb{E}X^2\,\mathbb{E}Y^2}\)</span>), <span class="math inline">\(|w| \le 1\)</span>, and the domain has measure <span class="math inline">\(T^2\)</span>, so <span class="math inline">\(\mathbb{E}\iint|w\,w\,\varepsilon\varepsilon| \le \sigma_\varepsilon^2T^2 &lt; \infty\)</span>. <span class="math inline">\(\Gamma\)</span> is the autocovariance defined in Link C; Link B needs only that it exists.</p>
</div>
</section>
<section id="link-a-under-the-dither" class="slide level2 smaller">
<h2>Link A under the dither</h2>
<p>Link A held <span class="math inline">\(u\)</span> fixed; the estimator moves it, <span class="math inline">\(u = u_n + a\sin\omega t\)</span>. That moves <span class="math inline">\(\bar\lambda\)</span> by <span class="math inline">\(O(a)\)</span>. Differentiating the equilibrium relation of A.0 in the form <span class="math inline">\(\ln C_P(\lambda) - 3\ln\lambda = \ln c + \ln u\)</span> gives <span class="math inline">\((\lambda C_P'/C_P - 3)\,d\ln\lambda = d\ln u\)</span>, so at the peak</p>
<p><span class="math display">\[\frac{d\ln\lambda}{d\ln u} = -\frac13,
\qquad
\bar\lambda(t) = \lambda^\star\Big(1 - \frac{a}{3u^\star}\sin\omega t\Big) + O(a^2)\]</span></p>
<p>The linear term of the previous slide then returns as a cross term. With <span class="math inline">\(\kappa_2 := -\lambda^{\star 2}C_P''(\lambda^\star)/C_P(\lambda^\star) = 6.3\)</span> for the curve of A.0b, and <span class="math inline">\(\delta\lambda = -\bar\lambda\varepsilon\)</span> in the frozen-rotor limit,</p>
<p><span class="math display">\[\frac{C_P'(\bar\lambda)}{C_P(\bar\lambda)}\,\delta\lambda
= -\kappa_2\,\frac{a}{3u^\star}\,\varepsilon\sin\omega t + O(a^2\varepsilon),
\qquad
\Big|\frac{\kappa_2\,a/(3u^\star)}{3}\Big| = 0.10 \ \text{at}\ a = 0.136\,u^\star\]</span></p>
<div class="claim">
<p>The cross term is at most <span class="math inline">\(10\%\)</span> of <span class="math inline">\(3\varepsilon\)</span> in the frozen-rotor limit and zero when the rotor tracks. The validation section measures <span class="math inline">\(\operatorname{sd}(y)/\operatorname{sd}(3\varepsilon) = 1.037\)</span> with the dither on, which is the total of every term neglected here.</p>
</div>
</section></section>
<section>
<section id="link-c-the-variance-rule" class="title-slide slide level1 divider center">
<h1>Link C: the variance rule</h1>
<p>Link B leaves an integral of a random process against a fixed weight. This is the general rule for its variance, and it needs two definitions first.</p>
</section>
<section id="the-power-spectral-density" class="slide level2 smaller">
<h2>The power spectral density</h2>
<p><span class="math inline">\(\varepsilon\)</span> is strictly stationary (<em>Link A, executed</em>) with finite variance, hence <strong>wide-sense stationary</strong>: <span class="math inline">\(\mathbb{E}[\varepsilon(t)] = 0\)</span> for all <span class="math inline">\(t\)</span>, by construction of <span class="math inline">\(\varepsilon\)</span>, and <span class="math inline">\(\mathbb{E}[\varepsilon(t)\varepsilon(s)]\)</span> depends on <span class="math inline">\(t - s\)</span> alone. Define the <strong>autocovariance</strong> and, as its Fourier transform, the <strong>power spectral density</strong>; <span class="math inline">\(\Gamma\)</span> is even, since <span class="math inline">\(\Gamma(-\tau) = \mathbb{E}[\varepsilon(t)\varepsilon(t-\tau)] = \Gamma(\tau)\)</span> by stationarity (shift <span class="math inline">\(t\)</span> by <span class="math inline">\(\tau\)</span>):</p>
<p><span class="math display">\[\Gamma(\tau) := \mathbb{E}\big[\varepsilon(t)\,\varepsilon(t+\tau)\big],
\qquad
S^{2s}(f) := \int_{-\infty}^{\infty}\! \Gamma(\tau)e^{-i2\pi f\tau}d\tau,
\qquad
\Gamma(\tau) = \int_{-\infty}^{\infty}\! S^{2s}(f)e^{i2\pi f\tau}df\]</span></p>
<div class="claim">
<p>The pair is the <strong>Wiener-Khinchin theorem</strong>: for <span class="math inline">\(\Gamma \in L^1(\mathbb{R})\)</span> the transform <span class="math inline">\(S^{2s}\)</span> exists, is real, even and <strong>nonnegative</strong>, and the inversion formula holds. Setting <span class="math inline">\(\tau = 0\)</span> in the inversion gives <span class="math inline">\(\Gamma(0) = \sigma_\varepsilon^2 = \int S^{2s}df\)</span>: the variance is the integral of <span class="math inline">\(S^{2s}\)</span>, which is why it is called a density. How the variance is weighted across frequency by a given integral is exactly what Link C computes, with <span class="math inline">\(|\hat w|^2\)</span> as the weight.</p>
</div>
<aside class="notes">
<p>Links C and D use only wide-sense stationarity. Strict stationarity entered once, on Link A, to make the means of nonlinear functions of the path constant in time. Stationarity is defensible over the ten-minute scales the dither operates on and false over a day, which is a limit on the result rather than on the derivation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="two-conventions-and-a-factor-of-two" class="slide level2 smaller">
<h2>Two conventions, and a factor of two</h2>
<p><span class="math inline">\(\Gamma\)</span> is real and even, so <span class="math inline">\(S^{2s}\)</span> is real and even. Tables therefore fold the negative frequencies onto the positive ones and quote the <strong>one-sided</strong> density:</p>
<p><span class="math display">\[S(f) := 2\,S^{2s}(f)\quad (f&gt;0),
\qquad\text{so}\qquad
\sigma_\varepsilon^2 = \int_{-\infty}^{\infty}\!S^{2s}(f)\,df = \int_0^{\infty}\! S(f)\,df\]</span></p>
<div class="warn">
<p>Everything quoted from a standard is <strong>one-sided</strong>; every integral over all of <span class="math inline">\(\mathbb{R}\)</span> below needs <strong>two-sided</strong>. The conversion <span class="math inline">\(S^{2s} = \tfrac12 S\)</span> is applied once, explicitly, at the point of use.</p>
</div>
<p>Units follow from the definition: <span class="math inline">\(\varepsilon\)</span> is dimensionless, so <span class="math inline">\([\Gamma] = 1\)</span>, <span class="math inline">\([S] = \text{Hz}^{-1}\)</span>, and <span class="math inline">\(\int S\,df\)</span> is dimensionless as it must be.</p>
</section>
<section id="how-varepsilon-is-synthesized-and-its-distribution" class="slide level2 smaller">
<h2>How <span class="math inline">\(\varepsilon\)</span> is synthesized, and its distribution</h2>
<p>The validation section needs sample paths of <span class="math inline">\(\varepsilon\)</span> with a prescribed one-sided density <span class="math inline">\(S\)</span>. For a record of length <span class="math inline">\(D\)</span> sampled every <span class="math inline">\(\Delta t\)</span>:</p>
<ul>
<li><strong>Definition.</strong> <span class="math inline">\(N := D/(2\Delta t)\)</span> bins, <span class="math inline">\(f_k := k/D\)</span>, <span class="math inline">\(\Delta f := 1/D\)</span>, and <span class="math display">\[\varepsilon(t) := \sum_{k=1}^{N} A_k\cos(2\pi f_k t + \phi_k),
\qquad A_k := \sqrt{2\,S(f_k)\,\Delta f},
\qquad \phi_k \ \text{independent, uniform on } [0,2\pi)\]</span> In the runs here <span class="math inline">\(D = 36\,600\)</span> s, <span class="math inline">\(\Delta t = 0.5\)</span> s, <span class="math inline">\(N = 36\,600\)</span>.</li>
<li><strong>Mean.</strong> <span class="math inline">\(\mathbb{E}\cos(2\pi f_k t + \phi_k) = 0\)</span> for uniform <span class="math inline">\(\phi_k\)</span>, so <span class="math inline">\(\mathbb{E}[\varepsilon(t)] = 0\)</span>.</li>
<li><strong>Autocovariance.</strong> Independent phases remove every cross term, so <span class="math display">\[\Gamma(\tau) = \sum_{k=1}^{N} \tfrac12 A_k^2\cos(2\pi f_k\tau)
= \sum_{k=1}^{N} S(f_k)\cos(2\pi f_k\tau)\,\Delta f
\;\xrightarrow{\ \Delta f\to0\ }\; \int_0^\infty S(f)\cos(2\pi f\tau)\,df\]</span> the inversion on <em>The power spectral density</em> for real even <span class="math inline">\(\Gamma\)</span>. At <span class="math inline">\(\tau = 0\)</span>, <span class="math inline">\(\operatorname{Var}\varepsilon = \sum_k S(f_k)\Delta f \to \int_0^\infty S\,df = \sigma_\varepsilon^2\)</span>.</li>
</ul>
</section>
<section id="how-varepsilon-is-synthesized-continued" class="slide level2 smaller">
<h2>How <span class="math inline">\(\varepsilon\)</span> is synthesized, continued</h2>
<ul>
<li><strong>Strict stationarity.</strong> Shifting <span class="math inline">\(t\)</span> by <span class="math inline">\(\tau\)</span> shifts <span class="math inline">\(\phi_k\)</span> to <span class="math inline">\(\phi_k + 2\pi f_k\tau\)</span>; a uniform phase shifted modulo <span class="math inline">\(2\pi\)</span> is uniform, so the joint law of <span class="math inline">\((\phi_1,\dots,\phi_N)\)</span>, and with it of the whole path, is shift invariant. This is assumption 2 of <em>Link A, standing assumptions</em>.</li>
<li><strong>Distribution at fixed <span class="math inline">\(t\)</span>.</strong> <span class="math inline">\(\varepsilon(t)\)</span> is a sum of <span class="math inline">\(N\)</span> independent terms, each bounded by <span class="math inline">\(A_k\)</span> with variance <span class="math inline">\(\tfrac12 A_k^2\)</span>. As <span class="math inline">\(N \to \infty\)</span> with <span class="math inline">\(\max_k A_k \to 0\)</span>, the central limit theorem gives <span class="math inline">\(\varepsilon(t) \to \mathcal{N}(0,\sigma_\varepsilon^2)\)</span>. This matches IEC 61400-1, whose <strong>normal turbulence model</strong> takes the fluctuation at a fixed time to be Gaussian <a href="#/references">[IEC]</a>.</li>
</ul>
<div class="claim">
<p>Every result in this deck uses <span class="math inline">\(\varepsilon\)</span> through <span class="math inline">\(\mathbb{E}[\varepsilon] = 0\)</span>, <span class="math inline">\(\Gamma\)</span>, and <span class="math inline">\(\mathbb{E}[\varepsilon^4] &lt; \infty\)</span> only, so it holds for the synthesized process and for any other process with the same <span class="math inline">\(\Gamma\)</span>.</p>
</div>
</section>
<section id="link-c-executed" class="slide level2 smaller">
<h2>Link C, executed</h2>
<p>Define the window’s transform <span class="math inline">\(\hat w(f) := \int_0^T w(t)\,e^{-i2\pi ft}\,dt\)</span> (closed form in A.3). Substitute <span class="math inline">\(\Gamma(t-s) = \int_{\mathbb{R}} S^{2s}(f)\,e^{i2\pi f(t-s)}df\)</span> into Link B’s double integral and move the <span class="math inline">\(f\)</span>-integral outside:</p>
<p><span class="math display">\[\operatorname{Var}(Z)
= \int_{\mathbb{R}} S^{2s}(f)\,
\underbrace{\left[\int_0^T\! w(t)e^{i2\pi ft}dt\right]}_{=\;\overline{\hat w(f)}}
\underbrace{\left[\int_0^T\! w(s)e^{-i2\pi fs}ds\right]}_{=\;\hat w(f)}\;df
= \int_{\mathbb{R}} S^{2s}(f)\,|\hat w(f)|^2\,df\]</span></p>
<p>the first bracket being the complex conjugate of the second because <span class="math inline">\(w\)</span> is real.</p>
<div class="claim">
<p>The exchange is Fubini again, and its condition holds: <span class="math inline">\(\iiint |S^{2s}(f)w(t)w(s)|\,dt\,ds\,df \le \sigma_\varepsilon^2 T^2 &lt; \infty\)</span>, since <span class="math inline">\(S^{2s} \ge 0\)</span> and <span class="math inline">\(\int S^{2s} = \sigma_\varepsilon^2\)</span>. The result is an ordinary integral over <span class="math inline">\(f\)</span> of the deterministic function <span class="math inline">\(S^{2s}|\hat w|^2\)</span>: the spectrum, weighted by how much of each frequency the window lets through.</p>
</div>
<p>Parseval fixes the total weight of the window, which is used as a check below:</p>
<p><span class="math display">\[\int_{\mathbb{R}}|\hat w(f)|^2 df = \int_0^T \sin^2\!\omega t\,dt = \frac{T}{2}\]</span></p>
</section>
<section id="a-shortcut-that-does-not-apply-here" class="slide level2 smaller">
<h2>A shortcut that does not apply here</h2>

<img data-src="assets/wind-window.svg" class="fig-hero r-stretch" alt="The squared magnitude of the window transform against frequency in units of the dither frequency, overlaid on the Kaimal spectrum normalized at the dither frequency. The window's main lobe runs from zero to twice the dither frequency; across that range the spectrum falls by a factor of twelve."><p>If <span class="math inline">\(S^{2s}\)</span> were constant across the support of <span class="math inline">\(|\hat w|^2\)</span> it could be taken outside, and Parseval would finish the job:</p>
<p><span class="math display">\[\operatorname{Var}(Z) \;\approx\; S^{2s}(f_1)\int_{\mathbb{R}}|\hat w|^2df = S^{2s}(f_1)\,\frac{T}{2}
\;=\; S_\varepsilon(f_1)\,\frac{T}{4}
\qquad\text{(valid iff } S \text{ is flat over the lobe)}\]</span></p>
<div class="warn">
<p><strong>The condition fails here.</strong> <span class="math inline">\(w\)</span> is one period of a sine, so <span class="math inline">\(|\hat w|^2\)</span> has its main lobe on <span class="math inline">\([0, 2f_1]\)</span>, a <span class="math inline">\(100\%\)</span> relative bandwidth, and across that interval <span class="math inline">\(S_\varepsilon\)</span> falls by a factor of <span class="math inline">\(S_\varepsilon(0)/S_\varepsilon(2f_1) = 11.8\)</span> at <span class="math inline">\(T = 150\)</span> s.</p>
</div>
</section></section>
<section>
<section id="link-d-the-spectrum-turbulence-has" class="title-slide slide level1 divider center">
<h1>Link D: the spectrum turbulence has</h1>
<p>Link C’s rule needs a spectrum. This is the one measured for the atmospheric boundary layer, and substituting it finishes the calculation.</p>
</section>
<section id="the-integral-length-scale" class="slide level2 smaller">
<h2>The integral length scale</h2>
<p>One more definition before the model, because it is the only free parameter in it. The <strong>normalized autocovariance</strong> and the <strong>integral time and length scales</strong> are</p>
<p><span class="math display">\[\varrho(\tau) := \frac{\Gamma(\tau)}{\Gamma(0)},
\qquad
\mathcal{T} := \int_0^{\infty}\!\varrho(\tau)\,d\tau,
\qquad
L := \bar V\,\mathcal{T}\]</span></p>
<p><span class="math inline">\(\mathcal{T}\)</span> is the lag over which the signal retains memory of itself, and <span class="math inline">\(L = \bar V\mathcal{T}\)</span> converts it to a length by Taylor’s frozen-turbulence hypothesis: eddies of size <span class="math inline">\(L\)</span> are carried past the rotor at speed <span class="math inline">\(\bar V\)</span>.</p>
<div class="claim">
<p><span class="math inline">\(L\)</span> is fixed by the spectrum at zero frequency. Since <span class="math inline">\(\Gamma\)</span> is real and even, <span class="math inline">\(e^{-i2\pi f\tau} = \cos 2\pi f\tau - i\sin 2\pi f\tau\)</span> contributes only its cosine, and the two half-lines contribute equally: <span class="math inline">\(S(f) = 2S^{2s}(f) = 2\int_{\mathbb{R}}\Gamma(\tau)\cos(2\pi f\tau)\,d\tau
= 4\int_0^\infty\Gamma(\tau)\cos(2\pi f\tau)\,d\tau\)</span>. Hence <span class="math display">\[S(0) = 4\int_0^{\infty}\! \Gamma(\tau)\,d\tau = 4\sigma_\varepsilon^2\mathcal{T} = \frac{4L}{\bar V}\,\sigma_\varepsilon^2\]</span> so <strong>any</strong> spectrum with integral scale <span class="math inline">\(L\)</span> must have that value at <span class="math inline">\(f = 0\)</span>. That is where the prefactor in the next slide comes from.</p>
</div>
</section>
<section id="the-kaimal-spectrum" class="slide level2 smaller">
<h2>The Kaimal spectrum</h2>
<p>A specific one-parameter model for <span class="math inline">\(S\)</span>, fitted by Kaimal, Wyngaard, Izumi and Coté <a href="#/references">[KWIC72]</a> to the 1968 Kansas boundary-layer measurements and adopted by IEC 61400-1 <a href="#/references">[IEC]</a> as its normal turbulence model. In terms of <span class="math inline">\(\varepsilon\)</span>:</p>
<p><span class="math display">\[\boxed{\;S_\varepsilon(f) = \mathrm{TI}^2\;\frac{4L/\bar V}{\big(1+6fL/\bar V\big)^{5/3}}\;}
\qquad f \ge 0,\ \text{one-sided}\]</span></p>
<p>Every piece is forced or measured, none is free:</p>
<div class="cols3">
<div class="card">
<p><span class="cardh"><span class="math inline">\(4L/\bar V\)</span></span></p>
<p>The value at <span class="math inline">\(f = 0\)</span> that the previous slide requires of any spectrum with integral scale <span class="math inline">\(L\)</span>.</p>
</div>
<div class="card">
<p><span class="cardh">exponent <span class="math inline">\(5/3\)</span></span></p>
<p>Kolmogorov’s inertial-subrange law, <span class="math inline">\(S\propto f^{-5/3}\)</span>, which the data follow above the corner.</p>
</div>
<div class="card">
<p><span class="cardh">the <span class="math inline">\(6\)</span></span></p>
<p>The one empirical number: it places the corner, at <span class="math inline">\(f = \bar V/6L\)</span>.</p>
</div>
</div>
<div class="claim">
<p>It is correctly normalized: substituting <span class="math inline">\(x = 6fL/\bar V\)</span>, <span class="math inline">\(\int_0^{\infty}\! S_\varepsilon df = \tfrac{2}{3}\int_0^\infty (1+x)^{-5/3}dx
= \tfrac23\cdot\tfrac32\,\mathrm{TI}^2 = \mathrm{TI}^2\)</span>, as the definition of <span class="math inline">\(\mathrm{TI}\)</span> demands.</p>
</div>
</section>
<section id="what-it-looks-like-and-where-the-dither-sits" class="slide level2 smaller">
<h2>What it looks like, and where the dither sits</h2>

<img data-src="assets/wind-kaimal.svg" class="fig-hero r-stretch" alt="Two panels. Left, the Kaimal one-sided density on log-log axes: flat below a corner frequency, then falling as f to the minus five thirds, with the 150 and 600 second dither frequencies marked on it. Right, f times S against log frequency, a single broad peak at U over 4L, showing where the variance actually accumulates."><p><a href="#/references">[IEC]</a> fixes <span class="math inline">\(L\)</span> from the hub height <span class="math inline">\(z\)</span> alone: <span class="math inline">\(L = 8.1\Lambda_1\)</span> with <span class="math inline">\(\Lambda_1 = 0.7\min(z,60)\)</span> m. For the NREL 5 MW rotor, <span class="math inline">\(z = 90\)</span> m gives <span class="math inline">\(\Lambda_1 = 42\)</span> m and <span class="math inline">\(L = 340\)</span> m.</p>
<div class="claim">
<p>At <span class="math inline">\(\bar V = 8\)</span> m/s that puts the corner at <span class="math inline">\(\bar V/6L = 3.9\times10^{-3}\)</span> Hz. The right panel plots <span class="math inline">\(fS_\varepsilon\)</span> against <span class="math inline">\(\ln f\)</span>, whose area is the variance (<span class="math inline">\(S\,df = fS\,d\ln f\)</span>); it peaks at <span class="math inline">\(\bar V/4L = 5.9\times10^{-3}\)</span> Hz (both shown in A.7). <strong>The published dither, <span class="math inline">\(f_1 = 1/150\,\text{s} = 6.7\times10^{-3}\)</span> Hz, sits directly on that peak.</strong> The last part of this deck returns to that.</p>
</div>
</section>
<section id="the-answer-and-what-the-shortcut-would-have-cost" class="slide level2 smaller">
<h2>The answer, and what the shortcut would have cost</h2>
<p>Evaluating the exact integral numerically against the shortcut, and both against a direct simulation of the turbine under a synthesized Kaimal inflow:</p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(T\)</span></th>
<th>exact <span class="math inline">\(\operatorname{Var}(Z)\)</span></th>
<th>shortcut</th>
<th><span class="math inline">\(\sigma(\hat g)\)</span> exact</th>
<th>shortcut</th>
<th>simulated</th>
<th>exact/sim</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(150\)</span> s</td>
<td><span class="math inline">\(15.65\)</span></td>
<td><span class="math inline">\(12.18\)</span></td>
<td><span class="math inline">\(5.21{\times}10^{-7}\)</span></td>
<td><span class="math inline">\(4.59{\times}10^{-7}\)</span></td>
<td><span class="math inline">\(5.48{\times}10^{-7}\)</span></td>
<td><span class="math inline">\(0.95\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(300\)</span> s</td>
<td><span class="math inline">\(53.08\)</span></td>
<td><span class="math inline">\(45.73\)</span></td>
<td><span class="math inline">\(4.80{\times}10^{-7}\)</span></td>
<td><span class="math inline">\(4.45{\times}10^{-7}\)</span></td>
<td><span class="math inline">\(5.09{\times}10^{-7}\)</span></td>
<td><span class="math inline">\(0.94\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(600\)</span> s</td>
<td><span class="math inline">\(152.9\)</span></td>
<td><span class="math inline">\(141.3\)</span></td>
<td><span class="math inline">\(4.07{\times}10^{-7}\)</span></td>
<td><span class="math inline">\(3.91{\times}10^{-7}\)</span></td>
<td><span class="math inline">\(3.83{\times}10^{-7}\)</span></td>
<td><span class="math inline">\(1.06\)</span></td>
</tr>
</tbody>
</table>
<div class="claim">
<p><span class="math display">\[\boxed{\;\sigma(\hat g) = \frac{6}{aT}\sqrt{\int_{\mathbb{R}}\tfrac12 S_\varepsilon(f)\,|\hat w(f)|^2\,df}\;}\]</span> Agreement with simulation is within <span class="math inline">\(\mathbf{6\%}\)</span> across a fourfold range of <span class="math inline">\(T\)</span>, with no fitted parameter. The shortcut under-predicts by <span class="math inline">\(11\)</span> to <span class="math inline">\(13\%\)</span>, because it samples <span class="math inline">\(S\)</span> at <span class="math inline">\(f_1\)</span> while the window also collects the larger <span class="math inline">\(S\)</span> below <span class="math inline">\(f_1\)</span>.</p>
</div>
</section></section>
<section>
<section id="does-it-hold" class="title-slide slide level1 divider center">
<h1>Does it hold?</h1>
<p>Each link checked separately against a simulation of the full nonlinear turbine, so a failure can be attributed to one link rather than to the chain.</p>
</section>
<section id="how-the-check-is-set-up" class="slide level2 smaller">
<h2>How the check is set up</h2>
<p>The turbine is integrated with an adaptive solver under a synthesized Kaimal inflow (<em>How <span class="math inline">\(\varepsilon\)</span> is synthesized</em>), <span class="math inline">\(240\)</span> periods of <span class="math inline">\(T = 150\)</span> s at <span class="math inline">\(\bar V = 8\)</span> m/s, realized <span class="math inline">\(\mathrm{TI} = 9.86\%\)</span>. The gain is held at <span class="math inline">\(u^\star\)</span>, with no adaptation between periods, so what is measured is the estimator alone.</p>
<div class="cols3">
<div class="card">
<p><span class="cardh">testing A</span></p>
<p>Record <span class="math inline">\(y(t)\)</span> and the <span class="math inline">\(\varepsilon(t)\)</span> that drove it. Regress one on the other: the slope should be <span class="math inline">\(3\)</span>.</p>
</div>
<div class="card">
<p><span class="cardh">testing C</span></p>
<p>Form <span class="math inline">\(Z = \int\varepsilon w\,dt\)</span> each period, take its sample variance, compare with <span class="math inline">\(\int S^{2s}|\hat w|^2 df\)</span>.</p>
</div>
<div class="card">
<p><span class="cardh">testing D</span></p>
<p>Take the sample standard deviation of <span class="math inline">\(\hat g\)</span> itself and compare with <span class="math inline">\(\tfrac{6}{aT}\sqrt{\operatorname{Var}Z}\)</span>.</p>
</div>
</div>
<div class="claim">
<p>Link B is algebra given A: <span class="math inline">\(\hat g_{\text{noise}} = \tfrac{6}{aT}Z\)</span> follows from <span class="math inline">\(y = y_0 + 3\varepsilon + r\)</span> by linearity of the estimator, so it is tested through D, which compares the scatter of <span class="math inline">\(\hat g\)</span> itself with the prediction.</p>
</div>
</section>
<section id="every-link-holds" class="slide level2 smaller">
<h2>Every link holds</h2>

<img data-src="assets/wind-validate.svg" class="fig-hero r-stretch" alt="Left, a scatter of the log-power fluctuation against three times the wind fluctuation, with the predicted unit-slope line and a fitted line of slope 3.08 lying almost on top of each other, correlation 0.9915. Right, three bars giving measured over predicted for links A, C and D: 1.037, 0.959 and 1.005, all inside a shaded five per cent band."><table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>link</th>
<th>claim</th>
<th>predicted</th>
<th>measured</th>
<th>ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>A</strong></td>
<td><span class="math inline">\(y-\bar y = 3\varepsilon\)</span></td>
<td>slope <span class="math inline">\(3\)</span></td>
<td>slope <span class="math inline">\(3.083\)</span>, <span class="math inline">\(r = 0.9915\)</span></td>
<td><span class="math inline">\(1.037\)</span></td>
</tr>
<tr class="even">
<td><strong>C</strong></td>
<td><span class="math inline">\(\operatorname{Var}Z = \int S^{2s}\vert\hat w\vert^2 df\)</span></td>
<td><span class="math inline">\(15.65\)</span></td>
<td><span class="math inline">\(15.01\)</span></td>
<td><span class="math inline">\(0.959\)</span></td>
</tr>
<tr class="odd">
<td><strong>D</strong></td>
<td><span class="math inline">\(\sigma(\hat g) = \tfrac{6}{aT}\sqrt{\operatorname{Var}Z}\)</span></td>
<td><span class="math inline">\(5.21{\times}10^{-7}\)</span></td>
<td><span class="math inline">\(5.23{\times}10^{-7}\)</span></td>
<td><span class="math inline">\(1.005\)</span></td>
</tr>
</tbody>
</table>
<div class="claim">
<p>All three within <span class="math inline">\(5\%\)</span>, and the assembled prediction within <span class="math inline">\(0.5\%\)</span>. The <span class="math inline">\(3.7\%\)</span> excess on A has two parts, both predicted on <em>Link A, executed, concluded</em>. The slope exceeds <span class="math inline">\(3\)</span> by <span class="math inline">\(2.8\%\)</span>: a term linear in <span class="math inline">\(\varepsilon\)</span>, which is the <span class="math inline">\(O(\sigma_\varepsilon^2\varepsilon)\)</span> term, <span class="math inline">\(\kappa_2\sigma_\varepsilon^2\varepsilon
= 0.063\,\varepsilon\)</span> in the frozen-rotor limit (slope <span class="math inline">\(3.06\)</span>) and <span class="math inline">\(0\)</span> if the rotor tracks. The rest is the remainder uncorrelated with <span class="math inline">\(\varepsilon\)</span>: <span class="math inline">\(r =
0.9915\)</span> means a residual of <span class="math inline">\(\sqrt{1-r^2} = 13\%\)</span> of <span class="math inline">\(\operatorname{sd}(y)\)</span>, adding in quadrature, <span class="math inline">\(\sqrt{1.028^2 + 0.13^2} = 1.037\)</span>. Its predicted size, from <span class="math inline">\(-\tfrac32\varepsilon^2\)</span> and <span class="math inline">\(\tfrac{C_P''}{2C_P}\delta\lambda^2 =
-\tfrac{\kappa_2}{2}(\delta\lambda/\lambda)^2\)</span>, is between <span class="math inline">\(7\%\)</span> (tracking) and <span class="math inline">\(22\%\)</span> (frozen) of <span class="math inline">\(\operatorname{sd}(3\varepsilon)\)</span>.</p>
</div>
</section></section>
<section>
<section id="what-it-decides" class="title-slide slide level1 divider center">
<h1>What it decides</h1>
<p>With <span class="math inline">\(\sigma(\hat g)\)</span> in hand, the three design dependences can be derived. Each uses only what the four links established.</p>
</section>
<section id="bias-and-standard-deviation-the-definitions" class="slide level2 smaller">
<h2>Bias and standard deviation: the definitions</h2>
<p>Link A gave <span class="math inline">\(y - \bar y = 3\varepsilon + O(\varepsilon^2)\)</span> at the optimum, and Link B gave <span class="math inline">\(\hat g_{\text{noise}} = \tfrac{6}{aT}Z\)</span>. So the estimator splits into a part that would be present with no wind and a part the wind adds:</p>
<p><span class="math display">\[\hat g = \underbrace{\frac{2}{aT}\int_0^T J\big(u + a\sin\omega t\big)\sin\omega t\,dt}_{\hat g_{\text{det}},\ \text{deterministic}}
\;+\; \underbrace{\frac{6}{aT}Z}_{\hat g_{\text{noise}},\ \text{random}}\]</span></p>
<p><span class="math display">\[\operatorname{Bias}(\hat g) := \mathbb{E}[\hat g] - J'(u),
\qquad
\sigma(\hat g) := \sqrt{\operatorname{Var}(\hat g)}
= \sqrt{\mathbb{E}\big[(\hat g - \mathbb{E}\hat g)^2\big]}\]</span></p>
<div class="claim">
<p><span class="math inline">\(\hat g_{\text{det}}\)</span> is a number, and <span class="math inline">\(\mathbb{E}[Z] = \int_0^T\mathbb{E}[\varepsilon]\,w\,dt = 0\)</span> because <span class="math inline">\(\varepsilon\)</span> is zero-mean. So the two quantities <strong>separate</strong>: <span class="math display">\[\operatorname{Bias}(\hat g) = \hat g_{\text{det}} - J'(u),
\qquad
\operatorname{Var}(\hat g) = \Big(\frac{6}{aT}\Big)^2\operatorname{Var}(Z)\]</span> The bias comes only from the probe; the scatter comes only from the wind.</p>
</div>
</section>
<section id="the-bias-grows-as-a2" class="slide level2 smaller">
<h2>The bias grows as <span class="math inline">\(a^2\)</span></h2>
<p>Assume <span class="math inline">\(J\)</span> is four times differentiable near <span class="math inline">\(u\)</span> and <span class="math inline">\(a\)</span> is small enough for the Taylor series to be used. Write <span class="math inline">\(s := \sin\omega t\)</span> and <span class="math inline">\(\langle\cdot\rangle := \tfrac1T\int_0^T(\cdot)\,dt\)</span>. The moments of a sine over a whole period are</p>
<p><span class="math display">\[\langle s\rangle = 0,\qquad \langle s^2\rangle = \tfrac12,\qquad
\langle s^3\rangle = 0,\qquad \langle s^4\rangle = \tfrac38,\qquad
\langle s^5\rangle = 0\]</span></p>
<p>Expand <span class="math inline">\(J(u + as) = J + J'as + \tfrac{J''}{2}a^2s^2 + \tfrac{J'''}{6}a^3s^3 +
O(a^4)\)</span> and multiply by <span class="math inline">\(\tfrac{2}{a}s\)</span> before averaging:</p>
<p><span class="math display">\[\hat g_{\text{det}} = \frac2a\Big[J\langle s\rangle + J'a\langle s^2\rangle
+ \tfrac{J''}{2}a^2\langle s^3\rangle + \tfrac{J'''}{6}a^3\langle s^4\rangle\Big] + O(a^4)
= J' + \frac{a^2}{8}J''' + O(a^4)\]</span></p>
<div class="claim">
<p><span class="math display">\[\operatorname{Bias}(\hat g) = \frac{a^2}{8}\,J'''(u) + O(a^4)\]</span> Every even power of <span class="math inline">\(a\)</span> is killed by an odd moment of <span class="math inline">\(s\)</span>, which is why the leading term is <span class="math inline">\(a^2\)</span> and not <span class="math inline">\(a\)</span>. Checked numerically on a cubic <span class="math inline">\(J\)</span>, where <span class="math inline">\(J'''\)</span> is exact: agreement to six digits at <span class="math inline">\(a = 0.02\)</span>, <span class="math inline">\(0.05\)</span>, <span class="math inline">\(0.10\)</span>.</p>
</div>
<div class="warn">
<p>The <span class="math inline">\(\tfrac18\)</span> is specific to a sinusoidal dither, through <span class="math inline">\(\langle s^4\rangle = \tfrac38\)</span>. A square-wave dither gives <span class="math inline">\(\tfrac16\)</span>.</p>
</div>
</section>
<section id="the-standard-deviation-falls-as-1a" class="slide level2 smaller">
<h2>The standard deviation falls as <span class="math inline">\(1/a\)</span></h2>
<p>From the separation, <span class="math inline">\(\operatorname{Var}(\hat g) = (6/aT)^2\operatorname{Var}(Z)\)</span> with <span class="math inline">\(Z = \int_0^T\varepsilon\sin\omega t\,dt\)</span>.</p>
<div class="claim">
<p><span class="math inline">\(Z\)</span> is built from the wind fluctuation and the fixed weight <span class="math inline">\(\sin\omega t\)</span> on <span class="math inline">\([0,T]\)</span>. <strong>The amplitude <span class="math inline">\(a\)</span> does not appear in it.</strong> Therefore <span class="math display">\[\sigma(\hat g) = \frac{6}{aT}\sqrt{\operatorname{Var}(Z)} \;\propto\; \frac1a\]</span> exactly for <span class="math inline">\(\hat g_{\text{noise}}\)</span>. The full scatter also carries <span class="math inline">\(\hat g_r\)</span> from the remainder <span class="math inline">\(r\)</span> of <em>Link A, executed, concluded</em>, with <span class="math inline">\(\operatorname{sd}(r -
\mathbb{E}r) = O(\sigma_\varepsilon^2)\)</span>; the validation measures both together.</p>
</div>
<p>Why <span class="math inline">\(1/a\)</span>: the wind’s contribution to log-power is <span class="math inline">\(3\varepsilon(t)\)</span> whatever the gain does, and the estimator divides by <span class="math inline">\(a\)</span> to turn a power change into a slope. A fixed disturbance divided by a smaller number is a larger result.</p>
<div class="warn">
<p>The two scalings pull opposite ways. Bias wants <span class="math inline">\(a\)</span> small; scatter wants <span class="math inline">\(a\)</span> large. Balancing them needs the constant in the second relation, which is what Links C and D supplied.</p>
</div>
</section>
<section id="averaging-over-n-periods" class="slide level2 smaller">
<h2>Averaging over <span class="math inline">\(N\)</span> periods</h2>
<p>Average <span class="math inline">\(N\)</span> consecutive estimates, <span class="math inline">\(\bar{\hat g}_N := \tfrac1N\sum_{n=1}^N \hat g_n\)</span>. Each has the same variance <span class="math inline">\(\sigma^2 := \operatorname{Var}(\hat g)\)</span>; if they were independent, <span class="math inline">\(\operatorname{Var}(\bar{\hat g}_N) = \sigma^2/N\)</span>. They are not quite, because the same wind spans adjacent periods. The exact statement uses the correlation between estimates <span class="math inline">\(k\)</span> periods apart, which Link C also gives with the window shifted by <span class="math inline">\(kT\)</span> (derived in A.8), and the variance of a mean of correlated samples (derived in A.9):</p>
<p><span class="math display">\[\rho_k := \frac{\operatorname{Cov}(Z_0,Z_k)}{\operatorname{Var}(Z)}
= \frac{\int S^{2s}(f)\,|\hat w(f)|^2\cos(2\pi fkT)\,df}{\int S^{2s}(f)\,|\hat w(f)|^2\,df},
\qquad
\operatorname{Var}(\bar{\hat g}_N) = \frac{\sigma^2}{N}\Big[1 + 2\sum_{k=1}^{N-1}\big(1-\tfrac kN\big)\rho_k\Big]\]</span></p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(T\)</span></th>
<th><span class="math inline">\(\rho_1\)</span></th>
<th><span class="math inline">\(\rho_2\)</span></th>
<th>sd reduction at <span class="math inline">\(N=3\)</span></th>
<th>at <span class="math inline">\(N=8\)</span></th>
<th>at <span class="math inline">\(N=24\)</span></th>
<th>if independent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(150\)</span> s</td>
<td><span class="math inline">\(-0.099\)</span></td>
<td><span class="math inline">\(-0.008\)</span></td>
<td><span class="math inline">\(1.87\times\)</span></td>
<td><span class="math inline">\(3.14\times\)</span></td>
<td><span class="math inline">\(5.51\times\)</span></td>
<td><span class="math inline">\(1.73\)</span>, <span class="math inline">\(2.83\)</span>, <span class="math inline">\(4.90\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(600\)</span> s</td>
<td><span class="math inline">\(-0.036\)</span></td>
<td><span class="math inline">\(-0.001\)</span></td>
<td><span class="math inline">\(1.78\times\)</span></td>
<td><span class="math inline">\(2.93\times\)</span></td>
<td><span class="math inline">\(5.09\times\)</span></td>
<td>same</td>
</tr>
</tbody>
</table>
<div class="claim">
<p>Adjacent estimates are <strong>slightly negatively correlated</strong>, because the half-window that ends one period begins the next with the opposite sign, so averaging does a little <em>better</em> than <span class="math inline">\(\sqrt N\)</span>. Measured lag-1 correlation of <span class="math inline">\(\hat g\)</span> over <span class="math inline">\(300\)</span> simulated periods at <span class="math inline">\(T = 600\)</span> s: <span class="math inline">\(-0.024\)</span>, against the predicted <span class="math inline">\(-0.036\)</span>.</p>
</div>
</section>
<section id="the-terminal-error-of-the-closed-loop" class="slide level2 smaller">
<h2>The terminal error of the closed loop</h2>
<p>Close the loop with a constant gain <span class="math inline">\(\kappa &gt; 0\)</span>, <span class="math inline">\(u_{n+1} = u_n + \kappa\hat g_n\)</span> (a step up the gradient). Near the optimum <span class="math inline">\(J'(u_n) = J''\,\tilde u_n +
O(\tilde u_n^2)\)</span> with <span class="math inline">\(\tilde u_n := u_n - u^\star\)</span>, and <span class="math inline">\(\hat g_n = J'(u_n) +
\tfrac{a^2}{8}J''' + \hat g_{\text{noise},n}\)</span> by the bias and noise results. The bias is a constant: it shifts the fixed point to <span class="math inline">\(\tilde u = -a^2J'''/(8J'')\)</span> and leaves the variance unchanged, so it is dropped here. Then, since <span class="math inline">\(J'' &lt; 0\)</span>:</p>
<p><span class="math display">\[\tilde u_{n+1} = (1-K)\,\tilde u_n + \kappa\,\hat g_{\text{noise},n},
\qquad K := \kappa|J''|\]</span></p>
<p>a first-order autoregression. Its stationary variance, taking the noise uncorrelated across periods (the <span class="math inline">\(\rho_k\)</span> above are small):</p>
<p><span class="math display">\[\operatorname{Var}(\tilde u) = \frac{\kappa^2\sigma^2(\hat g)}{1-(1-K)^2}
= \frac{K}{2-K}\cdot\frac{\sigma^2(\hat g)}{J''^2}
\qquad\Longrightarrow\qquad
\sigma(\tilde u) = \sqrt{\frac{K}{2-K}}\;\frac{\sigma(\hat g)}{|J''|}\]</span></p>
<div class="claim">
<p>This is the sense in which the terminal error is “<span class="math inline">\(\sigma(\hat g)\)</span> divided by the curvature”: the ratio <span class="math inline">\(\sigma(\hat g)/|J''|\)</span>, scaled by a factor that depends only on the loop gain <span class="math inline">\(K\)</span>. It is a <strong>stationary distribution</strong>: running longer leaves its width unchanged.</p>
</div>
<div class="warn">
<p>Checked in closed loop at <span class="math inline">\(K = 0.015\)</span>, <span class="math inline">\(T = 600\)</span> s: predicted <span class="math inline">\(\sigma(\tilde u) = 0.106\,u^\star\)</span>, measured <span class="math inline">\(0.082\)</span>, ratio <span class="math inline">\(0.777\)</span>. That shortfall is the record, not the formula: with <span class="math inline">\(\alpha = 1-K = 0.985\)</span> the loop’s correlation time is <span class="math inline">\(67\)</span> periods, the run’s <span class="math inline">\(270\)</span> post-transient samples span only four of them, and the sample variance of such a series is biased low by an expected factor of <span class="math inline">\(0.79\)</span> in standard deviation (Appendix A.6). Prediction and measurement agree once that is accounted for.</p>
</div>
</section></section>
<section>
<section id="consequences" class="title-slide slide level1 divider center">
<h1>Consequences</h1>
<p>One design rule, and one discrepancy the derivation does not remove.</p>
</section>
<section id="the-dither-period-has-a-worst-case" class="slide level2 smaller">
<h2>The dither period has a worst case</h2>

<img data-src="assets/sim-period.svg" class="fig-hero r-stretch" alt="Gradient noise and second-harmonic curvature bias against dither period on a logarithmic axis. Noise rises to a broad maximum near 110 seconds and falls slowly for longer periods; the curvature bias rises from minus fifty per cent toward zero as the period lengthens. The published 150 second period sits one per cent below the noise maximum."><p>For the trend only, take <span class="math inline">\(\operatorname{Var}(Z) \approx S_\varepsilon(f_1)\,T/4\)</span> with <span class="math inline">\(f_1 = 1/T\)</span>. Above the corner (short <span class="math inline">\(T\)</span>), <span class="math inline">\(S_\varepsilon \propto f^{-5/3}
\propto T^{5/3}\)</span>, so <span class="math inline">\(\operatorname{Var}(Z) \propto T^{8/3}\)</span> and <span class="math inline">\(\sigma(\hat g) = \tfrac{6}{aT}\sqrt{\operatorname{Var}Z} \propto T^{1/3}\)</span>: rising with <span class="math inline">\(T\)</span>. Below the corner (long <span class="math inline">\(T\)</span>), <span class="math inline">\(S_\varepsilon\)</span> is flat, so <span class="math inline">\(\operatorname{Var}(Z) \propto T\)</span> and <span class="math inline">\(\sigma(\hat g) \propto T^{-1/2}\)</span>: falling. The turnover is therefore a <strong>maximum</strong>. The exact integral (figure) puts it at <span class="math inline">\(T \approx 110\)</span> s, with <span class="math inline">\(\sigma(\hat g)\)</span> within <span class="math inline">\(1\%\)</span> of that maximum for <span class="math inline">\(80 \le T \le 150\)</span> s.</p>
</section>
<section id="the-dither-period-continued-what-a-longer-period-buys" class="slide level2 smaller">
<h2>The dither period, continued What a longer period buys</h2>
<div class="claim">
<p>The published <span class="math inline">\(T = 150\)</span> s sits <span class="math inline">\(1\%\)</span> below that maximum. Lengthening the period reduces the noise, and it also helps a second estimator this loop can run: <span class="math inline">\(\hat H\)</span>, the curvature read from the <strong>second harmonic</strong> <span class="math inline">\(2\omega\)</span> of the same dither (the subject of the matrix-gain deck). The rotor is a low-pass filter with time constant <span class="math inline">\(\tau_{\text{rotor}} = 6.4\)</span> s at <span class="math inline">\(8\)</span> m/s (A.0c), and it attenuates that harmonic, so</p>
<p><span class="math display">\[\frac{\hat H}{J''} - 1 \;=\; \frac{1}{1+(2\omega\tau_{\text{rotor}})^2} - 1 \;&lt;\; 0\]</span></p>
<p>At <span class="math inline">\(T = 600\)</span> s the gradient noise is <span class="math inline">\(22\%\)</span> lower (<span class="math inline">\(4.07\)</span> against <span class="math inline">\(5.21\times10^{-7}\)</span>, the table on <em>The answer</em>) and this bias moves from <span class="math inline">\(-22\%\)</span> to <span class="math inline">\(-2\%\)</span>.</p>
</div>
</section>
<section id="what-the-derivation-does-not-fix" class="slide level2 smaller">
<h2>What the derivation does not fix</h2>
<p>Feed the published configuration <a href="#/references">[CLR19]</a> through the closed-loop result: <span class="math inline">\(T = 150\)</span> s, <span class="math inline">\(a = 13.6\%\)</span> of <span class="math inline">\(u^\star\)</span>, <span class="math inline">\(J'' = -1.41\times10^{-13}\)</span>, and a loop that settles in about three periods, which for <span class="math inline">\(\tilde u_{n+1} = (1-K)\tilde u_n\)</span> means <span class="math inline">\((1-K)^3 \approx 1/8\)</span>, <span class="math inline">\(K = 0.5\)</span>, so <span class="math inline">\(\sqrt{K/(2-K)} = 1/\sqrt3\)</span>. With <span class="math inline">\(\sigma(\tilde u) = \sigma(\hat g)/(\sqrt3\,|J''|)\)</span> and <span class="math inline">\(d\ln\lambda/d\ln u = -1/3\)</span> (<em>Link A under the dither</em>):</p>
<p><span class="math display">\[\sigma(u) = 0.96\,u^\star
\qquad\Longrightarrow\qquad
\sigma_\lambda = 2.4
\qquad\text{against}\qquad
\sigma_\lambda \lesssim 0.14 \ \text{from the published table}\]</span></p>
<div class="cols2">
<div class="card">
<p><span class="cardh">inflow spectrum: eliminated</span></p>
<p>Reconciling would need <span class="math inline">\(S_\varepsilon\)</span> smaller by <span class="math inline">\(292\times\)</span>, i.e. <span class="math inline">\(\mathrm{TI} = 0.58\%\)</span> against the stated <span class="math inline">\(10\%\)</span>.</p>
</div>
<div class="card">
<p><span class="cardh">power signal: eliminated</span></p>
<p>Demodulating generator power <span class="math inline">\(u\Omega^3\)</span> rather than aerodynamic <span class="math inline">\(\tau_{\text{aero}}\Omega\)</span> changes <span class="math inline">\(\sigma(\hat g)\)</span> by <span class="math inline">\(2\%\)</span> in simulation.</p>
</div>
</div>
<div class="openq">
<p>The factor of <span class="math inline">\(17\)</span> is now analytic, independent of the solver, and two explanations are gone. What remains: <span class="math inline">\(|J''|\)</span> wrong by that factor, an effective averaging far longer than the reported settling time permits, or an inflow genuinely far quieter at <span class="math inline">\(f_1\)</span> than IEC Kaimal at <span class="math inline">\(10\%\)</span>. <strong>Figure 3 of <a href="#/references">[CLR19]</a> plots the inflow PSD</strong>; its value at <span class="math inline">\(6.7\times10^{-3}\)</span> Hz decides among them.</p>
</div>
</section>
<section id="where-this-leaves-the-program" class="slide level2 smaller">
<h2>Where this leaves the program</h2>
<div class="cols3">
<div class="card">
<p><span class="cardh">established</span></p>
<p><span class="math inline">\(\sigma(\hat g)\)</span> from the inflow spectrum to <span class="math inline">\(6\%\)</span>, nothing fitted. The <span class="math inline">\(\lambda\)</span> channel drops out <strong>at the optimum</strong> and only there.</p>
</div>
<div class="card">
<p><span class="cardh">actionable</span></p>
<p><span class="math inline">\(T = 150\)</span> s is near the worst available dither period. Lengthening it reduces gradient noise and curvature bias together.</p>
</div>
<div class="card">
<p><span class="cardh">open</span></p>
<p>A factor of <span class="math inline">\(17\)</span> against the published scatter, with two of four candidate explanations eliminated.</p>
</div>
</div>
<aside class="notes">
<p>The derivation assumes the iteration <span class="math inline">\(u_n\)</span> has reached its stationary distribution about <span class="math inline">\(u^\star\)</span>, so it gives terminal scatter and says nothing about the transient. It assumes wide-sense stationarity over the averaging window. It uses a point-wise Kaimal spectrum where the rotor actually sees a spatial average over the disc, which would reduce the high-frequency content. And the simulation it is checked against uses the same spectrum, so the agreement tests the algebra rather than the wind model.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="appendices" class="title-slide slide level1 divider center">
<h1>Appendices</h1>
<p>The derivations the main line leaned on without stopping to do.</p>
</section>
<section id="a.0-where-the-equilibrium-relation-comes-from" class="slide level2 smaller">
<h2>A.0 Where the equilibrium relation comes from</h2>
<p>The rotor is a rigid body of inertia <span class="math inline">\(I\)</span>, driven by aerodynamic torque and braked by the generator: <span class="math inline">\(I\dot\Omega = \tau_{\text{aero}} - \tau_g\)</span> with <span class="math inline">\(\tau_g = u\Omega^2\)</span>. Power is torque times angular speed, and <span class="math inline">\(\Omega = \lambda V/R\)</span>, so with <span class="math inline">\(A = \pi R^2\)</span></p>
<p><span class="math display">\[\tau_{\text{aero}} = \frac{P}{\Omega}
= \frac{\tfrac12\rho\pi R^2V^3C_P(\lambda)}{\lambda V/R}
= \tfrac12\rho\pi R^3V^2\,\frac{C_P(\lambda)}{\lambda}\]</span></p>
<p>At rest <span class="math inline">\(\dot\Omega = 0\)</span>, so <span class="math inline">\(\tau_{\text{aero}} = \tau_g = u\lambda^2V^2/R^2\)</span>. The <span class="math inline">\(V^2\)</span> on the two sides cancels, and dividing through:</p>
<p><span class="math display">\[\boxed{\;\frac{C_P(\lambda)}{\lambda^3} = \frac{2}{\rho\pi R^5}\,u =: c\,u\;}\]</span></p>
<div class="claim">
<p>A curve set by the blades meets a line set by the gain at <span class="math inline">\(\lambda_{\text{eq}}(u)\)</span>, and <span class="math inline">\(V\)</span> is gone. That cancellation is the reason for the <span class="math inline">\(\Omega^2\)</span> law: any other power of <span class="math inline">\(\Omega\)</span> leaves a factor of <span class="math inline">\(V\)</span> behind.</p>
</div>
<div class="warn">
<p><span class="math inline">\(C_P/\lambda^3\)</span> is not monotone; it peaks near <span class="math inline">\(\lambda \approx 4\)</span>. The physical root is on the falling branch, the other is unstable, and <span class="math inline">\(\lambda_{\text{eq}}(u)\)</span> means the falling-branch root throughout.</p>
</div>
</section>
<section id="a.0b-where-the-shape-of-c_plambda-comes-from" class="slide level2 smaller">
<h2>A.0b Where the shape of <span class="math inline">\(C_P(\lambda)\)</span> comes from</h2>
<p>Three layers, from what is a theorem down to what is a fit.</p>
<div class="cols3">
<div class="card">
<p><span class="cardh">physics fixes the envelope</span></p>
<p><span class="math inline">\(C_P \ge 0\)</span>, and <span class="math inline">\(C_P \le 16/27 \approx 0.593\)</span> for any rotor: the <strong>Betz limit</strong>, from momentum conservation on the stream tube alone. At <span class="math inline">\(\lambda \to 0\)</span> the rotor is stopped and extracts nothing; at large <span class="math inline">\(\lambda\)</span> the blades run faster than the wind can feed them and drag dominates. So <span class="math inline">\(C_P\)</span> must rise from zero and fall back, and has at least one maximum.</p>
</div>
<div class="card">
<p><span class="cardh">blade design fixes the curve</span></p>
<p>For a <em>given</em> blade, <span class="math inline">\(C_P(\lambda)\)</span> is computed by <strong>blade-element momentum</strong> theory: slice the blade spanwise, look up each section’s lift and drag against its local angle of attack from wind-tunnel airfoil tables, integrate. The result is empirical in its inputs and deterministic in its arithmetic. For a well-designed blade at fixed pitch it has one peak.</p>
</div>
<div class="card">
<p><span class="cardh">what this deck uses</span></p>
<p>Heier’s closed-form fit to typical BEM curves <a href="#/references">[H98]</a>, remapped so its peak sits at <span class="math inline">\((\lambda^\star, C_P^{\max}) = (7.5,\,0.49)\)</span>, the design values of the NREL 5 MW rotor from <a href="#/references">[J09]</a>. A stand-in with the right peak and the right asymmetry, steep on the stall side and gentle above.</p>
</div>
</div>
<div class="claim">
<p>So “single maximum” is an empirical property of good blades, and the specific curve here is a fit. Two consequences the main line depends on survive any such curve: <span class="math inline">\(C_P' = 0\)</span> at the peak, which is what Link A uses, and <span class="math inline">\(C_P/\lambda^3\)</span> being non-monotone, which is why A.0 must pick a branch.</p>
</div>
</section>
<section id="a.0c-the-rotor-time-constant" class="slide level2 smaller">
<h2>A.0c The rotor time constant</h2>
<p>Write the rotor equation of A.0 at fixed <span class="math inline">\(u\)</span> as <span class="math inline">\(I\dot\Omega = F(\Omega,V) :=
\tau_{\text{aero}}(\Omega,V) - u\Omega^2\)</span>, with equilibrium <span class="math inline">\(F(\Omega_{\text{eq}},\bar V)
= 0\)</span>. For <span class="math inline">\(\delta\Omega := \Omega - \Omega_{\text{eq}}\)</span> and <span class="math inline">\(\delta V := V - \bar V
= \bar V\varepsilon\)</span>, to first order</p>
<p><span class="math display">\[I\,\dot{\delta\Omega} = F_\Omega\,\delta\Omega + F_V\,\delta V,
\qquad F_\Omega := \partial F/\partial\Omega,\ F_V := \partial F/\partial V
\ \text{at the equilibrium.}\]</span></p>
<p>From A.0, <span class="math inline">\(\tau_{\text{aero}} = \tfrac12\rho\pi R^3V^2\,C_P(\lambda)/\lambda\)</span> with <span class="math inline">\(\lambda = R\Omega/V\)</span>, so <span class="math inline">\(\partial\lambda/\partial\Omega = R/V\)</span> and</p>
<p><span class="math display">\[\frac{\partial\tau_{\text{aero}}}{\partial\Omega}
= \tfrac12\rho\pi R^3V^2\,\frac{\lambda C_P'(\lambda) - C_P(\lambda)}{\lambda^2}\,\frac{R}{V}
= \tfrac12\rho\pi R^4V\,\frac{\lambda C_P' - C_P}{\lambda^2},
\qquad
2u\Omega_{\text{eq}} = \frac{2\tau_{\text{aero}}}{\Omega_{\text{eq}}}
= \rho\pi R^4V\,\frac{C_P}{\lambda^2}\]</span></p>
<p>the second using <span class="math inline">\(u\Omega_{\text{eq}}^2 = \tau_{\text{aero}}\)</span> at equilibrium. Therefore</p>
<p><span class="math display">\[F_\Omega = -\tfrac12\rho\pi R^4\bar V\,\frac{3C_P - \lambda C_P'}{\lambda^2} &lt; 0,
\qquad
\tau_{\text{rotor}} := -\frac{I}{F_\Omega}
= \frac{2I\lambda^2}{\rho\pi R^4\bar V\,\big(3C_P(\lambda) - \lambda C_P'(\lambda)\big)},
\qquad
b := \frac{F_V\bar V}{I}\]</span></p>
<div class="claim">
<p>At the peak <span class="math inline">\(C_P' = 0\)</span>, so <span class="math inline">\(\tau_{\text{rotor}} = 2I\lambda^{\star2}/(3\rho\pi R^4\bar V
C_P^{\max}) = 6.4\)</span> s for <span class="math inline">\(I = 4.05\times10^{7}\)</span> kg m<span class="math inline">\(^2\)</span> (rotor <span class="math inline">\(3.54\times10^{7}\)</span> plus <span class="math inline">\(97^2\times534\)</span> from the generator through the gearbox, <a href="#/references">[J09]</a>) and <span class="math inline">\(\bar V = 8\)</span> m/s. Dividing the linearized equation by <span class="math inline">\(I\)</span> gives <span class="math inline">\(\dot{\delta\Omega} + \delta\Omega/\tau_{\text{rotor}} = b\,\varepsilon(t)\)</span>, the form on <em>Link A, standing assumptions</em>. The full equation is stable about the same equilibrium and forgets <span class="math inline">\(\Omega(0)\)</span> in the same way; the linearization makes the rate explicit.</p>
</div>
</section>
<section id="a.0c-continued-the-rotor-as-a-low-pass-filter" class="slide level2 smaller">
<h2>A.0c, continued The rotor as a low-pass filter</h2>
<p>For a single-frequency input <span class="math inline">\(\varepsilon(t) = \cos(2\pi f t)\)</span> the steady-state solution of <span class="math inline">\(\dot{\delta\Omega} + \delta\Omega/\tau_{\text{rotor}} = b\,\varepsilon\)</span> is</p>
<p><span class="math display">\[\delta\Omega(t) = \frac{b\,\tau_{\text{rotor}}}{\sqrt{1+(2\pi f\tau_{\text{rotor}})^2}}
\cos\big(2\pi f t - \varphi\big),
\qquad \varphi = \arctan(2\pi f\tau_{\text{rotor}})\]</span></p>
<p>a first-order low-pass with corner frequency <span class="math inline">\(1/(2\pi\tau_{\text{rotor}}) = 0.025\)</span> Hz.</p>
<div class="claim">
<p>Below the corner, <span class="math inline">\(\Omega\)</span> follows the wind and <span class="math inline">\(\lambda\)</span> stays near <span class="math inline">\(\lambda_{\text{eq}}(u)\)</span>; above it, <span class="math inline">\(\Omega\)</span> barely moves and <span class="math inline">\(\lambda\)</span> follows <span class="math inline">\(1/V\)</span>. These are the two limits bracketing <span class="math inline">\(\delta\lambda\)</span> on <em>Link A, executed, continued</em>. A harmonic of the dither at frequency <span class="math inline">\(f\)</span> is attenuated by <span class="math inline">\(1/\sqrt{1+(2\pi f\tau_{\text{rotor}})^2}\)</span> and delayed by <span class="math inline">\(\varphi\)</span>; demodulating it in phase with the dither projects onto <span class="math inline">\(\cos\varphi = 1/\sqrt{1+(2\pi
f\tau_{\text{rotor}})^2}\)</span> a second time. The product at the second harmonic <span class="math inline">\(2\omega\)</span> is <span class="math inline">\(1/(1+(2\omega\tau_{\text{rotor}})^2)\)</span>, the factor on <em>The dither period has a worst case</em>.</p>
</div>
</section>
<section id="a.0d-why-barlambda---lambdastar-is-second-order" class="slide level2 smaller">
<h2>A.0d Why <span class="math inline">\(\bar\lambda - \lambda^\star\)</span> is second order</h2>
<p>Under the standing assumptions <span class="math inline">\(\lambda(t)\)</span> is a functional of the wind path, and the next slide derives its expansion in powers of <span class="math inline">\(\varepsilon\)</span> about <span class="math inline">\(\varepsilon \equiv 0\)</span>, where <span class="math inline">\(\lambda = \lambda_{\text{eq}}(u)\)</span>:</p>
<p><span class="math display">\[\lambda(t) = \lambda_{\text{eq}}(u) + \Lambda_1[\varepsilon](t) + \Lambda_2[\varepsilon](t) + O(\varepsilon^3)\]</span></p>
<p><span class="math display">\[\Lambda_1[\varepsilon](t) = \int_0^\infty h(s)\,\varepsilon(t-s)\,ds,
\qquad
\Lambda_2[\varepsilon](t) = \iint_0^\infty k(s_1,s_2)\,\varepsilon(t-s_1)\,\varepsilon(t-s_2)\,ds_1\,ds_2\]</span></p>
<p>with <span class="math inline">\(h\)</span> and <span class="math inline">\(k\)</span> fixed kernels set by the rotor equation. Taking expectations,</p>
<p><span class="math display">\[\mathbb{E}\,\Lambda_1 = \int_0^\infty h(s)\,\mathbb{E}[\varepsilon(t-s)]\,ds = 0,
\qquad
\big|\mathbb{E}\,\Lambda_2\big| = \Big|\iint k(s_1,s_2)\,\Gamma(s_1-s_2)\,ds_1ds_2\Big|
\le \|k\|_{1}\,\Gamma(0) = \|k\|_{1}\,\sigma_\varepsilon^2\]</span></p>
<p>the first because <span class="math inline">\(\mathbb{E}[\varepsilon] = 0\)</span>, the second because <span class="math inline">\(|\Gamma(\tau)| \le
\Gamma(0)\)</span> (Cauchy-Schwarz). At <span class="math inline">\(u = u^\star\)</span>, <span class="math inline">\(\lambda_{\text{eq}}(u^\star) =
\lambda^\star\)</span>, so <span class="math inline">\(\bar\lambda - \lambda^\star = \mathbb{E}\,\Lambda_2 + O(\mathbb{E}|\varepsilon|^3)
= O(\sigma_\varepsilon^2)\)</span>.</p>
<div class="claim">
<p><strong>In the two rotor limits.</strong> Frozen <span class="math inline">\(\Omega\)</span>: <span class="math inline">\(\lambda = \lambda^\star/(1+\varepsilon)
= \lambda^\star(1 - \varepsilon + \varepsilon^2 - \dots)\)</span>, so <span class="math inline">\(\Lambda_1 =
-\lambda^\star\varepsilon\)</span> has mean zero and <span class="math inline">\(\Lambda_2 = \lambda^\star\varepsilon^2\)</span> has mean <span class="math inline">\(\lambda^\star\sigma_\varepsilon^2 = 0.01\,\lambda^\star\)</span>. Tracking <span class="math inline">\(\Omega\)</span>: <span class="math inline">\(\lambda = \lambda^\star\)</span> and the difference is zero. With the linearized rotor of A.0c, <span class="math inline">\(\lambda = \lambda^\star(1 + \delta\Omega/\Omega_{\text{eq}})(1 -
\varepsilon + \varepsilon^2 - \dots)\)</span>; the first-order part <span class="math inline">\(\delta\Omega/\Omega_{\text{eq}} - \varepsilon\)</span> has mean zero, and the second-order part <span class="math inline">\(\varepsilon^2 - \varepsilon\,\delta\Omega/\Omega_{\text{eq}}\)</span> has mean <span class="math inline">\(\sigma_\varepsilon^2 - \mathbb{E}[\varepsilon\,\delta\Omega]/\Omega_{\text{eq}}\)</span> with <span class="math inline">\(|\mathbb{E}[\varepsilon\,\delta\Omega]| = \big|b\int_0^\infty e^{-s/\tau_{\text{rotor}}}\Gamma(s)\,ds\big|
\le b\,\tau_{\text{rotor}}\,\sigma_\varepsilon^2\)</span>.</p>
</div>
</section>
<section id="a.0d-continued-where-the-expansion-comes-from" class="slide level2 smaller">
<h2>A.0d, continued Where the expansion comes from</h2>
<p><span class="math inline">\(\Omega(t)\)</span> solves <span class="math inline">\(I\dot\Omega = F(\Omega,V)\)</span>, <span class="math inline">\(F := \tau_{\text{aero}} - u\Omega^2\)</span>, driven by <span class="math inline">\(V = \bar V(1+\varepsilon)\)</span>, with <span class="math inline">\(F\)</span> smooth and the equilibrium stable (<span class="math inline">\(F_\Omega &lt; 0\)</span>, A.0c). Seek the solution ordered by powers of <span class="math inline">\(\varepsilon\)</span>, <span class="math inline">\(\Omega = \Omega_{\text{eq}} + \Omega_1 + \Omega_2 + \dots\)</span> with <span class="math inline">\(\Omega_n\)</span> of order <span class="math inline">\(n\)</span>, expand <span class="math inline">\(F\)</span> about <span class="math inline">\((\Omega_{\text{eq}},\bar V)\)</span>, and collect equal orders:</p>
<ul>
<li><strong>Order 1.</strong> <span class="math inline">\(I\dot\Omega_1 = F_\Omega\Omega_1 + F_V\bar V\varepsilon\)</span>, the linearized equation of A.0c, so <span class="math display">\[\Omega_1(t) = b\int_0^\infty e^{-s/\tau_{\text{rotor}}}\,\varepsilon(t-s)\,ds\]</span> linear in the path, with kernel <span class="math inline">\(b\,e^{-s/\tau_{\text{rotor}}}\)</span>.</li>
<li><strong>Order 2.</strong> <span class="math inline">\(I\dot\Omega_2 = F_\Omega\Omega_2 + \tfrac12F_{\Omega\Omega}\Omega_1^2
+ F_{\Omega V}\bar V\,\Omega_1\varepsilon + \tfrac12F_{VV}\bar V^2\varepsilon^2\)</span>: the same stable operator, forced by products of two first-order quantities, so <span class="math display">\[\Omega_2(t) = \frac1I\int_0^\infty e^{-s/\tau_{\text{rotor}}}
\Big[\tfrac12F_{\Omega\Omega}\Omega_1^2 + F_{\Omega V}\bar V\,\Omega_1\varepsilon
+ \tfrac12F_{VV}\bar V^2\varepsilon^2\Big](t-s)\,ds\]</span> With <span class="math inline">\(\Omega_1\)</span> itself an integral of <span class="math inline">\(\varepsilon\)</span>, this is a double integral of <span class="math inline">\(\varepsilon(t-s_1)\varepsilon(t-s_2)\)</span> against a fixed kernel <span class="math inline">\(k(s_1,s_2)\)</span>.</li>
<li><strong>Order 3 and higher</strong> are forced by cubic and higher products: <span class="math inline">\(O(\varepsilon^3)\)</span>.</li>
</ul>
<div class="claim">
<p>Time invariance of <span class="math inline">\(F\)</span> makes the kernels depend on lags only; causality puts the integrals on <span class="math inline">\(s \ge 0\)</span>; stability makes <span class="math inline">\(e^{-s/\tau_{\text{rotor}}}\)</span> integrable, so each <span class="math inline">\(\Omega_n\)</span> is bounded by a constant times <span class="math inline">\(\max|\varepsilon|^n\)</span> over the filter’s memory.</p>
</div>
</section>
<section id="a.0d-continued-from-omega-to-lambda" class="slide level2 smaller">
<h2>A.0d, continued From <span class="math inline">\(\Omega\)</span> to <span class="math inline">\(\lambda\)</span></h2>
<p>With <span class="math inline">\(R\Omega_{\text{eq}}/\bar V = \lambda_{\text{eq}}(u)\)</span> and <span class="math inline">\(1/(1+\varepsilon)
= 1 - \varepsilon + \varepsilon^2 - \dots\)</span>, <span class="math display">\[\lambda = \frac{R\Omega}{\bar V(1+\varepsilon)}
= \lambda_{\text{eq}}\Big(1 + \frac{\Omega_1}{\Omega_{\text{eq}}} + \frac{\Omega_2}{\Omega_{\text{eq}}} + \dots\Big)\big(1 - \varepsilon + \varepsilon^2 - \dots\big)\]</span> <span class="math display">\[\Lambda_1 = \lambda_{\text{eq}}\Big(\frac{\Omega_1}{\Omega_{\text{eq}}} - \varepsilon\Big),
\qquad
\Lambda_2 = \lambda_{\text{eq}}\Big(\frac{\Omega_2}{\Omega_{\text{eq}}} - \varepsilon\frac{\Omega_1}{\Omega_{\text{eq}}} + \varepsilon^2\Big)\]</span></p>
<div class="claim">
<p>These are the functionals <span class="math inline">\(\Lambda_1\)</span>, <span class="math inline">\(\Lambda_2\)</span> of A.0d: <span class="math inline">\(\Lambda_1\)</span> is linear in the path because <span class="math inline">\(\Omega_1\)</span> is; <span class="math inline">\(\Lambda_2\)</span> is quadratic because <span class="math inline">\(\Omega_2\)</span>, <span class="math inline">\(\varepsilon\Omega_1\)</span> and <span class="math inline">\(\varepsilon^2\)</span> are. The frozen rotor is the case <span class="math inline">\(\Omega_1 = \Omega_2 = 0\)</span>, which gives <span class="math inline">\(\Lambda_1 = -\lambda_{\text{eq}}\varepsilon\)</span> and <span class="math inline">\(\Lambda_2 = \lambda_{\text{eq}}\varepsilon^2\)</span> as on A.0d.</p>
</div>
</section>
<section id="a.1-the-estimator-is-a-fourier-coefficient" class="slide level2 smaller">
<h2>A.1 The estimator is a Fourier coefficient</h2>
<p>Let <span class="math inline">\(y\)</span> be <span class="math inline">\(T\)</span>-periodic with Fourier series <span class="math inline">\(y = \tfrac{a_0}{2} +
\sum_{k\ge1}(a_k\cos k\omega t + b_k\sin k\omega t)\)</span>, <span class="math inline">\(\omega := 2\pi/T\)</span>. Multiply by <span class="math inline">\(\sin\omega t\)</span>, integrate over one period, and use three product-to-sum identities:</p>
<p><span class="math display">\[\int_0^T\!\sin\omega t\,dt = 0,
\qquad
\int_0^T\!\cos k\omega t\,\sin\omega t\,dt = \tfrac12\!\int_0^T\!\big[\sin(k{+}1)\omega t - \sin(k{-}1)\omega t\big]dt = 0,\]</span> <span class="math display">\[\int_0^T\!\sin k\omega t\,\sin\omega t\,dt
= \tfrac12\!\int_0^T\!\big[\cos(k{-}1)\omega t - \cos(k{+}1)\omega t\big]dt
= \begin{cases} T/2, &amp; k = 1\\ 0, &amp; k \ne 1\end{cases}\]</span></p>
<p>because a non-constant sinusoid integrates to zero over whole periods, while for <span class="math inline">\(k = 1\)</span> the first cosine is <span class="math inline">\(\cos0 = 1\)</span>. Every term dies except one:</p>
<p><span class="math display">\[\int_0^T y(t)\sin\omega t\,dt = b_1\cdot\frac{T}{2}
\qquad\Longrightarrow\qquad
b_1 = \frac{2}{T}\int_0^T y(t)\sin\omega t\,dt\]</span></p>
<div class="claim">
<p>Now the estimator, with the constants pulled out of the integral: <span class="math display">\[\hat g = \frac{1}{T}\int_0^T y(t)\,\frac{2}{a}\sin\omega t\,dt
= \frac{1}{a}\cdot\underbrace{\frac{2}{T}\int_0^T y(t)\sin\omega t\,dt}_{=\;b_1}
= \frac{b_1}{a}\]</span> <strong>The estimator is the first sine coefficient of the measured log-power, divided by the probe amplitude.</strong> Its <span class="math inline">\(2/a\)</span> is the Fourier <span class="math inline">\(2/T\)</span> times the <span class="math inline">\(1/a\)</span> that turns a power swing into a slope.</p>
</div>
</section>
<section id="a.1-continued-from-log-power-to-j" class="slide level2 smaller">
<h2>A.1, continued From log-power to <span class="math inline">\(J\)</span></h2>
<p>Two idealizations, both stated: <span class="math inline">\(\varepsilon \equiv 0\)</span>, so <span class="math inline">\(V = \bar V\)</span> is constant; and the rotor sits at its equilibrium at every instant, so <span class="math inline">\(\lambda(t) = \lambda_{\text{eq}}(u(t))\)</span> with <span class="math inline">\(u(t) = u + a\sin\omega t\)</span>. From <em>What we need from the turbine</em>, <span class="math inline">\(P = \tfrac12\rho A\bar V^3C_P(\lambda)\)</span> and <span class="math inline">\(J(u) := \ln C_P(\lambda_{\text{eq}}(u))\)</span>. Therefore</p>
<p><span class="math display">\[y(t) = \ln P(t)
= \ln\big(\tfrac12\rho A\bar V^3\big) + \ln C_P\big(\lambda_{\text{eq}}(u(t))\big)
= \underbrace{\ln\big(\tfrac12\rho A\bar V^3\big)}_{\text{a constant}}
+ J\big(u + a\sin\omega t\big)\]</span></p>
<div class="claim">
<p>The constant contributes nothing to <span class="math inline">\(b_1\)</span>, because <span class="math inline">\(\int_0^T\sin\omega t\,dt = 0\)</span> (A.1). So for the purpose of computing <span class="math inline">\(b_1\)</span>, <strong><span class="math inline">\(y\)</span> may be replaced by <span class="math inline">\(J(u + a\sin\omega t)\)</span></strong>, which is what the next slide expands. Both idealizations are relaxed in the main line: the first by Links A through D, the second by the rotor-dynamics correction on <em>The dither period has a worst case</em>.</p>
</div>
</section>
<section id="a.1-continued-what-that-coefficient-is" class="slide level2 smaller">
<h2>A.1, continued What that coefficient is</h2>
<p>Taylor-expand <span class="math inline">\(J(u + a\sin\omega t)\)</span> in <span class="math inline">\(a\)</span>:</p>
<p><span class="math display">\[J(u + a\sin\omega t) = J + J'a\sin\omega t + \frac{J''}{2}a^2\sin^2\omega t
+ \frac{J'''}{6}a^3\sin^3\omega t + O(a^4)\]</span></p>
<p>To read off <span class="math inline">\(b_1\)</span>, each power of <span class="math inline">\(\sin\omega t\)</span> must be rewritten as a sum of harmonics. Two identities, the second from <span class="math inline">\(\sin3\theta = 3\sin\theta -
4\sin^3\theta\)</span> rearranged:</p>
<p><span class="math display">\[\sin^2\theta = \tfrac12 - \tfrac12\cos2\theta,
\qquad
\sin^3\theta = \tfrac34\sin\theta - \tfrac14\sin3\theta\]</span></p>
<p>Now collect the coefficient of <span class="math inline">\(\sin\omega t\)</span> term by term:</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>term</th>
<th>its <span class="math inline">\(\sin\omega t\)</span> content</th>
<th>contribution to <span class="math inline">\(b_1\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(J\)</span></td>
<td>none</td>
<td><span class="math inline">\(0\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(J'a\sin\omega t\)</span></td>
<td>itself</td>
<td><span class="math inline">\(J'a\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\tfrac{J''}{2}a^2\sin^2\omega t\)</span></td>
<td>constant and <span class="math inline">\(\cos2\omega t\)</span> only</td>
<td><span class="math inline">\(0\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\tfrac{J'''}{6}a^3\sin^3\omega t\)</span></td>
<td><span class="math inline">\(\tfrac34\sin\omega t\)</span></td>
<td><span class="math inline">\(\tfrac{J'''}{6}\cdot\tfrac34\,a^3 = \tfrac{a^3}{8}J'''\)</span></td>
</tr>
</tbody>
</table>
<div class="claim">
<p><span class="math display">\[b_1 = aJ' + \frac{a^3}{8}J''' + O(a^5)
\qquad\Longrightarrow\qquad
\hat g = \frac{b_1}{a} = J' + \frac{a^2}{8}J''' + O(a^4)\]</span> Every even power of <span class="math inline">\(\sin\)</span> is a constant plus cosines (A.2), so only odd powers of <span class="math inline">\(a\)</span> reach <span class="math inline">\(b_1\)</span>, and after the division only even powers reach <span class="math inline">\(\hat g\)</span>. Same <span class="math inline">\(a^2/8\)</span> as on <em>The bias grows as <span class="math inline">\(a^2\)</span></em>, by a different route.</p>
</div>
</section>
<section id="a.2-moments-of-a-sine-over-a-whole-period" class="slide level2 smaller">
<h2>A.2 Moments of a sine over a whole period</h2>
<p>With <span class="math inline">\(s = \sin\omega t\)</span> and <span class="math inline">\(\langle\cdot\rangle = \tfrac1T\int_0^T(\cdot)\,dt\)</span> over one period:</p>
<p><span class="math display">\[\langle s^{2m+1}\rangle = 0 \quad\text{for every } m \ge 0\]</span></p>
<p>because <span class="math inline">\(\sin\omega t\)</span> is odd about <span class="math inline">\(t = T/2\)</span> and the interval is symmetric about that point, so the two halves cancel. For the even moments,</p>
<p><span class="math display">\[\langle s^2\rangle = \Big\langle\tfrac{1-\cos2\omega t}{2}\Big\rangle = \tfrac12,
\qquad
\langle s^4\rangle = \Big\langle\tfrac{3 - 4\cos2\omega t + \cos4\omega t}{8}\Big\rangle = \tfrac38\]</span></p>
<p>using <span class="math inline">\(\sin^4\theta = \tfrac18(3 - 4\cos2\theta + \cos4\theta)\)</span> and that every non-constant cosine averages to zero over a whole period. These are the only moments the bias derivation uses.</p>
</section>
<section id="a.3-the-windows-transform-in-closed-form" class="slide level2 smaller">
<h2>A.3 The window’s transform, in closed form</h2>
<p>The window is <span class="math inline">\(w(t) = \sin\omega_1 t\)</span> on <span class="math inline">\([0,T]\)</span> with <span class="math inline">\(\omega_1 = 2\pi/T\)</span>, and zero elsewhere. Write <span class="math inline">\(\beta := 2\pi f\)</span> and <span class="math inline">\(\sin\omega_1 t = (e^{i\omega_1 t} - e^{-i\omega_1 t})/2i\)</span>:</p>
<p><span class="math display">\[\hat w(f) = \int_0^T \sin\omega_1 t\,e^{-i\beta t}\,dt
= \frac{1}{2i}\left[\frac{e^{i(\omega_1-\beta)T}-1}{i(\omega_1-\beta)}
+ \frac{e^{-i(\omega_1+\beta)T}-1}{i(\omega_1+\beta)}\right]\]</span></p>
<p>Since <span class="math inline">\(\omega_1T = 2\pi\)</span>, both exponentials equal <span class="math inline">\(e^{-i\beta T}\)</span> and the fractions combine:</p>
<p><span class="math display">\[\boxed{\;\hat w(f) = \frac{\omega_1\big(1 - e^{-i2\pi fT}\big)}{\omega_1^2 - (2\pi f)^2}\;}
\qquad\Longrightarrow\qquad
|\hat w(f)|^2 = \frac{4\omega_1^2\sin^2(\pi fT)}{\big(\omega_1^2 - 4\pi^2f^2\big)^2}\]</span></p>
<div class="claim">
<p>At <span class="math inline">\(f = f_1 = 1/T\)</span> numerator and denominator both vanish; the limit is <span class="math inline">\(|\hat w(f_1)|^2 = T^2/4\)</span>. The main lobe lies between the first two zeros of <span class="math inline">\(\sin^2(\pi fT)\)</span>, at <span class="math inline">\(f = 0\)</span> and <span class="math inline">\(f = 2f_1\)</span>, which is the <span class="math inline">\([0, 2f_1]\)</span> quoted on <em>A shortcut that does not apply here</em>. Checked against a numerical transform at four frequencies to all printed digits.</p>
</div>
</section>
<section id="a.4-parseval-for-the-window" class="slide level2 smaller">
<h2>A.4 Parseval for the window</h2>
<p>Parseval’s identity for square-integrable <span class="math inline">\(w\)</span> states <span class="math inline">\(\int_{\mathbb{R}}|\hat w(f)|^2\,df = \int_{\mathbb{R}}|w(t)|^2\,dt\)</span>. The right side is elementary:</p>
<p><span class="math display">\[\int_{\mathbb{R}}|\hat w(f)|^2\,df = \int_0^T\sin^2\omega_1 t\,dt
= \int_0^T\frac{1-\cos2\omega_1 t}{2}\,dt = \frac{T}{2}\]</span></p>
<p>the cosine integrating to zero over the two full cycles it completes on <span class="math inline">\([0,T]\)</span>. This fixes the total weight the window places on the spectrum, and it is what the narrowband shortcut in Link C uses when it pulls <span class="math inline">\(S\)</span> outside the integral.</p>
</section>
<section id="a.5-stationary-variance-of-a-first-order-autoregression" class="slide level2 smaller">
<h2>A.5 Stationary variance of a first-order autoregression</h2>
<p>Let <span class="math inline">\(x_{n+1} = \alpha x_n + e_n\)</span> with <span class="math inline">\(|\alpha| &lt; 1\)</span>, <span class="math inline">\(e_n\)</span> zero-mean with variance <span class="math inline">\(\sigma_e^2\)</span> and uncorrelated with <span class="math inline">\(x_n\)</span>. If <span class="math inline">\(x\)</span> is stationary then <span class="math inline">\(\operatorname{Var}(x_{n+1}) = \operatorname{Var}(x_n) =: \Sigma\)</span>, and taking variances of both sides,</p>
<p><span class="math display">\[\Sigma = \alpha^2\Sigma + \sigma_e^2 \qquad\Longrightarrow\qquad \Sigma = \frac{\sigma_e^2}{1-\alpha^2}\]</span></p>
<div class="claim">
<p>On <em>The terminal error of the closed loop</em>, <span class="math inline">\(\alpha = 1 - K\)</span> and <span class="math inline">\(e_n = \kappa\hat g_{\text{noise},n}\)</span>, so <span class="math inline">\(\sigma_e^2 = \kappa^2\sigma^2(\hat g)\)</span> and <span class="math inline">\(1-\alpha^2 = 1-(1-K)^2 = K(2-K)\)</span>. Substituting <span class="math inline">\(\kappa = K/|J''|\)</span> gives the boxed result there. Stationarity requires <span class="math inline">\(|1-K| &lt; 1\)</span>, that is <span class="math inline">\(0 &lt; K &lt; 2\)</span>, which is the loop’s stability condition.</p>
</div>
</section>
<section id="a.6-why-a-short-record-under-measures-a-persistent-process" class="slide level2 smaller">
<h2>A.6 Why a short record under-measures a persistent process</h2>
<p>Take <span class="math inline">\(N\)</span> consecutive samples of a stationary process with variance <span class="math inline">\(\sigma^2\)</span> and autocorrelations <span class="math inline">\(\rho_k\)</span>, and form the sample variance <span class="math inline">\(s^2 := \tfrac1N\sum_{n=1}^N(x_n - \bar x)^2\)</span> with <span class="math inline">\(\bar x := \tfrac1N\sum_n x_n\)</span> the sample mean. Take the process zero-mean (subtract the mean otherwise). Expanding the square, <span class="math inline">\(\sum_n(x_n-\bar x)^2 = \sum_n x_n^2 - 2\bar x\sum_n x_n +
N\bar x^2 = \sum_n x_n^2 - N\bar x^2\)</span>, so</p>
<p><span class="math display">\[\mathbb{E}[s^2] = \frac1N\sum_{n=1}^N\mathbb{E}[x_n^2] - \mathbb{E}[\bar x^2]
= \sigma^2 - \operatorname{Var}(\bar x),
\qquad
\operatorname{Var}(\bar x) = \frac{\sigma^2}{N}\Big[1 + 2\sum_{k=1}^{N-1}\big(1-\tfrac kN\big)\rho_k\Big]\ \text{(A.9)}\]</span></p>
<div class="claim">
<p>For an AR(1), <span class="math inline">\(\rho_k = \alpha^k\)</span>. With <span class="math inline">\(\alpha = 0.985\)</span> and <span class="math inline">\(N = 270\)</span> the bracket is <span class="math inline">\(170\)</span>, so <span class="math inline">\(\mathbb{E}[s^2] = 0.628\,\sigma^2\)</span> and the expected sample <strong>standard deviation</strong> is <span class="math inline">\(0.79\,\sigma\)</span>. A persistent series sampled for only a few correlation times has not had room to wander as far as it eventually will, and the sample variance records that. The measured/predicted ratio of <span class="math inline">\(0.777\)</span> on the terminal-error slide is this effect, not a failure of the formula.</p>
</div>
</section>
<section id="a.7-variance-per-decade-and-the-peak-of-fs_varepsilon" class="slide level2 smaller">
<h2>A.7 Variance per decade, and the peak of <span class="math inline">\(fS_\varepsilon\)</span></h2>
<p><strong>Variance per decade.</strong> With <span class="math inline">\(u := \ln f\)</span>, <span class="math inline">\(df = f\,du\)</span>, so <span class="math display">\[\sigma_\varepsilon^2 = \int_0^\infty S(f)\,df = \int_{-\infty}^{\infty} f\,S(f)\,d(\ln f)\]</span> On a logarithmic frequency axis the area under <span class="math inline">\(fS\)</span> is the variance; the contribution of one decade is the area of <span class="math inline">\(fS\)</span> over that decade.</p>
<p><strong>The peak.</strong> Write <span class="math inline">\(c := 6L/\bar V\)</span>, so <span class="math inline">\(S_\varepsilon = \mathrm{TI}^2(4L/\bar V)(1+cf)^{-5/3}\)</span> and <span class="math inline">\(fS_\varepsilon \propto f(1+cf)^{-5/3}\)</span>. Differentiate: <span class="math display">\[\frac{d}{df}\Big[f(1+cf)^{-5/3}\Big]
= (1+cf)^{-5/3} - \tfrac53\,cf\,(1+cf)^{-8/3}
= (1+cf)^{-8/3}\Big[(1+cf) - \tfrac53 cf\Big]
= (1+cf)^{-8/3}\Big[1 - \tfrac23 cf\Big]\]</span> which vanishes at <span class="math inline">\(cf = 3/2\)</span>, that is <span class="math inline">\(f = \tfrac{3}{2c} = \tfrac{3\bar V}{12L} = \tfrac{\bar V}{4L}\)</span>, and changes sign from positive to negative there: a maximum. At <span class="math inline">\(\bar V = 8\)</span> m/s, <span class="math inline">\(L = 340\)</span> m this is <span class="math inline">\(5.9\times10^{-3}\)</span> Hz, against the corner <span class="math inline">\(\bar V/6L = 3.9\times10^{-3}\)</span> Hz.</p>
</section>
<section id="a.8-correlation-between-estimates-k-periods-apart" class="slide level2 smaller">
<h2>A.8 Correlation between estimates <span class="math inline">\(k\)</span> periods apart</h2>
<p>The estimate from period <span class="math inline">\(k\)</span> uses the window shifted by <span class="math inline">\(kT\)</span>, <span class="math inline">\(w_k(t) :=
w(t-kT)\)</span>, so <span class="math inline">\(Z_k := \int_{\mathbb{R}}\varepsilon(t)\,w_k(t)\,dt\)</span>. Substituting <span class="math inline">\(t' = t - kT\)</span>, the shift becomes a phase on the transform: <span class="math inline">\(\hat w_k(f) = \int w(t-kT)\,e^{-i2\pi ft}dt = e^{-i2\pi fkT}\int w(t')\,e^{-i2\pi ft'}dt'
= e^{-i2\pi fkT}\,\hat w(f)\)</span>. Repeating Link C’s calculation with the two windows <span class="math inline">\(w\)</span> and <span class="math inline">\(w_k\)</span>,</p>
<p><span class="math display">\[\operatorname{Cov}(Z_0,Z_k)
= \iint w(t)\,w(s-kT)\,\Gamma(t-s)\,dt\,ds
= \int_{\mathbb{R}} S^{2s}(f)\,\overline{\hat w(f)}\,e^{-i2\pi fkT}\hat w(f)\,df
= \int_{\mathbb{R}} S^{2s}(f)\,|\hat w(f)|^2\,e^{-i2\pi fkT}\,df\]</span></p>
<div class="claim">
<p><span class="math inline">\(S^{2s}|\hat w|^2\)</span> is even in <span class="math inline">\(f\)</span>, so the sine part of <span class="math inline">\(e^{-i2\pi fkT}\)</span> integrates to zero and <span class="math display">\[\rho_k := \frac{\operatorname{Cov}(Z_0,Z_k)}{\operatorname{Var}(Z)}
= \frac{\int S^{2s}(f)\,|\hat w(f)|^2\cos(2\pi fkT)\,df}{\int S^{2s}(f)\,|\hat w(f)|^2\,df}\]</span> the formula on <em>Averaging over <span class="math inline">\(N\)</span> periods</em>. Dividing by <span class="math inline">\(6/aT\)</span> on both sides leaves the ratio unchanged, so <span class="math inline">\(\rho_k\)</span> is also the correlation of <span class="math inline">\(\hat g_{\text{noise}}\)</span> across periods.</p>
</div>
</section>
<section id="a.9-variance-of-the-mean-of-n-correlated-samples" class="slide level2 smaller">
<h2>A.9 Variance of the mean of <span class="math inline">\(N\)</span> correlated samples</h2>
<p>Let <span class="math inline">\(x_1,\dots,x_N\)</span> have common variance <span class="math inline">\(\sigma^2\)</span> and correlations <span class="math inline">\(\operatorname{Corr}(x_n,x_m) = \rho_{|n-m|}\)</span>, and <span class="math inline">\(\bar x := \tfrac1N\sum_n x_n\)</span>. Variance of a sum is the sum of all covariances:</p>
<p><span class="math display">\[\operatorname{Var}(\bar x) = \frac1{N^2}\sum_{n=1}^N\sum_{m=1}^N\operatorname{Cov}(x_n,x_m)
= \frac{\sigma^2}{N^2}\sum_{n=1}^N\sum_{m=1}^N\rho_{|n-m|}\]</span></p>
<p>Count the pairs by lag <span class="math inline">\(k := |n-m|\)</span>: there are <span class="math inline">\(N\)</span> pairs with <span class="math inline">\(k = 0\)</span> and <span class="math inline">\(2(N-k)\)</span> pairs with lag <span class="math inline">\(k \ge 1\)</span> (each unordered pair twice). Hence</p>
<p><span class="math display">\[\operatorname{Var}(\bar x) = \frac{\sigma^2}{N^2}\Big[N + 2\sum_{k=1}^{N-1}(N-k)\rho_k\Big]
= \frac{\sigma^2}{N}\Big[1 + 2\sum_{k=1}^{N-1}\Big(1-\frac kN\Big)\rho_k\Big]\]</span></p>
<div class="claim">
<p>With all <span class="math inline">\(\rho_k = 0\)</span> the bracket is <span class="math inline">\(1\)</span> and <span class="math inline">\(\operatorname{Var}(\bar x) = \sigma^2/N\)</span>, the independent case. Applied to <span class="math inline">\(\hat g_n\)</span> with the <span class="math inline">\(\rho_k\)</span> of A.8 this is the formula on <em>Averaging over <span class="math inline">\(N\)</span> periods</em>; applied to the closed-loop iterates with <span class="math inline">\(\rho_k = \alpha^k\)</span> it is the bracket in A.6.</p>
</div>
</section>
<section id="references" class="slide level2 smaller">
<h2>References</h2>
<div class="refs">
<p><strong>[R17]</strong>&nbsp; M. A. Rotea, <em>Logarithmic power feedback for extremum seeking control of wind turbines</em>, IFAC-PapersOnLine <strong>50</strong>(1) (2017) 4504–4509. <a href="https://doi.org/10.1016/j.ifacol.2017.08.381">doi:10.1016/j.ifacol.2017.08.381</a></p>
<p><strong>[CLR19]</strong>&nbsp; U. Ciri, S. Leonardi &amp; M. A. Rotea, <em>Evaluation of log-of-power extremum seeking control for wind turbines using large eddy simulations</em>, Wind Energy <strong>22</strong> (2019) 992–1002. <a href="https://doi.org/10.1002/we.2336">doi:10.1002/we.2336</a></p>
<p><strong>[KR22]</strong>&nbsp; D. Kumar &amp; M. A. Rotea, <em>Wind turbine power maximization using log-power proportional-integral extremum seeking</em>, Energies <strong>15</strong> (2022) 1004. <a href="https://doi.org/10.3390/en15031004">doi:10.3390/en15031004</a></p>
<p><strong>[KR24]</strong>&nbsp; D. Kumar &amp; M. A. Rotea, <em>Optimal tip-speed ratio for degraded blades</em>, Wind Energy Science <strong>9</strong> (2024) 2133–2146. <a href="https://doi.org/10.5194/wes-9-2133-2024">doi:10.5194/wes-9-2133-2024</a></p>
<p><strong>[RKAJ24]</strong>&nbsp; M. A. Rotea, D. Kumar, E. J. Aju &amp; Y. Jin, <em>Multi-row extremum seeking for wind farm power maximization</em>, J. Phys. Conf. Ser. <strong>2767</strong> (2024) 032043. <a href="https://doi.org/10.1088/1742-6596/2767/3/032043">doi:10.1088/1742-6596/2767/3/032043</a></p>
<p><strong>[MGR24]</strong>&nbsp; S. P. Mulders, N. Gallo &amp; M. A. Rotea, <em>Analysis of extremum seeking control for wind turbine torque controller optimization by aerodynamic and generator power objectives</em>, ACC (2024). <a href="https://arxiv.org/abs/2407.08059">arXiv:2407.08059</a></p>
<p><strong>[GKN12]</strong>&nbsp; A. Ghaffari, M. Krstić &amp; D. Nešić, <em>Multivariable Newton-based extremum seeking</em>, Automatica <strong>48</strong> (2012) 1759–1767. <a href="https://doi.org/10.1016/j.automatica.2012.05.059">doi:10.1016/j.automatica.2012.05.059</a></p>
<p><strong>[S00]</strong>&nbsp; J. C. Spall, <em>Adaptive stochastic approximation by the simultaneous perturbation method</em>, IEEE Trans. Automat. Contr. <strong>45</strong> (2000) 1839–1853. <a href="https://www.jhuapl.edu/spsa/PDF-SPSA/Spall_TAC00.pdf">PDF</a></p>
<p><strong>[LM23]</strong>&nbsp; C. Lauand &amp; S. Meyn, <em>Quasi-stochastic approximation: design principles with applications to extremum seeking control</em>, IEEE Control Systems Magazine <strong>43</strong> (2023). <a href="https://doi.org/10.1109/MCS.2023.3291884">doi:10.1109/MCS.2023.3291884</a></p>
<p><strong>[A22]</strong>&nbsp; N. J. Abbas et al., <em>A reference open-source controller for fixed and floating offshore wind turbines</em>, Wind Energy Science <strong>7</strong> (2022) 53–73. <a href="https://doi.org/10.5194/wes-7-53-2022">doi:10.5194/wes-7-53-2022</a></p>
<p><strong>[H98]</strong>&nbsp; S. Heier, <em>Grid Integration of Wind Energy Conversion Systems</em>, Wiley (1998). Source of the analytic <span class="math inline">\(C_P(\lambda,\beta)\)</span> fit.</p>
<p><strong>[J09]</strong>&nbsp; J. Jonkman, S. Butterfield, W. Musial &amp; G. Scott, <em>Definition of a 5-MW reference wind turbine</em>, NREL/TP-500-38060 (2009). <a href="https://www.nrel.gov/docs/fy09osti/38060.pdf">PDF</a> &nbsp;·&nbsp; <strong>[IEC]</strong>&nbsp; IEC 61400-1 ed.&nbsp;3, <em>Wind turbines, Part 1: Design requirements</em>, normal turbulence model (2005). <a href="https://webstore.iec.ch/publication/5426">IEC</a></p>
<p><strong>[KWIC72]</strong>&nbsp; J. C. Kaimal, J. C. Wyngaard, Y. Izumi &amp; O. R. Coté, <em>Spectral characteristics of surface-layer turbulence</em>, Q. J. R. Meteorol. Soc. 98, 563–589 (1972). <a href="https://doi.org/10.1002/qj.49709841707">DOI</a></p>
</div>
<div class="footnote">
<p>Companion to <a href="gradient-estimation.html">Extremum Seeking Control of Wind Turbines</a>.</p>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><a href="../../research/wind-esc/index.html">← Wind Turbine Control</a> · The Wind as a Process</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"width":"wide"},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'fast',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 760,

        // Factor of the display size that should remain empty around the content
        margin: 6.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/Symplectomorphism\.github\.io\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>