<!DOCTYPE html>
<html lang="en"><head>
<link href="../../../images/robot-arm-favicon.png" rel="icon" type="image/png">
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Aykut C. Satici">
  <title>Aykut C. Satici – Cams</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/theme/quarto-0427d8d92a431aa6a6430e53ec02a470.css">
  <link rel="stylesheet" href="revealjs-styles.css">
  <link rel="stylesheet" href="kinematics-math.css">
  <script defer="" src="../../../assets/katex/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <link rel="stylesheet" href="../../../assets/katex/katex.min.css">
  <link href="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Cams – Aykut C. Satici">
<meta property="og:description" content="Aykut C. Satici, Associate Professor of Systems Engineering at UT Dallas. Robotics, nonlinear control, and machine learning.">
<meta property="og:image" content="https://Symplectomorphism.github.io/teaching/ug_courses/kinematics/images/robot-control-lab-social.png">
<meta property="og:site_name" content="Aykut C. Satici">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Cams</h1>
  <p class="subtitle">Kinematics and Machine Dynamics · Chapter 13</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Aykut C. Satici
</div>
</div>
</div>

</section>
<section id="chapter-overview" class="slide level2">
<h2>Chapter overview</h2>
<ul>
<li>Specify follower motion over a complete cam revolution.</li>
<li>Construct displacement, velocity, acceleration, and jerk diagrams.</li>
<li>Derive polynomial motion laws for dwell transitions.</li>
<li>Size a radial cam using pressure angle and curvature.</li>
</ul>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-cam-prescribes-a-motion" class="slide level2">
<h2>A cam prescribes a motion</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="assets/final/cam.svg" height="340"></p>
<figcaption>Radial cam, roller follower, pitch curve, and rotation center.</figcaption>
</figure>
</div>
<p>The cam profile imposes a follower displacement <span class="math inline">s(\theta)</span> through contact. Geometry prescribes motion only while contact and the assumed constraints are maintained.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="cam-and-follower-terminology" class="slide level2">
<h2>Cam and follower terminology</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Classification</th>
<th>Examples</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Follower motion</td>
<td>Translation; oscillation</td>
</tr>
<tr class="even">
<td>Cam geometry</td>
<td>Radial disk; cylindrical; spatial</td>
</tr>
<tr class="odd">
<td>Contact shape</td>
<td>Roller; flat-faced; curved sliding follower</td>
</tr>
<tr class="even">
<td>Closure</td>
<td>Force-closed; form-closed</td>
</tr>
</tbody>
</table>
<p>A force-closed follower uses a spring, gravity, or another applied force to maintain contact. A groove or conjugate pair can provide form closure.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-must-the-motion-accomplish" class="slide level2">
<h2>What must the motion accomplish?</h2>
<p><strong>Critical extreme position (CEP):</strong> the follower must reach specified endpoints; the path between them can be designed.</p>
<p><strong>Critical path motion (CPM):</strong> the displacement history itself must follow a prescribed function.</p>
<p>Common programs are rise-fall (RF), rise-fall-dwell (RFD), and rise-dwell-fall-dwell (RDFD).</p>
<p>A dwell is an interval of constant follower displacement.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="start-with-a-timing-diagram" class="slide level2">
<h2>Start with a timing diagram</h2>
<p>Example double-dwell program, one revolution per machine cycle:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Cam angle</th>
<th>Event</th>
<th>Displacement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">0</span>–<span class="math inline">120^\circ</span></td>
<td>Rise</td>
<td><span class="math inline">0\to h</span></td>
</tr>
<tr class="even">
<td><span class="math inline">120</span>–<span class="math inline">180^\circ</span></td>
<td>High dwell</td>
<td><span class="math inline">h</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">180</span>–<span class="math inline">300^\circ</span></td>
<td>Return</td>
<td><span class="math inline">h\to0</span></td>
</tr>
<tr class="even">
<td><span class="math inline">300</span>–<span class="math inline">360^\circ</span></td>
<td>Low dwell</td>
<td><span class="math inline">0</span></td>
</tr>
</tbody>
</table>
<p>The intervals must add to <span class="math inline">360^\circ</span>, and the end of the cycle must join its beginning smoothly.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="svaj-angle-versus-time" class="slide level2">
<h2>S–V–A–J: angle versus time</h2>
<p>Let primes denote derivatives with respect to <strong>cam angle in radians</strong>.</p>
<p>For constant angular speed <span class="math inline">\omega</span>:</p>
<p><span class="math display">v=\omega s',\qquad a=\omega^2s'',\qquad j=\omega^3s'''.</span></p>
<p>A plot of <span class="math inline">s'(\theta)</span> is not yet a physical velocity plot. The speed scale matters: doubling rpm multiplies acceleration by four and jerk by eight.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="if-the-cam-speed-varies" class="slide level2">
<h2>If the cam speed varies</h2>
<p>The chain rule gives</p>
<p><span class="math display">v=s'\omega,</span> <span class="math display">a=s''\omega^2+s'\alpha,</span> <span class="math display">j=s'''\omega^3+3s''\omega\alpha+s'\dot\alpha.</span></p>
<p>Here <span class="math inline">\alpha=\dot\omega</span>. The constant-speed formulas are a special case, not a general identity.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="continuity-at-every-join" class="slide level2">
<h2>Continuity at every join</h2>
<p>For a cam intended to run beyond very low speeds, use continuous displacement, velocity, and acceleration over the complete cycle.</p>
<p>An acceleration jump creates an impulsive jerk in the ideal model and excites vibration in the real mechanism.</p>
<p>A finite jump in jerk can be acceptable in this kinematic criterion; continuous jerk imposes a stronger smoothness requirement.</p>
<p>These conditions must hold at the <span class="math inline">360^\circ/0^\circ</span> join as well.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="why-a-straight-ramp-is-insufficient" class="slide level2">
<h2>Why a straight ramp is insufficient</h2>
<p>A linear rise joined to a dwell has an abrupt velocity change, hence impulsive acceleration.</p>
<p>Simple harmonic rise has zero endpoint velocity, but its nonzero endpoint acceleration does not match a dwell.</p>
<p>The motion law must be chosen for its <strong>boundary conditions</strong>, not just for a visually smooth displacement plot.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="normalize-the-rise-interval" class="slide level2">
<h2>Normalize the rise interval</h2>
<p>For a rise beginning at <span class="math inline">\theta_0</span> and spanning <span class="math inline">\beta</span> radians:</p>
<p><span class="math display">u=\frac{\theta-\theta_0}{\beta},\qquad0\leq u\leq1,</span> <span class="math display">s=h f(u).</span></p>
<p>At constant cam speed:</p>
<p><span class="math display">v=\frac{h\omega}{\beta}f',\quad
a=\frac{h\omega^2}{\beta^2}f'',\quad
j=\frac{h\omega^3}{\beta^3}f'''.</span></p>
<p>Derivatives of <span class="math inline">f</span> are with respect to <span class="math inline">u</span>.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="double-dwell-boundary-conditions" class="slide level2">
<h2>Double-dwell boundary conditions</h2>
<p>A rise connecting two dwells must satisfy</p>
<p><span class="math display">f(0)=0,\quad f(1)=1,</span> <span class="math display">f'(0)=f'(1)=0,</span> <span class="math display">f''(0)=f''(1)=0.</span></p>
<p>Six independent conditions determine six coefficients of a polynomial of degree at most five.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="derive-the-345-polynomial" class="slide level2">
<h2>Derive the 3–4–5 polynomial</h2>
<p>Let <span class="math inline">f(u)=c_0+c_1u+\cdots+c_5u^5</span>.</p>
<p>The conditions at zero give <span class="math inline">c_0=c_1=c_2=0</span>.</p>
<p>At <span class="math inline">u=1</span>:</p>
<p><span class="math display">\begin{bmatrix}1&amp;1&amp;1\\3&amp;4&amp;5\\6&amp;12&amp;20\end{bmatrix}
\begin{bmatrix}c_3\\c_4\\c_5\end{bmatrix}
=\begin{bmatrix}1\\0\\0\end{bmatrix}.</span></p>
<p>Thus <span class="math inline">\boxed{f(u)=10u^3-15u^4+6u^5}</span>.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="differentiate-the-motion-law" class="slide level2">
<h2>Differentiate the motion law</h2>
<p><span class="math display">f'=30u^2-60u^3+30u^4,</span> <span class="math display">f''=60u-180u^2+120u^3,</span> <span class="math display">f'''=60-360u+360u^2.</span></p>
<p>Displacement, velocity, and acceleration match both dwells.</p>
<p>Endpoint jerk is finite but nonzero: <span class="math inline">f'''(0)=f'''(1)=60</span>. It jumps to zero on the dwells.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-complete-double-dwell-program" class="slide level2">
<h2>The complete double-dwell program</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="assets/final/svaj.svg" height="360"></p>
<figcaption>Aligned normalized displacement, velocity, acceleration and jerk curves over one cycle.</figcaption>
</figure>
</div>
<p>Rise and return use the 3–4–5 polynomial; derivatives are with respect to angle. Jerk has finite jumps at the dwell boundaries.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="worked-example-rise-duration-and-velocity" class="slide level2">
<h2>Worked example: rise duration and velocity</h2>
<p>Use <span class="math inline">h=20</span> mm, <span class="math inline">\beta=120^\circ=2\pi/3</span> rad, and 300 rpm.</p>
<p><span class="math display">\omega=10\pi\ \mathrm{rad/s},\qquad T_r=\frac{\beta}{\omega}=\frac1{15}\ \mathrm{s}.</span></p>
<p>The normalized peak speed is <span class="math inline">\max f'=15/8</span> at <span class="math inline">u=1/2</span>:</p>
<p><span class="math display">\boxed{v_{\max}=\frac{0.020}{1/15}\frac{15}{8}
=0.5625\ \mathrm{m/s}.}</span></p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="worked-example-acceleration-and-jerk" class="slide level2">
<h2>Worked example: acceleration and jerk</h2>
<p>For the 3–4–5 polynomial:</p>
<p><span class="math display">\max|f''|=\frac{10\sqrt3}{3},\qquad \max|f'''|=60.</span></p>
<p>With <span class="math inline">h=0.020</span> m and <span class="math inline">T_r=1/15</span> s:</p>
<p><span class="math display">\boxed{|a|_{\max}=\frac{h}{T_r^2}\frac{10\sqrt3}{3}
=25.98\ \mathrm{m/s^2},}</span> <span class="math display">\boxed{|j|_{\max}=\frac{60h}{T_r^3}=4050\ \mathrm{m/s^3}.}</span></p>
<p>The acceleration peaks occur at <span class="math inline">u=(3\mp\sqrt3)/6</span>.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="return-and-dwell-segments" class="slide level2">
<h2>Return and dwell segments</h2>
<p>For a return over <span class="math inline">\beta_f</span> radians beginning at <span class="math inline">\theta_f</span>, let <span class="math inline">u_f=(\theta-\theta_f)/\beta_f</span>.</p>
<p><span class="math display">s=h[1-f(u_f)].</span></p>
<p>The displacement decreases; its derivatives acquire a minus sign and the appropriate powers of <span class="math inline">1/\beta_f</span>.</p>
<p>On the high dwell, <span class="math inline">s=h</span>; on the low dwell, <span class="math inline">s=0</span>. All time derivatives vanish during either dwell.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="continuous-jerk-alternative-4567" class="slide level2">
<h2>Continuous-jerk alternative: 4–5–6–7</h2>
<p>Add the conditions <span class="math inline">f'''(0)=f'''(1)=0</span> to the six dwell conditions.</p>
<p>The resulting seventh-degree polynomial is</p>
<p><span class="math display">\boxed{f(u)=35u^4-84u^5+70u^6-20u^7.}</span></p>
<p>Its jerk matches the dwells continuously. This improves boundary smoothness but does not automatically minimize peak velocity, acceleration, or cam size.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="another-option-cycloidal-rise" class="slide level2">
<h2>Another option: cycloidal rise</h2>
<p><span class="math display">f(u)=u-\frac{\sin(2\pi u)}{2\pi},</span> <span class="math display">f'=1-\cos(2\pi u),\quad f''=2\pi\sin(2\pi u).</span></p>
<p>Displacement, velocity, and acceleration satisfy the double-dwell boundary conditions. Jerk remains finite but jumps at the dwell joins.</p>
<p>Compare candidate laws using peak derivatives, pressure angle, curvature, and the actual load requirements.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="single-dwell-programs" class="slide level2">
<h2>Single-dwell programs</h2>
<p>For rise-fall-dwell motion, the follower reverses at the top without spending an interval there.</p>
<p>At the rise/fall join, enforce the same displacement, zero velocity at a smooth maximum, and matching acceleration.</p>
<p>The common acceleration need not be zero. Separate polynomial segments can meet prescribed join conditions.</p>
<p>Independent boundary conditions must determine a nonsingular coefficient system.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-worked-single-dwell-construction" class="slide level2">
<h2>A worked single-dwell construction</h2>
<p>For one complete rise and fall over <span class="math inline">0\leq u\leq1</span>, use</p>
<p><span class="math display">\boxed{\frac{s}{h}=64u^3(1-u)^3.}</span></p>
<p>The displacement is zero at both ends and equals <span class="math inline">h</span> at <span class="math inline">u=1/2</span>.</p>
<p>Endpoint velocity and acceleration are zero, so it joins a low dwell. At the top, <span class="math inline">s_u=0</span> and <span class="math inline">s_{uu}=-24h</span>: a smooth reversal with nonzero downward acceleration.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="base-circle-prime-circle-and-pitch-curve" class="slide level2">
<h2>Base circle, prime circle, and pitch curve</h2>
<p>The <strong>base circle</strong> is the largest circle centered on the cam axis that fits inside and is tangent to the cam surface.</p>
<p>For a roller follower, the <strong>pitch curve</strong> is the roller-center locus in the cam-fixed frame.</p>
<p>The <strong>prime circle</strong> is the smallest centered radius attained by that pitch curve.</p>
<p>For an in-line radial roller follower at its low dwell, <span class="math inline">R_p=R_b+r_r</span>, where <span class="math inline">r_r</span> is roller radius.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="from-motion-law-to-pitch-curve" class="slide level2">
<h2>From motion law to pitch curve</h2>
<p>For an in-line translating roller follower, define <span class="math inline">r(\theta)=R_p+s(\theta)</span>.</p>
<p>One cam-fixed coordinate convention gives</p>
<p><span class="math display">x_p=r\sin\theta,\qquad y_p=r\cos\theta.</span></p>
<p>Generate the physical cam profile by offsetting the pitch curve inward along its normal by the roller radius.</p>
<p>Simply subtracting the roller radius radially gives the correct result on a circular dwell, but generally not on a rise or return.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="pressure-angle-sizes-the-cam" class="slide level2">
<h2>Pressure angle sizes the cam</h2>
<p>For this in-line translating roller geometry:</p>
<p><span class="math display">\boxed{\tan\phi=\frac{s'}{R_p+s}.}</span></p>
<p>A larger <span class="math inline">R_p</span> reduces the pressure angle for the same motion law. A shorter rise interval increases <span class="math inline">|s'|</span> and tends to increase pressure angle.</p>
<p>Given an allowed angle <span class="math inline">\phi_{\max}</span>, check the entire cycle:</p>
<p><span class="math display">R_p\geq\max_\theta\left(\frac{|s'|}{\tan\phi_{\max}}-s\right).</span></p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="worked-example-a-conservative-size-bound" class="slide level2">
<h2>Worked example: a conservative size bound</h2>
<p>For the 20 mm, <span class="math inline">120^\circ</span> 3–4–5 rise,</p>
<p><span class="math display">\max|s'|=\frac{h}{\beta}\frac{15}{8}=17.90\ \mathrm{mm/rad}.</span></p>
<p>Choose <span class="math inline">\phi_{\max}=30^\circ</span> as a design assumption.</p>
<p>Because <span class="math inline">s\geq0</span>, the sufficient bound</p>
<p><span class="math display">R_p\geq\frac{17.90}{\tan30^\circ}=31.02\ \mathrm{mm}</span></p>
<p>is conservative. Select <span class="math inline">R_p=35</span> mm, then check curvature before accepting the design.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="curvature-of-the-pitch-curve" class="slide level2">
<h2>Curvature of the pitch curve</h2>
<p>For a polar pitch curve <span class="math inline">r=R_p+s</span>, the signed curvature radius is</p>
<p><span class="math display">\boxed{\rho_p=
\frac{(r^2+r'^2)^{3/2}}{r^2+2r'^2-rr''}.}</span></p>
<p>At convex regions, require <span class="math inline">\rho_p&gt;r_r</span> for a regular inward roller offset. Equality produces a cusp; too large a roller can undercut the intended profile.</p>
<p>Inflections and concave regions require their own signed-curvature and interference checks.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="worked-example-roller-and-curvature" class="slide level2">
<h2>Worked example: roller and curvature</h2>
<p>Use the complete double-dwell program, <span class="math inline">R_p=35</span> mm, and <span class="math inline">r_r=5</span> mm.</p>
<p>Sampling the smooth segments gives approximately:</p>
<ul>
<li>peak pressure-angle magnitude <span class="math inline">22.1^\circ</span>;</li>
<li>minimum positive pitch-curve radius <span class="math inline">35.0</span> mm;</li>
<li>base-circle radius <span class="math inline">R_b=30</span> mm.</li>
</ul>
<p>The sampled convex curvature exceeds the roller radius. Refine extrema and check the full manufactured profile before final design.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="contact-forces-and-manufacturing" class="slide level2">
<h2>Contact forces and manufacturing</h2>
<p>A spring-loaded follower needs sufficient preload to maintain compressive contact throughout the motion, accounting for follower inertia and external loads.</p>
<p>A form-closed arrangement avoids separation in the ideal geometry but can experience impact across clearance.</p>
<p>Check material stresses, roller bearings, lubrication, tolerances, cutter access, and surface finish. A smooth displacement law alone does not establish dynamic suitability.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="references-and-course-completion" class="slide level2">
<h2>References and course completion</h2>
<p>Satici, <em>Kinematics and Machine Dynamics</em>, Chapter 13, §§13.1–13.4, pp.&nbsp;103–107, following Norton, <em>Design of Machinery</em>.</p>
<p>Polynomial solutions, plots, numerical examples, and radial roller geometry derivations are instructional additions to the compiled outline.</p>
<p><a href="index.html">Return to the complete course</a>.</p>
<aside class="notes">
<p>Source: Satici, compiled Kinematics and Machine Dynamics notes (Fall 2020), Chapter 13, pp.&nbsp;103–107, following Norton, Design of Machinery. Original diagrams, derivations, and examples extend the source outline; see _planning/remaining-chapters-coverage.md.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="../../../images/monogram_solid-blk.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="../../../teaching/ug_courses/kinematics/index.html">← Course Home</a> · Kinematics and Machine Dynamics · Chapter 13</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 6.0e-2,

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/Symplectomorphism\.github\.io\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>